### ISSUE TITLE
Unable to use hyper-datasets (allegroai doesn't exist)

### ISSUE THREAD

**Issue by mikhail-datoo** [allegroai/clearml#1008]
## Describe the bug
Hi there, hope all is well!

I'm trying to use hyper-datasets, however the [example](https://github.com/allegroai/clearml/blob/master/examples/hyperdatasets/data-registration/register_dataset_masks.py) and the [docs](https://clear.ml/docs/latest/docs/hyperdatasets/frame_groups) use a package called allegroai, which I cannot find on pypi.

Has this functionality been moved to the clearml package - I've tried searching for FrameGroup in this repo but didn't get any results (other than the hyper-datasets example)?

## To reproduce

pip install allegroai
ERROR: Could not find a version that satisfies the requirement allegroai (from versions: none)
ERROR: No matching distribution found for allegroai

## Expected behaviour

Package successfully installed

## Environment

python==3.8.16

**Comment by ainoam** [comment]
Hi @mikhail-datoo,

Hyper-Datasets are only available as part of ClearML's enterprise offering (You'll note the [docs](https://clear.ml/docs/latest/docs/hyperdatasets/overview) say "ClearML Enterprise's Hyper-Datasets supports ...").

We'll try to make that more visible to avoid confusion.

**Comment by mikhail-datoo** [comment]
My bad, thanks very much!
