### ISSUE TITLE
Unable to use `upload_image` functionality in ClearML report

### ISSUE THREAD

**Issue by dinhtungtp** [allegroai/clearml#1020]
## Describe the bug
When I click upload_image button, upload an image, ClearML report show me error `Upload failedHttp failure response for http://192.168.100.141:8081: 0 Unknown Error`

## Environment
* Server type (self hosted)
* ClearML Server Version (Only for self hosted): WebApp: 1.10.1-359 • Server: 1.10.1-359 • API: 2.24
* OS: Linux

## Screen Capture
https://ibb.co/QQt0TPP
Action: click to upload button, choose image, upload => error

**Comment by ainoam** [comment]
Thanks for reporting @dinhtungtp.

A fix should become available in [ClearML Server](https://github.com/allegroai/clearml-server) v1.11 that will be imminently released.

**Comment by pollfly** [comment]
Hey @dinhtungtp! Just letting you know that this issue has been resolved in the recently released [ClearML Server v1.11.0](https://github.com/allegroai/clearml-server/releases/tag/v1.11.0). Let us know if there are any issues :)
