### ISSUE TITLE
pytorch lightning model saving not working with new namespace

### ISSUE THREAD

**Issue by aweinmann** [allegroai/clearml#1032]
PyTorch lightning got renamed to lightning and this changed the namespace to lightning. While the old namespace is still supported the new one does not work with ClearML with regards to model checkpoint saving. 

The trainer got moved from pytorch_lightning to lightning.pytorch and thus https://github.com/allegroai/clearml/blob/66061af1aaa5b3bc447e22da6abac2a966653829/clearml/binding/frameworks/pytorch_bind.py#L113 and the following lines will not work when using the new namespace

**Comment by ainoam** [comment]
Thanks for noting @aweinmann.

Would you like to issue a PR?
