### ISSUE TITLE
Table markdown in report section doesn't work

### ISSUE THREAD

**Issue by dinhtungtp** [allegroai/clearml#1037]
## Describe the bug
Table markdown in report section doesn't work

## Image example
https://ibb.co/jwcqQJc

## Environment
* Server type: self hosted
* ClearML Server Version:  1.11.0-373 
* OS (Windows \ Linux \ Macos): Linux

**Comment by shyallegro** [comment]
Hi, @dinhtungtp 
we'll try to reproduce, can you please share the exact table code you are using here, so we can make sure there isn't some spcial character hiding there.

**Comment by shyallegro** [comment]
Hi @dinhtungtp,
managed to reproduce using your code, it seems your example is using U+2014 : EM DASH instead of an ASCII minus (U+002D : HYPHEN-MINUS {hyphen, dash; minus sign}) this happens some times when moving the code through MS word.

using the following code correctly creates a table.

```
|          | Align Right | Align Left | Align Center |
| -------- | -----------:|:---------- |:------------:|
| 1        |           1 | 1          |      1       |
| 11       |          11 | 11         |      11      |
```

**Comment by dinhtungtp** [comment]
@shyallegro Thank you for your explanation, I can create the table now 🙇 
Let me close this thread 🙇
