### ISSUE TITLE
Using pipeline locally with ssh tunneling uses wrong IP

### ISSUE THREAD

**Issue by lambdaofgod** [allegroai/clearml#1053]
## Describe the bug
I have ClearML server (with **IP1**) and I want to use it by tunneling from another machine **M**.

I did this by creating a tunnel where I redirected ClearML API ports to localhost on M - I edited clearml.conf by replacing **IP1** with localhost.

When I run pipeline I get

```
ValueError: Could not retrieve a local copy of artifact <artifact>, failed downloading http://IP1:8081/<file_path>
```
Which understandably fails because there is no acces to **IP1** from **M**.

This is confusing because when I try to get artifacts outside of pipeline (using `Task`) the url properly uses `localhost` instead of **IP1**.

## Expected behaviour
For artifacts ClearML pipeline should use URL with IP specified in clearml.conf.

## Environment
* Server type: self-hosted
* ClearML SDK Version: clearml==1.10.3
* ClearML Server Version: Server: 1.9.2-317 • API: 2.23
* Python Version
* OS - Linux 20.04

**Comment by jkhenning** [comment]
Hi @lambdaofgod,

>  I edited clearml.conf by replacing IP1 with localhost.

How would ClearML know in this case what is the correct host address?
