### ISSUE TITLE
Specify multipart threshold and chunksize in boto3 configuration

### ISSUE THREAD

**Issue by cgaudreau-ubisoft** [allegroai/clearml#1058]
## Proposal Summary
In the boto3 configuration section of the clearml config it should be possible to specify the threshold and chunksize for doing multipart uploads using S3.

## Motivation
We would like to bypass the multipart upload in certain cases, which means we need to be able to manually set the threshold for the multipart upload.

## Related Discussion
N/A

**Comment by ainoam** [comment]
Thanks for suggesting @cgaudreau-ubisoft 

We'll look into adding support for this.
