### ISSUE TITLE
Add artifacts file path to comparison view

### ISSUE THREAD

**Issue by materight** [allegroai/clearml#1073]
## Proposal Summary
When comparing the artifacts of two tasks, the file path is not shown in the UI.
<img width="1718" alt="image" src="https://github.com/allegroai/clearml/assets/26522190/b9c21af7-40f7-41f4-a346-a7de71de427a">

It would be nice to show the link and make it clickable, like in the artifacts tab:
<img width="1058" alt="image" src="https://github.com/allegroai/clearml/assets/26522190/e5d58d9b-6909-4608-9621-50a3ef2d4c81">

## Motivation
It's a small change (I suppose) and it would help a lot when comparing experiments, since it would allow to open the two artifacts file directly from the comparison view instead of having to go back to the task view and search for them.

**Comment by ainoam** [comment]
Thanks for suggesting @materight.

If I understand correctly, you're saying that it would be useful to be open artifact links directly from comparison, and less about actually seeing the text comparison of artifact URLs?

**Comment by materight** [comment]
Yes exactly, I just want to be able to open the artifact from this view. So it could be either a link, or just printing the url like for the other properties (content type, hash, size...)

**Comment by ainoam** [comment]
@materight Makes complete sense. We'll try to add this in a near version.

**Comment by d13g0** [comment]
+1 👍🏼

**Comment by pollfly** [comment]
Hey @materight! [clearml-server 1.13.0](https://github.com/allegroai/clearml-server/releases/tag/v1.13.0) is now out, with clickable URLs/object IDs in experiment details comparison.

**Comment by materight** [comment]
Great, thanks a lot! Looks good!
