### ISSUE TITLE
Dataset.list_dataset() partial match doesn't work with speical charcters

### ISSUE THREAD

**Issue by natephysics** [allegroai/clearml#1076]
## Describe the bug
Dataset.list_dataset() partial match option doesn't escape special characters, which breaks matching in many cases. Tracing it back, Task._query_tasks() task_name doesn't work with special characters either. I plan to offer a PR with the fix at the _query_tasks() level unless there's a compelling reason otherwise. 

## To reproduce
List datasets with a task name with characters that need to be escaped normally. An example, `[ABC] Name` won't match even if the task name is identical. 

## Expected behaviour
Without any mention of needing to escape special characters, it might make more sense to do it by default.

**Comment by jkhenning** [comment]
@natephysics docstrings were updated to reflect this, as discussed in #1077. I'm closing this 🙂
