### ISSUE TITLE
Docker image for 1.12

### ISSUE THREAD

**Issue by graelo** [allegroai/clearml#1080]
Hi,

You published version `1.12` but the corresponding Docker image was not added.
Could please push it?

Thanks

**Comment by ainoam** [comment]
@graelo Do note that it is **clearml** [v1.12.0](https://github.com/allegroai/clearml/releases/tag/v1.12.0) that has just been released, and not **clearml-server**.
A clearml-server 1.12 is expected in the next few days - Docker images will become available when it is released :)

**Comment by graelo** [comment]
Ah, sorry I got confused, thanks.

| pkg name | Docker image |
| --- | --- |
| `clearml` | None |
| `clearml-server` | `clearml` |
