### ISSUE TITLE
Better info about pipeline step status

### ISSUE THREAD

**Issue by materight** [allegroai/clearml#1090]
## Proposal Summary
Show the current progress and correct elapsed time of running steps in the pipeline view.

## Motivation
Currently the running time always shows `>1s` instead of the actual elapsed time.  
<img width="174" alt="image" src="https://github.com/allegroai/clearml/assets/26522190/0844a047-cef6-4e47-89d2-7403cbf826b9">

It also doesn't show the current progress, it would be nice to have a progress bar similar to the one shown in the experiment list
<img width="521" alt="image" src="https://github.com/allegroai/clearml/assets/26522190/12efcaee-c9c8-4998-8c08-a5ddc7e79cbd">

**Comment by ainoam** [comment]
Thanks for the feedback @materight.

Indeed there seems to be an issue in presenting elapsed time - We'll work on a fix for a near version.

For progress indication - Do note that steps progress needs to be explicitly specified by your step implementation (see [Task.set_progress()](https://clear.ml/docs/latest/docs/references/sdk/task#set_progress))

**Comment by materight** [comment]
Hi @ainoam, thanks for the update.

Re progress indication: in this example I'm calling `set_progress()` on the step task, but the progress bar is shown only if I open the task list view, while I'm proposing to show it also in the pipeline view.

**Comment by ainoam** [comment]
Thanks for clarifying @materight.

Makes total sense - We'll look into supporting this in a near version.

**Comment by pollfly** [comment]
Hey @materight! Just letting you know that the issue of the pipeline step duration not updating has been resolved in the recently released [clearml-server 1.13.0](https://github.com/allegroai/clearml-server/releases/tag/v1.13.0). Let us know if there are any issues :)

**Comment by materight** [comment]
@pollfly thanks for the update. Unfortunately it doesn't seem to be working... Now it doesn't show anything, even after the stap has been completed. 
<img width="175" alt="image" src="https://github.com/allegroai/clearml/assets/26522190/03b4f7df-5fdd-4e03-945a-87bcb54e9767">

**Comment by pollfly** [comment]
Hey @materight! Is the issue with the pipeline step duration not updating still occurring for you? If yes, what `clearml` and clearml-server` versions are you using?

**Comment by materight** [comment]
Yes it looks like it's fixed now, thanks!
