### ISSUE TITLE
Ability to ignore requirements when using PipelineDecorator.pipeline

### ISSUE THREAD

**Issue by JoshuaMeyers** [allegroai/clearml#1093]
## Proposal Summary
additional argument for `pipeline` decorator allowing access to `Task.ignore_requirements("mypkgname")`.

## Motivation
I am running a pipeline using the decorator and a provided docker image. When launching the pipeline, my local environment is synced with the environment in the image. However, because the image is only built periodically, there are sometimes minor differences between my local env and the image env. I would like the option to ignore my local environment.

For normal tasks, I can ignore my local environment using `Task.ignore_requirements("mypkgname")`. But for the pipeline decorator, I cannot access this logic.

I also cannot use `Task.current_task` since the logic is run in the decorator so I don't believe I have access to the task before it fails to resolve requirements.

If there is already a solution for this that I've missed, I'm all ears! Thanks in advance

clearml version: 1.12.2
python version: 3.10.11

**Comment by eugen-ajechiloae-clearml** [comment]
Hi @JoshuaMeyers ! It is indeed not possible to ignore requirements in pipelines. We will add this feature in the future.
