### ISSUE TITLE
Keep Task in running state after script exits

### ISSUE THREAD

**Issue by ngessert** [allegroai/clearml#1134]
I have the following scenario: in a clearml pipeline, I am executing multiple tasks, where one task should run after the other. 

In my setup, I have a clearml agent running on an "entry" machine that picks up the tasks and then submits them via an API to AWS SageMaker. The SageMaker job then picks up the task again executes the actual processing/training. 

My problem is that the task switches to completed after the agent is done with calling the API. Since it shows as completed, the next task is already launched, although the actual job (in SageMaker) hasn't completed yet. 

Thus, I was wondering if I can somehow prevent a task from switching to completed state when exiting in the clearml agent. 

I tried this piece, but it still went to completed afterwards:

```
task_id = current_task.id
current_task.close()
Task.get_task(task_id=task_id).mark_started(force=True)
```

**Comment by jkhenning** [comment]
@ngessert how are you running the agent?

> clearml agent running on an "entry" machine that picks up the tasks and then submits them via an API to AWS SageMaker

Is the agent doing that or your own code? If it's the agent, how did you achieve that?
