### ISSUE TITLE
Parallel dataset verification bug in `master` fails on older versions of Python

### ISSUE THREAD

**Issue by charlienewey-odin** [allegroai/clearml#1144]
## Describe the bug

A recent commit to dataset verification in `dataset.py` has introduced a Python version incompatibility.

This is the commit that introduced the bug: https://github.com/allegroai/clearml/commit/f964783046b07b9edeee02d13a360d7c8dec56e8

The problem is on [this line](https://github.com/allegroai/clearml/commit/f964783046b07b9edeee02d13a360d7c8dec56e8#diff-54d4ebfa8efb319559c3c1d66fb0e002ac617f5226ebc50668295f60a6e4d9e1R3259)

The `cancel_futures` argument was not introduced until Python 3.9 - see Python docs here: https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor.shutdown. This renders `clearml` incompatible with many of the versions advertised in the README.

This bug should not have been able to find its way into `master`. Do ClearML have `tox` tests or similar?

## To reproduce

Validate a dataset with Python <= 3.8.

**Comment by eugen-ajechiloae-clearml** [comment]
Hi @charlienewey-odin ! We already have a fix for this which will be synced with Github soon. Note that this shouldn't have made it to an official release

**Comment by pollfly** [comment]
Hey @charlienewey-odin! Just letting you know that this issue has been resolved in the recently released [v1.13.2](https://github.com/allegroai/clearml/releases/tag/v1.13.2). Let us know if there are any issues :)
