### ISSUE TITLE
Tabular Scalar Comparison

### ISSUE THREAD

**Issue by VasilevGrigoriy** [allegroai/clearml#1152]
Hi! 👋 

In our example in metrics visualisation there is a beautiful [table](https://clear.ml/docs/latest/docs/webapp/webapp_exp_comparing/#tabular-scalar-comparison). 

How I can reproduce this results in my basic version? Or its available only in another versions of ClearML? 

When I only passing values using logger.report_single_value there is not this functionality..

**Comment by ainoam** [comment]
@VasilevGrigoriy This new tabular layout for scalar comparison is part of clearml-server v1.13.0 which should be coming out shortly.

**Comment by VasilevGrigoriy** [comment]
> @VasilevGrigoriy This new tabular layout for scalar comparison is part of clearml-server v1.13.0 which should be coming out shortly.

Thanks for your reply!
