### ISSUE TITLE
GCS credentials not recognized on web app

### ISSUE THREAD

**Issue by materight** [allegroai/clearml#1156]
## Describe the bug
Using the latest version of the `allegroai/clearml` container, the local GCS credentials are not recognized anymore:
<img width="744" alt="image" src="https://github.com/allegroai/clearml/assets/26522190/bb3aa56a-757c-4b05-961d-7e57822f895f">
<img width="994" alt="image" src="https://github.com/allegroai/clearml/assets/26522190/b58dadca-1e51-4158-b623-f17fbc742bbe">

The local credentials should be fine since the first sample can be properly accessed, but any other sample can't. If I try to open the link of one of the unaccessible sample, the browser gets redirected to a `gs://` uri, while the accessible one redirects to `https://storage.cloud.google.com`. If I manually change `gs://` to `https://storage.cloud.google.com`, then I can also open the unaccessible sample.

## To reproduce
Deploy the web app and log some debug samples on GCS.

## Expected behaviour
The samples should show the preview and be accessible from the web interface.

## Environment
* Server type: self hosted
* ClearML SDK Version: 1.13.2
* ClearML Server Version: WebApp: 1.13.0-414 • Server: 1.13.0-414 • API: 2.27
* Python Version: 3.11
* OS: Linux

**Comment by shyallegro** [comment]
Hi @materight 
thanks for reporting, we are trying to reproduce.

**Comment by materight** [comment]
Fixed as of v1.15.0
