### ISSUE TITLE
using nas as a default storage for self hosting server

### ISSUE THREAD

**Issue by sriram-dsl** [allegroai/clearml#1163]
where should i make changes in configuration files to use nas as default storage.
fileserver.conf file is not created after launching the clearml server

**Comment by ainoam** [comment]
@sriram-dsl are you trying to change the underlying storage of the ClearML file server or specify an alternative location for your experiments?

**Comment by sriram-dsl** [comment]
Yes, in specific - nas storage

**Comment by jkhenning** [comment]
@sriram-dsl you cann't set that from the `fileserver.conf` file, you can pass the `CLEARML_UPLOAD_FOLDER` env var pointing to the NAS mount folder for the fileserver

**Comment by sriram-dsl** [comment]
Okay, I will give it a try.

Command:
CLEARML_UPLOAD_FOLDER = <path_to_nas>

I attempted to make changes in the clearml_docker_compose file,
pointing the fileserver data directory to a different path other than
/opt/data/fileserver.
It worked for a regular folder, but it didn't work with the mounted NAS
folder path.
Error: Invalid path.

The NAS was mounted properly,
and file transfer is occurring.

**Comment by jkhenning** [comment]
Did you set set the mount on the host file system? and how did you change the docker-compose file? Can you share?

**Comment by sriram-dsl** [comment]
> .
> [image: WhatsApp Image 2023-11-26 at 21.56.48_fb07cba1.jpg]
>
This is the docker_compose.yml file. I provided a different path instead of
/opt/clearml/data/fileserver, opting for /mnt/fileserver.

This is the path to the folder on Synology:
/run/user/1000/gvfs/ftp:host=synologynas.local/common/clearml. The
following error occurred after using this path:
```

Creating network "clearml_backend" with driver "bridge" Creating network
"clearml_frontend" with driver "bridge" Creating clearml-redis ... Creating
clearml-mongo ... Creating clearml-redis ... done Creating clearml-mongo
... done Creating clearml-elastic ... done ERROR: for clearml-fileserver
Cannot create container for service fileserver: invalid mode:
/mnt/fileserver

ERROR: for fileserver Cannot create container for service fileserver:
invalid mode: /mnt/fileserver ERROR: Encountered errors while bringing up
the project.

```

However, it worked fine with the regular folder path on my local machine.

**Comment by jkhenning** [comment]
So I guess there's some issue with the NAS mount, perhaps incorrect permissions?

**Comment by jkhenning** [comment]
This seems wrong:
```    - /run/user/1000/gvfs/ftp:host=synologynas.local/common/clearml:/mnt/fileserver```

I think this messes up with the docker-compose format - you can't use `:` in the path - can't you mount the NAS in the host to `/mnt/clearml-fileserver` and use this mount in the docker compose file:
```
    - /mnt/clearml-fileserver:/mnt/fileserver
```

**Comment by sriram-dsl** [comment]
sorry for the late reply
i have successfully mounted the nas folder on local machine through nfs share
i have used that nfs accessed nas folder as a data folder, then launched the server
the data is being stored in nas folder

**Comment by sriram-dsl** [comment]
i have tried to mount the nas folder on /opt/clearml
then the data is not being pushed to the server, there might be an issue with api calls
but when i mount the nas folder on /opt/clearml/data/fileserver, then it is working

**Comment by jkhenning** [comment]
So now it's working?

**Comment by sriram-dsl** [comment]
Yes, it is working.
