### ISSUE TITLE
how to change web to light theme?

### ISSUE THREAD

**Issue by Rane2021** [allegroai/clearml#1187]
## Proposal Summary
Explain your proposed feature.

## Motivation
Explain the use case that needs this feature

## Related Discussion
If this continues a slack thread, please provide a link to the original slack thread.

**Comment by ainoam** [comment]
@Rane2021 At this time the ClearML web UI is only available in a single color scheme.

**Comment by Rane2021** [comment]
thanks

**Comment by martinakos** [comment]
Is there a feature request for this? for me is essential to use a light theme.
