### ISSUE TITLE
Task.set_project not working

### ISSUE THREAD

**Issue by CourchesneA** [allegroai/clearml#1190]
## Describe the bug
I am using pytorch lightning, and I use the CLI module. Since the argument parsing happens at the same time as the training, I don't have access to all the information when I call `clearml.Task.init()`. So I set info manually after training + parsing using `mytask.set_project()` and `mytask.set_name()`. The end result is that only the name was set, but the project was not modified.

## To reproduce
```
clearml_task = Task.init(
    project_name="default_project", task_name=f"default_task",
    output_uri="s3://my_uri"
)

cli = pl.CLI(MyModel)  # parse the config file using jsonargparse and train

clearml_task.set_project(cli.config.fit.myproject)        # Doesn't work
clearml_task.move_to_project(cli.config.fit.myproject)    # Also doesn't work
clearml_task.set_name(cli.config.fit.mytaskname)     # This one work

```

## Expected behaviour
Expected:
clearml has task "mytaskname" in project "myproject"

Actual:
clearml has task "mytaskname" in project "default_project"

## Environment
* Server type: clearml cloud
* ClearML SDK Version: 1.14.1
* Python Version: 3.10.12
* OS: ubuntu 22.04
## Related Discussion
https://github.com/allegroai/clearml/issues/1164#issuecomment-1834114634

**Comment by ainoam** [comment]
@CourchesneA Do note that [`set_project()`](https://clear.ml/docs/latest/docs/references/sdk/task#set_project) and [`move_to_project`](https://clear.ml/docs/latest/docs/references/sdk/task#move_to_project) take either project ID or project name, do you should name your parameter (which seems to be what you did [here](https://github.com/allegroai/clearml/issues/1164#issuecomment-1893839809)).

Does this help?

**Comment by CourchesneA** [comment]
That's what I was missing, thanks !
