### ISSUE TITLE
Allow to set the `working_dir` with pipelines from decorators

### ISSUE THREAD

**Issue by materight** [allegroai/clearml#1194]
## Proposal Summary
Add a `working_dir` parameter to `PipelineDecorator.pipeline` and `PipelineDecorator.component` to be able to set the execution working_dir.

## Motivation
Currently when defining a pipeline using `PipelineDecorator.component`, it's only possible to set the `repo` for the script execution, but not the `working_dir`. Therefore it defaults to `.`, and if all the code is inside a subfolder, when running the pipeline remotely the script it's not able to find any local modules.

## Related Discussion
[Original slack thread.](https://clearml.slack.com/archives/CTK20V944/p1706117060205309)

**Comment by ainoam** [comment]
Thanks for suggesting @materight.
We'll try to address this in a near version.

**Comment by pollfly** [comment]
Hey @materight! [v1.15.0](https://github.com/allegroai/clearml/releases/tag/v1.15.0) is now out supporting custom working directory for pipelines

**Comment by materight** [comment]
Great! Thanks a lot
