### ISSUE TITLE
GPU monitoring is missing for experiments

### ISSUE THREAD

**Issue by jdn-kvantify** [allegroai/clearml#1219]
## Describe the bug
Using clearml client  v1.14.4 I do not see any `:monitor:gpu` scalar for my experiments, only `:monitor:machine` with CPU stats is being logged. Downgrading my local cleaml to v1.14.1 brings back the GPU monitoring.

## Environment
* Server type: app.clear.ml
* ClearML SDK Version: 1.14.4
* Python Version: 3.11
* OS : linux (ubuntu)

## Related Discussion

https://clearml.slack.com/archives/CTK20V944/p1709296761463969

**Comment by ainoam** [comment]
Thanks for reporting @jdn-kvantify - We're working on a fix which should become available shortly.

**Comment by ainoam** [comment]
@jdn-kvantify [1.14.5rc0](https://pypi.org/project/clearml/1.14.5rc0/) now available should fix this issue.
