### ISSUE TITLE
Published experiment can be reset from Web UI

### ISSUE THREAD

**Issue by gustavoeb** [allegroai/clearml#1223]
## Description
When a single Published experiment is selected in the Web UI, the Reset option is grayed out - as expected.
When multiple experiments are selected, some Published and some Unpublished, it is possible to use the context menu (right click) to reset all experiments - causing loss of data that should be read-only (Published experiments).

## Reproduction steps
1. Publish one experiment
2. Select one published and one un-published experiment
3. Using the context menu (right-click) trigger the Reset command

## Expected behaviour
I'd expect Published - and therefore read-only - experiments, never to be inadvertently reset. The behaviour should either be throwing an exception, or resetting only experiments that can be reset and multiple are selected.

## Environment
* Server type: self hosted
* ClearML SDK Version: Not applicable, Web UI
* ClearML Server Version: 7.2.0
* Python Version: Not applicable, Web UI
* OS (Windows \ Linux \ Macos): Not applicable, Web UI

**Comment by ainoam** [comment]
Thanks for reporting @gustavoeb.

Latest versions of ClearML server allow only resetting the non-published items out of the selection - Are you using an up to date version? (ClearML server does not yet have a 7.2.0 version. You can check the bottom of the Settings page)

**Comment by gustavoeb** [comment]
Thanks @ainoam. Seems like I was referring to a helm chart tag (7.2.0), which if I understand correctly is actually ClearML 1.11.0? https://github.com/allegroai/clearml-helm-charts/blob/9131a64b38ca76b73724913d849efb5d2f63ce27/charts/clearml/Chart.yaml#L6

Anyways glad to hear this is fixed in later versions. I'll close it for now.
