### ISSUE TITLE
Save hidden/visible scalars layout in "Compare Experiments" tab

### ISSUE THREAD

**Issue by lobanov-m** [allegroai/clearml#1242]
Hello! Thank you for the great tool!

## Proposal Summary
It would be cool if we could save a layout of the hidden and visible scalars in the "Compare Experiments" tab. And maybe reorder scalars graphs.

## Motivation
I am logging many scalars during validation (separate metrics and sub-metrics (like TP, FP, FN) for every class, for every sub-task). And I use "Compare experiments" tab to see if my new experiment is better than the previous one. I look at many graphs, not the single metric, so every time i close the window I need to deselect all scalars and find the needed ones.

Probably, it could be done with "Reports", but as far as I understand, I need to paste model id in every graph by hands every time I want to see the graphs of the new experiment

Thank you!

**Comment by ainoam** [comment]
Thanks for suggesting @lobanov-m.

For maintaining plot comparison have you considered the experiment table [comparison view](https://clear.ml/docs/latest/docs/webapp/webapp_exp_table/#comparing-experiments)? The metric selection for each project is retained.

**Comment by lobanov-m** [comment]
Oh, did not find that at first! Thank you very much, I will try! Looks like it is what I wanted.
