### ISSUE TITLE
Support Megatron-LM training job on k8s cluster

### ISSUE THREAD

**Issue by void-main** [allegroai/clearml#1287]
## Proposal Summary
Please add support for Megatron-LM integration.

## Motivation
We want to train LLM with Megatron-LM, normally we launch tasks by hand on our k8s cluster.

But we want many cool features from clearml, for example, pipelines.

So I wonder if it's possible to launch megatron training job from clearml? If so, are there any documentations on that?

## Related Discussion
None

**Comment by void-main** [comment]
Searched the doc for a little bit, and looks like I should use the [k8s glue](https://github.com/allegroai/clearml-agent/blob/master/examples/k8s_glue_example.py).

The work flow should be like the following:
- setup my own k8s cluster
- install the clearml-helm-charts as described in the [doc](https://clear.ml/docs/latest/docs/deploying_clearml/clearml_server_kubernetes_helm/)
- setup a single queue (as multi queues are not supported in community version)
- start a task with k8s glue

Could anyone please tell me if the understanding is correct? Thanks

@allegro-ai @bmartinn @jkhenning

**Comment by void-main** [comment]
If the above understanding is correct, may I ask how do clear.ml manager the k8s resource conflicts?

For example, what happens when I do the following operations:
0. let's say we have a cluster of 3 nodes;
1. start a task with custom k8s glue code, and it takes up 2 nodes;
2. start a non k8s glue task, and configure the autoscaler for k8s cluster, and the job could go with up to 3 nodes;

Will clear.ml scheduler actually run 3 jobs for the non k8s glue task? Or will the clearml-agent sense the k8s glue code job, and only schedule a single node job?

**Comment by jkhenning** [comment]
Hi @void-main,

You plan seems correct to me. As for the conflict question, there is no conflict - the ClearML k8s glue agent does not take any node, it's simply running as a control-plane pod, and uses k8s to schedule a new pod for every task that it finds in the queue. It's up to k8s to provision the resources and start the task pod (according to the spec/template created by the glue agent)

**Comment by void-main** [comment]
Thanks for the explanation @jkhenning !
