### ISSUE TITLE
async variant of get_mutable_local_copy

### ISSUE THREAD

**Issue by S0NNER10N** [allegroai/clearml#1296]
## Proposal Summary
Need async variant of loading several datasets to mutable local copy

## Motivation
Real case:
- i want run benchmark for 5 different models, hosted as separated k8s pods
- each benchmark uses separate dataset
- i cannot create task group or even spawn task -- get_mutable_local_copy blocks everything until it's completed

**Comment by ainoam** [comment]
@S0NNER10N Have you considered running [separate processes](https://clear.ml/docs/latest/docs/guides/distributed/subprocess_example)?
