### ISSUE TITLE
Scalar logging bug with Fire

### ISSUE THREAD

**Issue by tvelovraf** [allegroai/clearml#1300]
## Describe the bug
ClearML logging of `tf.summary.scalar` outputs seems to be buggy when using with [Python Fire](https://github.com/google/python-fire) package at the same time.
The bug appears in the graph legend labels in ClearML Web UI (**Scalars** section of experiment).

### Case 0
Let's start from the version of code without Fire. There is no bug:

<details><summary>CODE</summary>

```python
from clearml import Task
# import fire
import tensorflow as tf
import os
import argparse


def add_sub(x, y):
    res_add = x + y
    res_sub = x - y
    add_summary = tf.summary.create_file_writer(os.path.join('/home/user/clearfire/logs', "add"))
    sub_summary = tf.summary.create_file_writer(os.path.join('/home/user/clearfire/logs', "sub"))

    with add_summary.as_default():
        tf.summary.scalar("result", res_add, step=0)
        tf.summary.scalar("result", res_add, step=1)
    with sub_summary.as_default():
        tf.summary.scalar("result", res_sub, step=0)
        tf.summary.scalar("result", res_sub, step=1)
    return res_add, res_sub


if __name__ == "__main__":
    Task.init(project_name="examples", task_name='fire_00')
    parser = argparse.ArgumentParser()
    parser.add_argument('--x', type=int)
    parser.add_argument('--y', type=int)
    args = parser.parse_args()
    add_sub(args.x, args.y)
```
</details> 
I run this code with:

```python fire_bug.py --x 3 --y 4 --clearml_task fire_00```

And everything is fine there:
![image](https://github.com/user-attachments/assets/7d55e7fc-082f-4510-8f04-d9434225adb7)

### Case 1
Now let's add Fire in our code:

<details><summary>CODE</summary>

```python
from clearml import Task
import fire
import tensorflow as tf
import os


def add_sub(x, y):
    res_add = x + y
    res_sub = x - y
    add_summary = tf.summary.create_file_writer(os.path.join('/home/user/clearfire/logs', "add"))
    sub_summary = tf.summary.create_file_writer(os.path.join('/home/user/clearfire/logs', "sub"))

    with add_summary.as_default():
        tf.summary.scalar("result", res_add, step=0)
        tf.summary.scalar("result", res_add, step=1)
    with sub_summary.as_default():
        tf.summary.scalar("result", res_sub, step=0)
        tf.summary.scalar("result", res_sub, step=1)
    return res_add, res_sub


if __name__ == "__main__":
    Task.init(project_name="examples", task_name='fire_01')
    fire.Fire(
        {
            "addsub": add_sub,
        }
    )
```
</details> 

Run this code with:
```python fire_bug.py addsub --x 3 --y 4```

And there comes the bug. One of the graph labels have become "**unknown 1: result**" istead of "**sub: result**" (as it was in **Case 0**):
![image](https://github.com/user-attachments/assets/bd134281-e14d-4e93-9a50-ebe1ec13d07e)

### Case 2
If I put `Task.init` under the function scope:

<details><summary>CODE</summary>

```python
from clearml import Task
import fire
import tensorflow as tf
import os


def add_sub(x, y):
    Task.init(project_name="examples", task_name='fire_02')
    res_add = x + y
    res_sub = x - y
    add_summary = tf.summary.create_file_writer(os.path.join('/home/user/clearfire/logs', "add"))
    sub_summary = tf.summary.create_file_writer(os.path.join('/home/user/clearfire/logs', "sub"))

    with add_summary.as_default():
        tf.summary.scalar("result", res_add, step=0)
        tf.summary.scalar("result", res_add, step=1)
    with sub_summary.as_default():
        tf.summary.scalar("result", res_sub, step=0)
        tf.summary.scalar("result", res_sub, step=1)
    return res_add, res_sub


if __name__ == "__main__":
    fire.Fire(
        {
            "addsub": add_sub,
        }
    )
```
</details> 

and run code the same way — the bug is still there (just as in the **Case 1**).

### Case 3
The only workaround I found is to place ClearML import under the function scope:

<details><summary>CODE</summary>

```python
import fire
import tensorflow as tf
import os


def add_sub(x, y):
    from clearml import Task
    Task.init(project_name="examples", task_name='fire_03')
    res_add = x + y
    res_sub = x - y
    add_summary = tf.summary.create_file_writer(os.path.join('/home/rafael/clearfire/logs', "add"))
    sub_summary = tf.summary.create_file_writer(os.path.join('/home/rafael/clearfire/logs', "sub"))

    with add_summary.as_default():
        tf.summary.scalar("result", res_add, step=0)
        tf.summary.scalar("result", res_add, step=1)
    with sub_summary.as_default():
        tf.summary.scalar("result", res_sub, step=0)
        tf.summary.scalar("result", res_sub, step=1)
    return res_add, res_sub


if __name__ == "__main__":
    fire.Fire(
        {
            "addsub": add_sub,
        }
    )
```
</details> 

Runnig code the same way and bug is "fixed":
![image](https://github.com/user-attachments/assets/2b589c83-fbcd-4679-9f2f-06cc811d3e8d)

However, Fire integration have become unused :(

## Expected behaviour
Graph labeling should work the same way in all above cases.

## Environment
Server type - self hosted
ClearML SDK Version - 1.16.2
ClearML Server Version (Only for self hosted) - WebApp: 1.15.1-478 • Server: 1.15.1-478 • API: 2.29
Python Version - 3.10.14
OS - Ubuntu 20.04.06 LTS
Python Fire Version - 0.6.0
Tensorflow Version - 2.14.0
Tensorboard version - 2.14.1

**Comment by ainoam** [comment]
Thanks for reporting @tvelovraf - We'll take a look.

**Comment by tvelovraf** [comment]
@ainoam I did some inspection of this problem.

As I wrote [there](https://github.com/allegroai/clearml/pull/1275) Fire call is [wrapped](https://github.com/allegroai/clearml/blob/54418060ae94179a35bfef00c83c292ebfa5f13d/clearml/binding/fire_bind.py#L62) with `__patched_call` by ClearML.
So, all code wrapped by Fire itself is executed under the scope of [that call](https://github.com/allegroai/clearml/blob/54418060ae94179a35bfef00c83c292ebfa5f13d/clearml/binding/frameworks/__init__.py#L34). And just before of that call, current thread `ident` is [added](https://github.com/allegroai/clearml/blob/54418060ae94179a35bfef00c83c292ebfa5f13d/clearml/binding/frameworks/__init__.py#L31C9-L31C25) into the `_recursion_guard` dict. 

Next, I call `tf.summary.create_file_writer` (see code in **Case 1** of this issue), which in turn calls (somewhere deep inside) `gen_summary_ops.create_summary_file_writer` which is also [wrapped](https://github.com/allegroai/clearml/blob/fa0ba104c4c9cd790f4d52eb5d2fd0db2432af92/clearml/binding/frameworks/tensorflow_bind.py#L1281) with `__patched_call`.
But in the end, instead of calling wrapped version of `gen_summary_ops.create_summary_file_writer` ClearML [calls the original one](https://github.com/allegroai/clearml/blob/54418060ae94179a35bfef00c83c292ebfa5f13d/clearml/binding/frameworks/__init__.py#L30).
This is because we are still under the Fire scope and current thread `ident` was already added into the `_recursion_guard` dict as I mentioned few lines above. 

I'm sure this is the cause of the bug. And this could potentially be a problem for all `__patched_call` wrapped functions (if Fire is used along).
But I'm not sure how to fix it if not removing this [check](https://github.com/allegroai/clearml/blob/54418060ae94179a35bfef00c83c292ebfa5f13d/clearml/binding/frameworks/__init__.py#L29)... :)

**Comment by eugen-ajechiloae-clearml** [comment]
Hi @tvelovraf ! We might want to use this function instead in the affected function https://github.com/allegroai/clearml/blob/54418060ae94179a35bfef00c83c292ebfa5f13d/clearml/binding/frameworks/__init__.py#L47. 
Do you intend on opening a PR for this issue?

**Comment by tvelovraf** [comment]
Hi @eugen-ajechiloae-clearml! Oh, I missed there is such function, thanks
Yea, I would like to open a PR.

I see Fire support was released earlier than `_patched_call_no_recursion_guard` function appeared.
Do you think there are no any potential danger in using no_recursion_guard version for Fire wrapping?

**Comment by eugen-ajechiloae-clearml** [comment]
@tvelovraf as long as the function is not recursive (CallAndUpdateTrace seems not to be recursive), it should be ok. You could run all the examples in https://github.com/allegroai/clearml/tree/master/examples/frameworks/fire to verify that nothing breaks after the change.

**Comment by tvelovraf** [comment]
@eugen-ajechiloae-clearml OK, I will check the examples and open a PR in nearest time
