### ISSUE TITLE
Add_external_files for Hyperdatsets 

### ISSUE THREAD

**Issue by jennzhugewps** [allegroai/clearml#1306]
## Proposal Summary
I would like to have this function for Hyperdatasets:
https://clear.ml/docs/latest/docs/references/sdk/dataset/#add_external_files

## Motivation
I can rewrite get_frames for azure:
def get_frames(container_link):
    # Parse the container link to get the account URL, container name, and folder path
    account_url, container_name, folder_path = parse_azure_link(container_link)
    
    # Create a BlobServiceClient
    blob_service_client = BlobServiceClient(account_url=account_url)
    
    # Get the container client
    container_client = blob_service_client.get_container_client(container_name)
    
    # List the blobs in the specified folder
    blob_list = container_client.list_blobs(name_starts_with=folder_path)
    
    # Generate single frames
    ret_frames = []
    for blob in blob_list:
        blob_url = f"{account_url}/{container_name}/{blob.name}"
        ret_frames.append(SingleFrame(source=blob_url))
    
    return ret_frames

but then I need to rewrite it again for a different cloud storage. It would be nice if add_external_files could handle that.

**Comment by ainoam** [comment]
Thanks for suggesting @jennzhugewps. However, Hyper-datasets are not part of the ClearML open source offering.
ClearML Enterprise offering support is provided through its dedicated support channel.
