### ISSUE TITLE
Many ClearML Dataset functions and parameters not available for Hyperdatasets, also it would be clearer to change name of allegroai Dataset to Hyperdataset 

### ISSUE THREAD

**Issue by jennzhugewps** [allegroai/clearml#1309]
## Proposal Summary
Hi, while switching my code over from normal Datasets to Hyperdatasets with enterprise, I noticed that many of the basic functions available for Datasets are not available for Hyperdatasets including but not limited to:
- Dataset.rename (can only rename a Hyperdataset through the web app)
- Dataset.set_description
- Dataset.add_external_files
- Dataset.move_to_project

Additionally, when I am looking at documentation for Datasets vs Hyperdatasets, they are both named Dataset but one is from clearML package and one is from allegroai package. I sometimes mix up which type I'm looking at when I'm reading the docs. It would be clearer if allegroai Dataset was renamed to Hyperdataset.

## Motivation
It would be great if we could have all these functionalities, including all the available parameters in the normal Dataset version, especially since allegroai is supposed to be a superset of the clearml package. Specifically, I need the functions I listed to manage my API that connects to clearML.

For add_external_files, without this function for Hyperdatasets, I have to import each blob storage package separately, ex: from azure.storage.blob import BlobServiceClient, and then figure out how to parse that blob storage link for each storage provider because they have different functions. Whereas with add_external_files, all you need to provide is a direct link and it handles the different providers for you.

It would be less confusing when going through the docs if allegroai Dataset was renamed to Hyperdataset since clearML Dataset already exists. 

## Related Discussion
https://wildlifeprotection.slack.com/archives/C06J8A11VV1/p1722879053626809

**Comment by ainoam** [comment]
@jennzhugewps As mentioned in #1306 - Issues in this repository are only for the ClearML open source offering.
Enterprise offering features such as Hyper-datasets should be advanced through Enterprise support channels.
