### ISSUE TITLE
Issues while using `clearml-data search` CLI

### ISSUE THREAD

**Issue by abviv** [allegroai/clearml#1321]
## Describe the bug
![image](https://github.com/user-attachments/assets/cc7af818-d727-40c9-aeb7-60da41e78cc7)
I am getting the above error while trying to use the clearml-data search command.

I am using clearml==1.16.4
## To reproduce
Exact steps to reproduce the bug. Provide example code if possible.
Given
## Expected behaviour
What is the expected behaviour? What should've happened but didn't?
This should've returned the proper list of datasets which i have already uploaded.

## Environment
* Server type (self hosted )
* ClearML SDK Version
* ClearML Server Version (Only for self hosted). Can be found on the bottom right corner of the settings screen. I am running the following verison:

![image](https://github.com/user-attachments/assets/d81b7ae7-3743-4a8f-b2bf-f4e30319e0c1)

* Python Version = 3.12.2 
* OS ( Linux)
## Related Discussion
If this continues a slack thread, please provide a link to the original slack thread.

**Comment by ainoam** [comment]
Thanks for reporting @abviv, we'll take a look.

**Comment by d-vignesh** [comment]
Hi @ainoam , tested this bug out. It seems like the version of the dataset is None in some cases.
<img width="908" alt="image" src="https://github.com/user-attachments/assets/7837060c-2428-4c21-b78e-0b253f19cbf2">

Adding a condition to assign version value as "" in this [line](https://github.com/allegroai/clearml/blob/99db5e77cd911fdc24ad2fa0cc635c556cdb048a/clearml/cli/data/__main__.py#L659) when its None is fixing the issue. Would this fix be enough? 
<img width="674" alt="image" src="https://github.com/user-attachments/assets/80de12df-fa5c-4593-a58b-efc8293ff262">

**Comment by abviv** [comment]
@d-vignesh Could you please create a new branch and do a pull request? I can test it locally.

**Comment by d-vignesh** [comment]
@abviv can you please try the above branch and test.

**Comment by d-vignesh** [comment]
@abviv did you get a chance to test this?

**Comment by pollfly** [comment]
Hey @abviv! Just letting you know that this issue has been resolved in the recently released [v1.16.5](https://github.com/allegroai/clearml/releases/tag/v1.16.5). Let us know if there are any issues :)
