### ISSUE TITLE
delete dataset from minio by WebUI

### ISSUE THREAD

**Issue by lolpa1n** [allegroai/clearml#1324]
Hello!, I want to delete data from minio via the webui, I was able to delete via the SDK, but via the web version they remain in minio.
Is there such a function? I just don't want to delete all datasets via SDK

**Comment by oren-allegro** [comment]
Hi @lolpa1n ,

You should have a service called async_delete
Depending on your server setup (docker-compose or K8s) - you can define the following variable in the async_delete service:
`CLEARML__services__storage_credentials__aws__s3__credentials=[{host:"your-minio.domain.com:443",key:"12345678",secret:"AaBbCcDd1234567890"}]`

This will allow the server to also erase the minio artifacts when deleting tasks and datasets.
