### ISSUE TITLE
ClearML frontend does not include the cookies to get the plot.

### ISSUE THREAD

**Issue by feicccccccc** [allegroai/clearml#1331]
## Describe the bug

The fronted does not include the cookies when fetching the plot from the file server.
i.e. Getting the plot from frontend
![image](https://github.com/user-attachments/assets/1d2c104d-7a82-4cc3-b38d-5cc8399599d8)
![image](https://github.com/user-attachments/assets/eebbdde9-b45c-408c-9453-c7e193e940d2)

Getting the plot directly from the url
![image](https://github.com/user-attachments/assets/720e16bd-fca4-47cf-b82c-bff614d84b45)

## To reproduce
Exact steps to reproduce the bug. Provide example code if possible.

## Expected behaviour
What is the expected behaviour? What should've happened but didn't?
The images show on the frontend.

## Environment
* self-host
* ClearML SDK Version
* ClearML Server Version (Only for self hosted). Can be found on the bottom right corner of the settings screen.
WebApp: 1.16.2-502 • Server: 1.16.2-502 • API: 2.30
* Python Version
* OS (Windows \ Linux \ Macos)
## Related Discussion
If this continues a slack thread, please provide a link to the original slack thread.

**Comment by oren-allegro** [comment]
@feicccccccc - this will be fixed in the upcoming version.
As a workaround - you can add the following env variable to the webserver service:
`WEBSERVER__useFilesProxy` and set it to `true`

For example, if using docker-compose - add to the webserver service dfinitions:
```
    environment:
      WEBSERVER__useFilesProxy: "true"

```

**Comment by feicccccccc** [comment]
Checked and confirmed it works.
