### ISSUE TITLE
Tables reporting does not work

### ISSUE THREAD

**Issue by lolpa1n** [allegroai/clearml#1343]
Hello!
I want to log 3 dataframes (train, val, test)
Sizes respectively:
train - 20mb (50k rows)
val - 7mb (20k rows)
test - 7mb (20k rows)
I can log val and test successfully, but not train. There are no error messages during logging. The dataframes are identical. What could be the reason for this?
Logged using:
`logger.report_table(title=f'Dataframe {TAG} train', series='pandas DataFrame', iteration=0, table_plot=train_df)`
or
`logger.report_table(title=f'Dataframe {TAG} train', series='pandas DataFrame', iteration=0, csv='train_balanced.csv')`

**Comment by shomratalon** [comment]
Hi @lolpa1n ,

There seems to be a size limit for table reporting (~15MB), though it's strange that the log didn't mention it. I'll look into the log reporting for this and add the relevant logging message in the next ClearML version.

For uploading large files like this, I recommend using the `upload_artifact` method. This will allow you to access and download the file from the UI or SDK for future use.

Some docs and examples about artifacts can be found [here](https://clear.ml/docs/latest/docs/clearml_sdk/task_sdk/#artifacts)
