### ISSUE TITLE
L

### ISSUE THREAD

**Issue by 1atAlcone** [allegroai/clearml#1350]
## Proposal Summary
Explain your proposed feature.

## Motivation
Explain the use case that needs this feature

## Related Discussion
If this continues a slack thread, please provide a link to the original slack thread.

**Comment by 1atAlcone** [comment]
> ## Proposal Summary
> Explain your proposed feature.
> 
> ## Motivation
> Explain the use case that needs this feature
> 
> ## Related Discussion
> If this continues a slack thread, please provide a link to the original slack thread. 

The

**Comment by ainoam** [comment]
Seems like an erroneous submission
