### ISSUE TITLE
download model is not working

### ISSUE THREAD

**Issue by omricarmi** [allegroai/clearml#171]
when I press right click on the model and then download nothing happens.
![ezgif-6-55636281b035](https://user-images.githubusercontent.com/5064959/87643209-38f4c600-c753-11ea-8cd3-44cc7999c954.gif)

**Comment by jkhenning** [comment]
Hi @omricarmi ,

I suspect the reason is that the link to the model has the `file://` scheme - i.e. a local file, not uploaded to the Trains Fileserver (or any other remote storage).

I think the issue here is that for these kind of links (files), the Trains WebApp should not provide the option to download, since it can't - this file is a local file stored in your machine's (or a remote machine's) file system, and cannot be accessed by the browser...

Sounds reasonable?

**Comment by omricarmi** [comment]
Make sense. Still the server is on the same machine that the model file is.
So maybe the server can expose this file for download somehow.

**Comment by jkhenning** [comment]
> So maybe the server can expose this file for download somehow.

Since the server can't know whether the file is on the same machine (I suppose that usually people will not run the server on their own development machine), as well as how to get to that file if it is (this will require additional configurations in the docker-compose file to allow the server access to additional folders on your file system).

For that reason, Trains Server includes the Fileserver. All you have to do is to provide Trains with `output_uri` pointing to your file server. For example, if Trains Server is deployed on the same machine:
```python
task = Task.init(project_name="my project", task_name="my task", output_uri="http://localhost:8081")
```

**Comment by omricarmi** [comment]
If file server is configured in trains configuration file is it enough?

**Comment by jkhenning** [comment]
No, the default setting in the configuration file is for using the files server for debug images and other "temporary" stuff, not for model snapshots upload.

You'll need to use the `output_uri` argument as described above, or set another configuration file setting `sdk.development.default_output_uri`

**Comment by sdesrozis** [comment]
That works perfectly well using `output_uri` pointing to `http://<train-server>:8081` for a local trains server.

But, in browser, the model link is not clickable. However, the uri is correct, if I copy/paste in web browser, the model is downloaded. It should be a nice improvment to have a clickable link. Is it possible ?

**Comment by jkhenning** [comment]
Hi @sdesrozis, 

Do you mean the `http://<trains-server>:8081/path/to/file.ext` link is not clickable?

I just verified it using this small testing code (of course `/path/to/model.bin` is an actual file 🙂):
```python
from trains import Task
task = Task.init(project_name="examples", task_name="model upload", output_uri="http://<my-trains-server-ip>:8081")
task.update_output_model_and_upload("/path/to/model.bin", "my model", iteration=10)
```

You should see the output model in the ARTIFACTS tag, under MODELS, and the `Output Model` information should contain a link to the model entity in the system. In the model entity info panel (which opens in a new browser tab), you should see a MODEL URL field. While the link there is not clickable, there should be a download icon immediately following the link - this icon will appear if the link is such that can be downloaded by the browser (so the icon will not appear if your link starts with `file://`)

Do you see anything different?

**Comment by sdesrozis** [comment]
Hi @jkhenning 

Thank you for your detailled anwswer. Let me check it. Note that my usage is slightly different than your snippet. I use `Pytorch-ignite` integration so model is uploaded when `torch.save(...)` is called, I don't use `task.update_output_model_and_upload(...)`.

`trains` version is 0.16.1 (`trains-server` from git).

**Comment by jkhenning** [comment]
@sdesrozis, I might be that in your Trains Server version, the download icon will follow the link to the model entity that appears in the experiment's `ARTIFACTS/MODELS/Output Model` - see in this example (screenshot taken from the Trains Demo Server):

![model_download](https://user-images.githubusercontent.com/59198928/94941108-1dd95d00-04dd-11eb-9429-b973de28ef40.png)

**Comment by sdesrozis** [comment]
@jkhenning I confirm that the ion is following the link. Note that if I have multiple artifact, no icon is available neither clickable link.

![Capture d’écran de 2020-10-05 11-18-32](https://user-images.githubusercontent.com/10013598/95062215-fc56bc00-06fc-11eb-900d-be332cc1d95f.png)

**Comment by jkhenning** [comment]
@sdesrozis just making sure I understand - this is the model's info view - are you saying that the icon does not show in the model's info panel (after the model link) if the experiment itself has multiple artifacts in the Experiment info panel/ARTIFACTS/OTHER section?

**Comment by ainoam** [comment]
@sdesrozis No doubt a straight forward button will be convenient. In the mean time, did you notice the model context menu (those 3 lines at the info card top right corner) has a download button that does just that?

![image](https://user-images.githubusercontent.com/51905810/95074911-f8846300-0717-11eb-82f0-152d4e7c8c4c.png)

**Comment by sdesrozis** [comment]
@ainoam Thank you for pointing out that very useful context menu ! I didn't catch it ! It works perfectly.
