### ISSUE TITLE
failed to use local trains with AWS AMI deployment

### ISSUE THREAD

**Issue by omricarmi** [allegroai/clearml#174]
Hi,
I deployed trains server using ami to AWS.
i can get to the webapp through x.x.x.x:8080
but when trying to run python code with trains integration it fails on:

> Retrying (Retry(total=239, connect=240, read=239, redirect=240, status=240)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='x.x.x.x', port=8008): Read timed out. (read timeout=3.0)")': /auth.login
> Retrying (Retry(total=238, connect=240, read=238, redirect=240, status=240)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='x.x.x.x', port=8008): Read timed out. (read timeout=3.0)")': /auth.login
> Retrying (Retry(total=237, connect=240, read=237, redirect=240, status=240)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='x.x.x.x', port=8008): Read timed out. (read timeout=3.0)")': /auth.login
> 

I configured the trains.conf file as the guide says:

> api {
>     # Notice: 'host' is the api server (default port 8008), not the web server.
>     api_server: https://x.x.x.x:8008
>     web_server: https://x.x.x.x:8080
>     files_server: https://x.x.x.x:8081
>     # Credentials are generated using the webapp, http://localhost:8080/profile
>     credentials {"access_key": "O*******", "secret_key": "V*********"}
> }

**Comment by jkhenning** [comment]
Hi @omricarmi,

Did you configure your AWS AMI for HTTPS access? I assume that when you access the WebApp using `x.x.x.x:8080`, it resolves to `http://x.x.x.x:8080` - is that correct?

Please try changing your `trains.conf` file to:

api {
api_server: **http**://x.x.x.x:8008
web_server: **http**://x.x.x.x:8080
files_server: **http**://x.x.x.x:8081
credentials {"access_key": "O*******", "secret_key": "V*********"}
}

**Comment by omricarmi** [comment]
I changed t http and still same error

**Comment by allegroai-git** [comment]
@omricarmi I assume this was solved - please reopen if this is still an issue
