### ISSUE TITLE
How to stop background worker/daemon?

### ISSUE THREAD

**Issue by omricarmi** [allegroai/clearml#178]
How to stop background worker/daemon?
couldn't find in docs.

**Comment by JDennisJ** [comment]
Hi @omricarmi ,

Actually we are going to release RC version supporting stop for trains-agent daemon very soon (will keep you updated about it 😄 ). 
For now, the best way is to kill the process, I use `pkill -f trains` for doing it, but `pgrep -af trains` with `kill` or any other method will work.

**Comment by omricarmi** [comment]
Great. that what I did too. but because my trains-server and trains-agent are on the same machine I used:
`ps aux | grep "trains-agent daemon" | cut -d " " -f 2 | xargs kill -9`
else it would kill trains-server

**Comment by JDennisJ** [comment]
Right, grepping `trains-agent` is much better 👍

**Comment by bmartinn** [comment]
Hi @omricarmi 
With `trains-agent` v 0.16 we now have `--stop` to stop a running daemon 🚀 
For example:
```console
trains-agent daemon --gpus 0,1 --queue dual_gpu --detached
trains-agent daemon --gpus 2,3 --queue dual_gpu --detached
```
Stopping the first agent (GPU 0+1):
```console
trains-agent daemon --gpus 0,1 --queue dual_gpu --stop
```
See details in the [release notes](https://github.com/allegroai/trains-agent/releases/tag/0.16.0)
