### ISSUE TITLE
can't sign in to trains

### ISSUE THREAD

**Issue by boazpe** [allegroai/clearml#180]
Hi,
been using trains now for almost a year now. I installed it by deploying the AWS AMI, i think it's version V0.12.0. 
Not sure what changed, but i can't sign in to it, i.e, i get the trains sign in screen, enter my user name, click start, but nothing happens. 
I tried to reboot the EC2 it's installed on but no luck.

What do you suggest?

Thanks,
Boaz

**Comment by boazpe** [comment]
Just found out the problem, went out of disk space in the EC2.
If i deploy a new EC2, is there a way to migrate all the data (logs, scalars, models..)?

**Comment by jkhenning** [comment]
Hi @boazpe ,

Did you just increase the storage size on the EC2 instance you've been working on, or did you do a fresh installation on a new machine?

**Comment by boazpe** [comment]
Did a fresh installation on a new EC2

**Comment by jkhenning** [comment]
I assume you backed up your data and moved it to the new instance?
If so, did you make sure the restored data has the appropriate permissions (folder owner, as per the installation guide)?
Also, can your browser's Developer's panel Network tab before you try to login (i.e. before you enter the name and press `Enter`), and than send a screenshot of the results shown in the panel?

**Comment by boazpe** [comment]
Hi Jake, 
The sign-in issue seemed to be resolved: looking at developer tools i saw that port 8008 is not reachable, once I opened it in AWS console and used trains-user I'm able to sign-in.

I still can't get to see my projects from old EC2. 
I backed up following the instructions in docs (BTW didn't terminate old EC2 yet). 
than copied the back up files to new EC2 and unzipped them as in the instructions.

didn't see anything about " appropriate permissions " in the guide though..  could you direct me please?

Thanks again,
Boaz

**Comment by jkhenning** [comment]
Hi @boazpe,

After restoring the files into `/opt/trains`, make sure the owner is `uid` 1000, using `sudo chown 1000:1000 -R /opt/trains` - let me know if it helps...

> didn't see anything about " appropriate permissions " in the guide though

You're right... this is not mentioned in the instructions (and we should probably add it), only in the installation instructions (Step 8 in the Trains Server [Linux and Mac OS X](https://allegro.ai/docs/deploying_trains/trains_server_linux_mac/) installation instructions)

**Comment by boazpe** [comment]
tried " sudo chown 1000:1000 -R /opt/trains" but i still don't see the projects from old EC2.

just to make sure I did the steps correctly:

on old EC2:
1. `sudo tar czvf ~/trains_backup_data.tgz -C /opt/trains/data .`
`sudo tar czvf ~/trains_backup_config.tgz -C /opt/trains/config .` 

copied files to new EC2

on new EC2:
2. `docker-compose down`
3. `sudo rm -fR /opt/trains/data/* /opt/trains/config/*`
`sudo tar -xzf ~/trains_backup_data.tgz -C /opt/trains/data`
`sudo tar -xzf ~/trains_backup_config.tgz -C /opt/trains/config`
4. `sudo chown 1000:1000 -R /opt/trains`
5. `sudo reboot`

missed anything?

**Comment by jkhenning** [comment]
>  i still don't see the projects from old EC2.

When you say that, do you mean you see nothing, or do you see other stuff (like the default examples project)?
If you see nothing, what exactly does that mean? Do you get an operational WebApp, just without any experiments and projects, or do you see a blank screen? I'd appreciate a screenshot 😄

**Comment by boazpe** [comment]
Currently I see only a new experiment I created using the new EC2.
At some point I did see examples & samples but I'm not sure when and what I did after (didn't delete them, but I tried to install trains-server few times, some with MarketPlace some with community AMI). 

![image](https://user-images.githubusercontent.com/44225960/89108924-6e80fb00-d445-11ea-91a1-c54d420c7159.png)

**Comment by jkhenning** [comment]
This seems odd. A few things:

1. Are you using fixed user/password settings, or simply login using a name?
1. Can you try clearing out `/opt/trains/data` (you can simply move it to a different directory), restoring the data again, and sending a screenshot as well as the mongo and apiserver logs? (for the logs, use `sudo docker logs trains-apiserver` and `sudo docker logs trains-mongo`)

**Comment by boazpe** [comment]
So I installed trains-server from scratch again and i still can't manage to load old projects.
BTW they also don't load in old EC2, but that's maybe because of low disk space, i'm not sure..

When I installed trains-server, I do get examples projects etc.. , they are cleared since i do `sudo rm -fR /opt/trains/data/* /opt/trains/config/*` so that's why in the screenshot above they do not appear.

another issue is that before I do  `sudo rm -fR /opt/trains/data/* /opt/trains/config/*` I can sign in with any user name (when I use community install) but after I clear config & data I can sign in only with 'trains-user'.

I'll move on and leave my old projects behind (it's ok i have most of the models backed up anyway)

Thanks again,
Boaz

**Comment by jkhenning** [comment]
> another issue is that before I do sudo rm -fR /opt/trains/data/* /opt/trains/config/* I can sign in with any user name (when I use community install) but after I clear config & data I can sign in only with 'trains-user'.

This is since the default configuration does not use Fixed Users, and your configuration (from the old EC2 instance) probably defines a fixed user named `trains-user`, which seems to indicate the old configuration is applied correctly...

With regards to the old data, it's really very strange. If you'll have the time, I'd appreciate seeing the complete logs from the mongodb and apiserver dockers, just in case they can point us to any issue.

Thanks for using Trains and taking the time to help us improve it 😄 👍
