### ISSUE TITLE
Uploads to local Minio server is slow

### ISSUE THREAD

**Issue by csseaky** [allegroai/clearml#189]
Hi!

I have a local MinIO set up in my computer. When I use the MinIO browser, I can upload any file with 50 - 100 MB per second as its local.
However when I try to upload with task.upload_artifact it uploads with 500 KB/second. Why is that?

**Comment by bmartinn** [comment]
Hi @csseaky ,
Could you attache some information on your setup ?
- minio server version
- boto3 / botocore / s3transfer package version
- trains package version
- minio server <-> client machine network connection (LAN?! / speed)
- minio server machine OS
- trains client OS

I just tested on the latest minio server with `trains==0.16 boto3==1.14.43 botocore==1.17.43 s3transfer==0.3.3` on two ubuntu machines (LAN), all looks okay and upload speed match max network speed.

You can also quickly test with this code:

```python
from trains import StorageManager
from time import time
tic = time()
StorageManager.upload_file(
    '/home/user/my_large_file_here.bin',
    's3://minio_ip:9000/bucket_name/my_large_file_here.bin'
)
print(time() - tic)
```

```

**Comment by csseaky** [comment]
Hi!

With the code you've posted, it took 0.57 seconds to upload 33 MB. It works.
However, when I use task.upload_artifact it is slow. Why could it be?

I assume there is nothing wrong with libraries and MinIO server etc. because your code works.

**Comment by bmartinn** [comment]
Hi @csseaky ,
:rocket: Trains 0.16.1 was released with a fix to the minio slow upload
```bash
pip install trains==0.16.1
```
