### ISSUE TITLE
[Feature Request]: Demo for integrate app server

### ISSUE THREAD

**Issue by LMerCy** [allegroai/clearml#200]
As for object detection task, we usually need to visualize the detection results. We can now implement this by report_image, but upload or create new image would cost both a huge bandwidth/storage. 

So can u give a demo about how to integrate an app server,such as this: [dash-detr](https://github.com/plotly/dash-detr), so we can just save prediction results, when we open the web ui, we can load the image and the detection results if needed, at the same time we can add many customized features if we want.

**Comment by bmartinn** [comment]
Hi @LMerCy ,

Regrading detection results, if these are for debug purposes, using the `report_image` sounds like the right choice.

If you are concerned with storage, images (and any debug sample object) will overwrite old files (based on iteration).
You can control the history size by setting the [sdk.metrics.file_history_size](https://github.com/allegroai/trains/blob/19822419b66413351c2f6cdba097effae0993a86/docs/trains.conf#L32) in your `trains.conf` file.
Notice that the history is based on the combination of title/series of any image, meaning the default behavior is the last 100 images per each unique combination of title/series.

If you are thinking of an app like [dash-detr](https://github.com/plotly/dash-detr) , you can use the `trains-agent` to run it, and then just point to the application server, by either using the artifacts (`task.upload_artifact('app', 'http://localhost:8080/app')`) , or the debug samples (`logger.report_media('app', 'server', url='http://localhost:8080/app')`), or simply print it to the console.

What do you think?

**Comment by LMerCy** [comment]
@bmartinn

**Comment by LMerCy** [comment]
@bmartinn 
Thanks, the second option can solve my problem!
