### ISSUE TITLE
Missing data, "Retrying, failed logging task to bacnend (0 lines); missing data" and memory leak?

### ISSUE THREAD

**Issue by oak-tree** [allegroai/clearml#205]
Hey,
We are using `trains 0.13`. We sometimes experience the following reporting:
![image](https://user-images.githubusercontent.com/667153/92488296-074e2780-f1f7-11ea-818c-e4fecddf00a9.png)

We do not understand when it happens or what is the cause, but it seems that this error causes a memory leak and eventually disrupting our training procedure.

When the error appears the memory graph indicated some leak as can be seen : 
![image](https://user-images.githubusercontent.com/667153/92488828-b7bc2b80-f1f7-11ea-880e-115dbc03d14a.png)

Any idea how to resolve this issue?

## EDIT: 
trains `server version` is 0.13, trains packages (`trains.__version__`) is `0.16.1`

**Comment by bmartinn** [comment]
Hi @oak-tree ,

From the graph it seems the memory increase is periodic, I would guess it has something to do with epochs ending/starting...
(Notice that free memory is system wide, while used memory is process specific)

Regrading the actual error:
> We sometimes experience the following reporting:

Are you also getting network errors? 
What is the setup of the machine running the code (OS, frameworks, python version etc.)?
Are you running the experiment with `trains-agent` or manually ?

BTW:
Any reason why you are not upgrading the `trains-server` ?

**Comment by oak-tree** [comment]
Hey @bmartinn 

We do think that the memory increasing i.e the memory leak and trains error are correlated. 

Note that the graph has some mislead information, the sum of the `used` with the `free` does not sum into the initialize value of the `free memory`. This can be seen clearly at the end where the sum is less than 20GB but the whole memory as can be seen at the start is above 20GB. So i'm guess some memory is not reported in the chart. 


Outsetup:
## Machine OS:
Training is done from Kubeflow over GKE. Machines from GKE manged version running:
`Container-Optimized OS from Google. Version 77`
The container runs `trains` over this machine runs:
`Ubuntu 18.04.3 LTS (Bionic Beaver)`

## Trains server OS
We are using K8S over Azure for trains, i.e running AKS:
`trains-server OS` -  `Ubuntu-1604-202003`


## Python version 
`Python 3.6.9`

## Tensorflow 
```tf.__version__ 2.3.0```

But we saw those errors on `tf` 2.2.0 as well



## Upgrading 
There is a change in the latest versions of trains that we need to upgrade manually the `data` so we did not find the time yet to do it :)

**Comment by bmartinn** [comment]
@oak-tree 
There is an RC available with a fix, could you verify it solved the issue ?
```
pip install trains==0.16.2rc0
```

**Comment by oak-tree** [comment]
Thanks for the quickpatch. We'll test it ASAP

**Comment by oak-tree** [comment]
Hey @bmartinn 

We still get the same error
![image](https://user-images.githubusercontent.com/667153/92741503-5cb93e80-f387-11ea-9ef7-81818b74a001.png)
Trains version is `0.16.2rc0` as can be seen here:
![image](https://user-images.githubusercontent.com/667153/92741604-76f31c80-f387-11ea-962f-efa33e6c7059.png)

**Comment by bmartinn** [comment]
Oh no :(
@oak-tree could you maybe breakpoint [here](https://github.com/allegroai/trains/blob/10ec4d56fb4a1f933128b35d68c727189310aae8/trains/backend_api/session/session.py#L344), and send the trace (i.e. stack so I know where the error originates from)

**Comment by bmartinn** [comment]
@oak-tree I forgot to mention the fix is already part of the latest `trains` release.
``` bash
pip install trains==0.16.2
```
