### ISSUE TITLE
Allow a global way to disable the demo server

### ISSUE THREAD

**Issue by Shaked** [allegroai/clearml#209]
In order to prevent human/developers mistakes, we would like to have a global way maybe by using an environment variable or by instantiating a `Task` which disables the demo servers call, so that if a developer forgets to update his `trains.conf` for whatever reason, trains won't report the data to the demo servers. 

Personally, I believe that the ideal approach would be to disable it **by default** and allow devs to use it via environment variable or an init parameter. 

What do you think?

Shaked

**Comment by bmartinn** [comment]
Hi @Shaked 

The reason for the default demoserver is simple, it is very easy to start working when you literally do not need to configure a single thing :)
That said, I can totally see what you mean regrading the potential leak...

One way to go about it is to actually block the demo server on your company's firewall (a.k.a add it to the fixed hosts and set it to an invalid address)

Are you suggesting we should have an environment variable disabling the use of the demoserver ?
Is that easier to maintain on developers machines ?

**Comment by Shaked** [comment]
@bmartinn 

I totally understand the reason for the default demoserver, it is much easier to quickly start using trains and get the feeling of how it works, talking from my own personal experience here :) 

> One way to go about it is to actually block the demo server on your company's firewall (a.k.a add it to the fixed hosts and set it to an invalid address)

We have thought about this solution, but the problem with that is that it might be tricky for us in some cases to control all entrypoints due to the environments that we are working on. This might create a room for developers to forget, same as they might misconfigure their `trains.conf` and end up hitting the demo server. 

> Are you suggesting we should have an environment variable disabling the use of the demoserver ?
Is that easier to maintain on developers machines ?

Ideally it would be better to have it disabled and then allow developers to enable it via something like `TRAINS_DEMO_ENABLED=TRUE`, same as developers can change the path of trains' configuration file i.e `TRAINS_CONFIG_FILE=/path/to/trains.conf`. Having said that, I understand that this is a product decision, and if this cannot happen, the other solution would be to set `TRAINS_DEMO_ENABLED=FALSE` by default and allow developers to override it on their own environments. 

Thank you for replying so quickly!
Shaked

**Comment by bmartinn** [comment]
> I totally understand the reason for the default demoserver, it is much easier to quickly start using trains and get the feeling of how it works, talking from my own personal experience here :)

Thank you so much for that! Iy is truly hard to make ML/DL complex solutions easy to on board and I'm glad we are on the right track. BTW if you have suggestions for improvement, please feel free to share them.

Actually I might have a solution, what about setting the `TRAINS_API_HOST` to your local server?
This will prevent any demoserver access, and will actually override any misconfigured or missing `trains.conf` 
For example, you could mandate `~/.profile` to have:
```
export TRAINS_API_HOST="http://my_local_trains_server:8008"
```

WDYT?

**Comment by Shaked** [comment]
@bmartinn, 

I think that it won't be good enough as it still opens a room for developer mistakes. We cannot pass these variables directly to our Dockerfiles, so we will have to run the containers using environment variables instead.

I think that if it's not possible to disable the demo by default, it would be better to have a dedicated environment variable that we could toggle in order to enable/disable the demo settings. I believe that `TRAINS_DEMO_ENABLED=<bool>` would be a good enough solution for that so we could just put it directly in our Dockerfiles. 

I hope this makes sense

**Comment by bmartinn** [comment]
> We cannot pass these variables directly to our Dockerfiles

Why not? How else would you pass the suggested `TRAINS_DEMO_ENABLED` environment variable ?

Following the `TRAINS_DEMO_ENABLED` suggestion, if it is set to `true` and there is no `~/trains.conf`, what do you think we should do, throw exception ? switch to offline mode ?

**Comment by Shaked** [comment]
> Why not? How else would you pass the suggested TRAINS_DEMO_ENABLED environment variable ?

The main difference here is that ideally we would like to avoid saving configuration such as domains, secrets etc in our docker images as developers may forget about them, might use wrong values by mistake etc etc, instead we pass our configuration while running our containers and that way we integrate everything with k8s (either a configMap, secret  or a volume). 

Using an environment variable such as `TRAINS_DEMO_ENABLED` is harmless and can even be hardcoded within the Dockerfile. 

> Following the TRAINS_DEMO_ENABLED suggestion, if it is set to true and there is no ~/trains.conf, what do you think we should do, throw exception ? switch to offline mode ?

I would suggest to throw an exception

**Comment by bmartinn** [comment]
> Using an environment variable such as TRAINS_DEMO_ENABLED is harmless and can even be hardcoded within the Dockerfile.

Not objecting here, just trying to understand the restrictions IT security impose. What you are saying is that it is okay to have a harmless env as part of the docker image (a.k.a `TRAINS_DEMO_ENABLED`), but that `TRAINS_API_HOST` is not a harmless environment variable (even though you can still override its value from an external env file / k8s yaml file) ?

**Comment by Shaked** [comment]
Well, I believe that from a security perspective, it would be best to save sensitive or relatively sensitive configuration and secrets in one place such as a vault and then share it only whenever needed, for example while running a container. Images might somehow leak and be in the open, either by a mistake or by purpose and ideally they shouldn't have anything about the org attached to them. 

When I think about `TRAINS_API_HOST` I think about an internal host, which even though it's or it's not open for the world, I'd rather hide it from it as much as possible. 

From a devops perspective I believe that configuration should always be injected i.e `trains.conf` but `TRAINS_DEMO_ENABLED` is not exactly a configuration, it's actually a bridge to overcome a design decision (the support of the default demo setting). Once it's there, it tells nothing about the env and will never be replaced in any case. It will only effect docker images (or Dockerfiles) where `trains` is installed and used. 

What do you think?

**Comment by bmartinn** [comment]
>  I think about an internal host, which even though it's or it's not open for the world, I'd rather hide it from it as much as possible.

Point taken :+1: 

I think it all makes sense, I mean it will not fully solve this type of leakage but it will definitely mitigate the problem :)

Okay I think er have feature here. 
When `TRAINS_DISABLE_DEMO_SERVER` is set, the system will not default to the `trains` demo server configuration, and will raise an exception "Configuration file or environment could not be located and default demo server is disabled"  (Or something along those lines)

WDYT?

**Comment by Shaked** [comment]
Sounds great. 

If you can point me to where this all should happen, I can make a PR. 

Thank you :)

**Comment by bmartinn** [comment]
@Shaked Yes, please PR it :)
Thank you!

**Comment by Shaked** [comment]
> @Shaked Yes, please PR it :)
> Thank you!
> 
> References :
> [Defines](https://github.com/allegroai/trains/blob/master/trains/backend_api/session/defs.py)
> [Demo server address](https://github.com/allegroai/trains/blob/b84a78186025c71ed4dd234af7c78bb0bb32b5eb/trains/backend_api/session/session.py#L60)
> [Server definition check](https://github.com/allegroai/trains/blob/b84a78186025c71ed4dd234af7c78bb0bb32b5eb/trains/backend_api/session/session.py#L139)

Done https://github.com/allegroai/trains/pull/213

**Comment by bmartinn** [comment]
@Shaked I forgot to mention here, this is already part of the latest `trains` release
```
pip install trains==0.16.2
```
