### ISSUE TITLE
Failed to get Plot Charts

### ISSUE THREAD

**Issue by DdHms** [allegroai/clearml#210]
I'm getting the following error while trying to view plots.
`Failed to get Plot Charts
``Error 100 : General data error (TransportError(400, 'search_phase_execution_exception', 'failed to create query: `
I connected to an existing task which I am not quite sure what plots were sent but I sent a report_scatter3d to the same logger
I saw issue #197  but the solution there does not seem to work.
Thanks in advance

**Comment by bmartinn** [comment]
Hi @DdHms 
What is the exact call that fails? Are you logging directly with trains Logger ?
What's the trains & trains-server versions you are using ?
Any chance you could provide the full exception log ?

**Comment by allegroai-git** [comment]
@DdHms please reopen and provide more info if this is still an issue
