### ISSUE TITLE
Multiple tasks in a single training script

### ISSUE THREAD

**Issue by KirkHadley** [allegroai/clearml#211]
How do I create and subsequently destroy multiple tasks in a single training script? The context is that within a given run I build distinct models for users, and I would like to track those users' training processes as independent tasks. Or perhaps there's a better way of doing this?

**Comment by bmartinn** [comment]
Hi @KirkHadley 

>I would like to track those users' training processes as independent tasks.

I'm not sure what you mean by that, if you are creating the Tasks how would the users use those Tasks?

Regrading creating / destroying (do you mean deleting? or aborting ?)

Creating a new experiment:
```python
from trains import Task
additional_experiment = Task.create(project_name='examples', task_name='new experiment 1')
```

Edit the experiment (i.e. point to a specific git repository etc.)
```python
data = additional_experiment.export_task()
# data now contains all the fields of the experiment, so you know what you can edit
additional_experiment.update_task(data)
```

Archive an experiment, probably safer than deleting it:
```python
additional_experiment.set_system_tags(additional_experiment.get_system_tags() + ["archived"])
```

For completeness, delete an experiment:
```python
from trains.backend_api.session.client import APIClient
client = APIClient()
client.tasks.delete(task=additional_experiment.id, force=True)
```
