### ISSUE TITLE
Handling unpushed commits

### ISSUE THREAD

**Issue by odedbd** [allegroai/clearml#222]
I think it would be great if Trains would know to handle unpushed commits properly. Consider the following use case - 
1. I make some changes to my code
2. commit them locally (one or more commits)
3. do **not** push them to origin
4. run my script
5. clone the Dev task and enqueue to run on my GPU server

The clone execution would fail because the saved commit is not available on the remote repository (no push). My particular use case is that we are using git submodules, which means that every push can actually be two or even three pushes (depending on how many of the submodules I had to change). Moreover, I prefer committing early, but would rather not to have to push my code all the time.

I thought of several ways this could be addressed, from the quick and dirty to more involved-

1. Trains could diff against origin/foo instead of local foo (where foo is my current local branch). This should work since the origin/foo commit should be in the remote repo. The downside is that it ignores the local commit structure and uncommitted changes will not be separated from committed yet unpushed changes.

2. Similar to 1. but log both the diff vs. local foo and the diff vs. origin/foo. When running the task try fetching the local commit from the remote (perhaps it has been pushed by now); if the commit is unavailable fall back to using the diff vs. origin foo. In the task UI you can show the uncommitted changes.

3. Log the local commits separately. The same scheme as 2. can be used (i.e. trying with a fallback) and the UI can show the unpushed commits separately, as a log of commit messages or with diff from previous.

I'm sure there are many other options to go about this as well. Will be happy to hear more ideas & thoughts on this.

**Comment by bmartinn** [comment]
Hi @odedbd 
I think this is a great idea, and as you mentioned I believe implementation should be simple enough.
Basically: `git diff origin/master` (instead of local HEAD) and get the `commit id` of origin/master (instead of local HEAD).
This means that from the `trains-agent` perspective nothing changes (which is great).
A few thoughts:
1. It might be a bit confusing to see uncommitted changes, when you know everything is committed (even if only locally).
2. When comparing two experiments, the code might actually be the same but one would point to a commit id without changes and the other on a previous commit, with uncommitted changes which are basically the last local commit...
3. I would make this feature configurable via the `~/trains.conf` , probably disabled by default.

What do you think?

**Comment by odedbd** [comment]
@bmartinn thanks for the feedback,

I think a diff from origin/master should work, but it may be worth the while to make it a little more nuanced. Perhaps it is better to compare to the origin HEAD of the remote tracking branch of the local branch, rather than master. Perhaps that's what you meant, but just gave master as an example.

I agree about 1-2, but that's a trade-off that's more than worth it for my use case. Also, these could be mitigated with my suggestions 2-3 in the OP.

I think your 3. is a good idea, can also make it configurable via the Task api, similar to set_docker_base.

**Comment by bmartinn** [comment]
> compare to the origin HEAD of the remote tracking branch of the local branch, rather than master. Perhaps that's what you meant, but just gave master as an example.

Apologies, you are correct I meant the origin HEAD (not the actual remote master)

> log both the diff vs. local foo and the diff vs. origin/foo. 

For that we need full server +  UI support, which I believe would require too much work at this point. Worth remembering though :)

> make it configurable via the Task api, similar to set_docker_base.

Wouldn't that be a bit odd? It would mean you control someone else's configuration (when they are running the same code base), what's the use case here?

**Comment by odedbd** [comment]
> Wouldn't that be a bit odd? It would mean you control someone else's configuration (when they are running the same code base), what's the use case here?

The use case is a research project where O(1) researcher is working on the code. Setting this up via task allows me to selectively use this feature for different projects I am working on. An alternative could be to add support for an additional, per project, trains.conf that allows for overriding the defaults (if there is such an option I haven't seen it).

**Comment by jkhenning** [comment]
Hi @odedbd,

Sorry, forgot to update - this was handled in ClearML v0.17.5

Closing this issue, please reopen if needed 🙂
