### ISSUE TITLE
[Question] Can task associated with multiple output models?

### ISSUE THREAD

**Issue by cksac** [allegroai/clearml#224]
Hi, would like to know if trains support multiple output models in one task?

**Comment by JDennisJ** [comment]
Hi @cksac 

You can have several models in the same task, but the task is associated with one model. If you like, you can use artifacts to store links to additional models. Can this do the trick?

**Comment by jkhenning** [comment]
Hi @cksac,

I'm closing this issue, please reopen if needed. Thanks!
