### ISSUE TITLE
Cuda version in train.conf

### ISSUE THREAD

**Issue by tomeramit** [allegroai/clearml#229]
Hi,

I don't want to set the cuda version in the trains.conf file, because sometimes I want to use cuda 10.1 and sometimes cuda 10.0
if I dont define it, it goes automaticly to cuda 10.2, (even thought I have specific package of cudatoolkit 10)
and then it crush somewhere during installation.

adding logs, let me know what to do

(the main problem is here in this line
2020-10-25T17:02:19.945Z lv-beast:gpu0,1 DEBUG Executing Conda: /home/lv-beast/miniconda3/condabin/conda install -p /home/lv-beast/.trains/venvs-builds/3.5 -c simpleitk -c pytorch -c astra-toolbox/label/dev -c conda-forge -c defaults -c intel cudatoolkit=10.2 --quiet --json, it add cudatoolkit=10.2, and I dont want this phrase to be set at all)

2020-10-25T17:01:09.763Z lv-beast:gpu0,1 INFO task ee82c2092b834a3b85a5fb7c6054e66a pulled from ca9acd7a32df49e5b4ea41760e252be7 by worker lv-beast:gpu0,1

2020-10-25T17:01:14.800Z lv-beast:gpu0,1 DEBUG Current configuration (trains_agent v0.16.2rc0, location: /tmp/.trains_agent.71n7mnuk.cfg):
----------------------
sdk.storage.cache.default_base_dir = ~/.trains/cache
sdk.storage.cache.size.min_free_bytes = 10GB
sdk.storage.direct_access.0.url = file://*
sdk.metrics.file_history_size = 100
sdk.metrics.matplotlib_untitled_history_size = 100
sdk.metrics.images.format = JPEG
sdk.metrics.images.quality = 87
sdk.metrics.images.subsampling = 0
sdk.metrics.tensorboard_single_series_per_graph = false
sdk.network.metrics.file_upload_threads = 4
sdk.network.metrics.file_upload_starvation_warning_sec = 120
sdk.network.iteration.max_retries_on_server_error = 5
sdk.network.iteration.retry_backoff_factor_sec = 10
sdk.aws.s3.key = 
sdk.aws.s3.region = 
sdk.aws.boto3.pool_connections = 512
sdk.aws.boto3.max_multipart_concurrency = 16
sdk.log.null_log_propagate = false
sdk.log.task_log_buffer_capacity = 66
sdk.log.disable_urllib3_info = true
sdk.development.task_reuse_time_window_in_hours = 72.0
sdk.development.vcs_repo_detect_async = true
sdk.development.store_uncommitted_code_diff = true
sdk.development.support_stopping = true
sdk.development.default_output_uri = 
sdk.development.force_analyze_entire_repo = false
sdk.development.suppress_update_message = false
sdk.development.detect_with_pip_freeze = false
sdk.development.worker.report_period_sec = 2
sdk.development.worker.ping_period_sec = 30
sdk.development.worker.log_stdout = true
sdk.development.worker.report_global_mem_used = false
sdk.development.detect_with_conda_freeze = false
agent.worker_id = lv-beast:gpu0,1
agent.worker_name = lv-beast
agent.force_git_ssh_protocol = false
agent.python_binary = 
agent.package_manager.type = conda
agent.package_manager.pip_version = <20.2
agent.package_manager.system_site_packages = true
agent.package_manager.force_upgrade = false
agent.package_manager.conda_channels.0 = simpleitk
agent.package_manager.conda_channels.1 = pytorch
agent.package_manager.conda_channels.2 = astra-toolbox/label/dev
agent.package_manager.conda_channels.3 = conda-forge
agent.package_manager.conda_channels.4 = defaults
agent.package_manager.conda_channels.5 = intel
agent.package_manager.torch_nightly = false
agent.venvs_dir = /home/lv-beast/.trains/venvs-builds
agent.vcs_cache.enabled = true
agent.vcs_cache.path = /home/lv-beast/.trains/vcs-cache
agent.venv_update.enabled = false
agent.pip_download_cache.enabled = true
agent.pip_download_cache.path = /home/lv-beast/.trains/pip-download-cache
agent.translate_ssh = true
agent.reload_config = false
agent.docker_pip_cache = /home/lv-beast/.trains/pip-cache
agent.docker_apt_cache = /home/lv-beast/.trains/apt-cache
agent.docker_force_pull = false
agent.default_docker.image = nvidia/cuda:10.1-runtime-ubuntu18.04
agent.git_user = tomer.amit
agent.default_python = 3.7
agent.cuda_version = 102
agent.cudnn_version = 0
api.version = 1.5
api.verify_certificate = true
api.default_version = 1.5
api.http.max_req_size = 15728640
api.http.retries.total = 240
api.http.retries.connect = 240
api.http.retries.read = 240
api.http.retries.redirect = 240
api.http.retries.status = 240
api.http.retries.backoff_factor = 1.0
api.http.retries.backoff_max = 120.0
api.http.wait_on_maintenance_forever = true
api.http.pool_maxsize = 512
api.http.pool_connections = 512
api.api_server = http://192.168.2.94:8008
api.web_server = http://192.168.2.94:8080
api.files_server = http://192.168.2.94:8081
api.credentials.access_key = IQ4BUOO3Q27ZPICO096M
api.host = http://192.168.2.94:8008

Executing task id [ee82c2092b834a3b85a5fb7c6054e66a]:
repository = https://bodyvisionmedical.visualstudio.com/LungVision/_git/MachineLearning
branch = develop
version_num = a34c4289123b7804fd028c8975c7c1cc7e5ec0b9
tag = 
docker_cmd = 
entry_point = training_script.py
working_dir = LvObjects/Lv3D/TomoGan/scripts

Executing Conda: /home/lv-beast/miniconda3/condabin/conda env remove -p /home/lv-beast/.trains/venvs-builds/3.5 --quiet --json

Remove all packages in environment /home/lv-beast/.trains/venvs-builds/3.5:

2020-10-25T17:02:19.945Z lv-beast:gpu0,1 DEBUG Executing Conda: /home/lv-beast/miniconda3/condabin/conda install -p /home/lv-beast/.trains/venvs-builds/3.5 -c simpleitk -c pytorch -c astra-toolbox/label/dev -c conda-forge -c defaults -c intel cudatoolkit=10.2 --quiet --json

2020-10-25T17:03:25.081Z lv-beast:gpu0,1 DEBUG Pass

Using cached repository in "/home/lv-beast/.trains/vcs-cache/MachineLearning.2f27b16d384a01d04c7eedd7180ff087/MachineLearning"
Fetching submodule LungVision
Fetching submodule LungVision

2020-10-25T17:03:30.121Z lv-beast:gpu0,1 DEBUG Note: switching to 'a34c4289123b7804fd028c8975c7c1cc7e5ec0b9'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at a34c428 Merged PR 3663: arrange data helper functions

2020-10-25T17:03:45.329Z lv-beast:gpu0,1 DEBUG type: git
url: https://bodyvisionmedical.visualstudio.com/LungVision/_git/MachineLearning
branch: HEAD
commit: a34c4289123b7804fd028c8975c7c1cc7e5ec0b9
root: /home/lv-beast/.trains/venvs-builds/3.5/task_repository/MachineLearning

Executing Conda: /home/lv-beast/miniconda3/condabin/conda install -p /home/lv-beast/.trains/venvs-builds/3.5 -c simpleitk -c pytorch -c astra-toolbox/label/dev -c conda-forge -c defaults -c intel 'pip<20.2' --quiet --json

2020-10-25T17:04:55.461Z lv-beast:gpu0,1 DEBUG Pass
Conda: Trying to install requirements:
['certifi~=2018.08.24', 'google_api_python_client~=1.7.12', 'httplib2~=0.18.1', 'imgaug~=0.2.9', 'joblib~=0.14.1', 'matplotlib~=2.2.2', 'nose~=1.3.7', 'numba~=0.39.0', 'oauth2client~=4.1.3', 'pandas~=0.23.4', 'Pillow~=5.0.0', 'plotly~=4.8.2', 'pox~=0.2.8', 'pytorch~=1.2.0', 'scikit_learn~=0.20.0', 'scipy~=1.1.0', 'semantic_version~=2.8.5', 'tabulate~=0.8.2', 'torchvision~=0.4.0', 'tqdm~=4.48.2', 'graphviz', 'python-graphviz', 'kiwisolver']
Executing Conda: /home/lv-beast/miniconda3/condabin/conda env update -p /home/lv-beast/.trains/venvs-builds/3.5 --file /tmp/conda_envgcrfwcr9.yml --quiet --json

2020-10-25T17:06:00.585Z lv-beast:gpu0,1 DEBUG Conda error: ResolvePackageNotFound: 
  - scikit_learn~=0.20.0
  - google_api_python_client~=1.7.12
Conda: Trying to install requirements:
['certifi~=2018.08.24', 'httplib2~=0.18.1', 'imgaug~=0.2.9', 'joblib~=0.14.1', 'matplotlib~=2.2.2', 'nose~=1.3.7', 'numba~=0.39.0', 'oauth2client~=4.1.3', 'pandas~=0.23.4', 'Pillow~=5.0.0', 'plotly~=4.8.2', 'pox~=0.2.8', 'pytorch~=1.2.0', 'scipy~=1.1.0', 'semantic_version~=2.8.5', 'tabulate~=0.8.2', 'torchvision~=0.4.0', 'tqdm~=4.48.2', 'graphviz', 'python-graphviz', 'kiwisolver']
Executing Conda: /home/lv-beast/miniconda3/condabin/conda env update -p /home/lv-beast/.trains/venvs-builds/3.5 --file /tmp/conda_env6oc180h4.yml --quiet --json

2020-10-26T01:16:30.108Z lv-beast:gpu0,1 DEBUG Conda error: UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (cudatoolkit):

  - pytorch~=1.2.0 -> cudatoolkit[version='10.0.*|9.2.*|>=10.0,<10.1|>=9.2,<9.3']
  - torchvision~=0.4.0 -> cudatoolkit[version='>=10.0,<10.1|>=10.0.130,<10.1.0a0|>=10.1,<10.2|>=9.2,<9.3|>=9.2,<9.3.0a0']
  - torchvision~=0.4.0 -> pytorch==1.2.0 -> cudatoolkit[version='10.0.*|9.2.*']

The following specifications were found to be incompatible with each other:

Package cudatoolkit conflicts for:
cudatoolkit=10.2
Conda: Trying to install requirements:
['certifi~=2018.08.24', 'httplib2~=0.18.1', 'imgaug~=0.2.9', 'joblib~=0.14.1', 'matplotlib~=2.2.2', 'nose~=1.3.7', 'numba~=0.39.0', 'oauth2client~=4.1.3', 'pandas~=0.23.4', 'Pillow~=5.0.0', 'plotly~=4.8.2', 'pox~=0.2.8', 'scipy~=1.1.0', 'semantic_version~=2.8.5', 'tabulate~=0.8.2', 'tqdm~=4.48.2', 'graphviz', 'python-graphviz', 'kiwisolver']
Executing Conda: /home/lv-beast/miniconda3/condabin/conda env update -p /home/lv-beast/.trains/venvs-builds/3.5 --file /tmp/conda_env3f_gadfk.yml --quiet --json

2020-10-26T01:25:51.261Z lv-beast:gpu0,1 DEBUG Pass
Conda: Installing requirements: step 2 - using pip:
['Keras==2.3.1', 'SimpleITK==0.10.0', 'cached_property==1.3.0', 'chardet==3.0.4', 'colorama==0.4.3', 'colorlog==4.2.1', 'dask==2.6.0', 'elasticdeform==0.4.6', 'h5py==2.10.0', 'jsonpickle==1.4.1', 'log_utils==0.3.4', 'numpy==1.18.1', 'protobuf==3.13.0', 'psutil==5.7.2', 'pyclipper==1.0.6', 'git+https://github.com/BodyVisionMedical/pyserialization.git@ef992361a3a257cbd077c0306e0ad51342cc56ad#egg=pyserialization', 'requests==2.24.0', 'scikit_image==0.15.0', 'tensorboard==1.14.0', 'tensorflow_gpu==1.14.0', 'testfixtures==4.13.3', 'trains==0.16.3rc0', 'urllib3==1.25.10', 'vtk==8.1.1', 'scikit_learn~=0.20.0', 'google_api_python_client~=1.7.12', 'pytorch~=1.2.0', 'torchvision~=0.4.0']
bash: /home/lv-beast/miniconda3/envs/keras-dl/lib/libtinfo.so.5: no version information available (required by bash)
Collecting numpy==1.18.1
  Using cached numpy-1.18.1-cp35-cp35m-manylinux1_x86_64.whl (19.9 MB)

2020-10-26T01:25:56.285Z lv-beast:gpu0,1 DEBUG ERROR: imgaug 0.2.9 requires opencv-python, which is not installed.
ERROR: scikit-image 0.12.3 requires dask[array]>=0.5.0, which is not installed.
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.11.3
    Uninstalling numpy-1.11.3:
      Successfully uninstalled numpy-1.11.3
Successfully installed numpy-1.18.1
Package(s) not found: torchvision
Warning! Could not locate PyTorch version torchvision~=0.4.0 matching CUDA version 102, trying CUDA version 101
Warning! Could not locate PyTorch version torchvision~=0.4.0 matching CUDA version 101, trying CUDA version 100
bash: /home/lv-beast/miniconda3/envs/keras-dl/lib/libtinfo.so.5: no version information available (required by bash)
ERROR: torchvision-0.4.0-cp37-cp37m-manylinux1_x86_64.whl is not a supported wheel on this platform.

2020-10-26T01:26:01.313Z lv-beast:gpu0,1 DEBUG Command 'source /home/lv-beast/miniconda3/etc/profile.d/conda.sh && conda activate /home/lv-beast/.trains/venvs-builds/3.5 && pip install -r /tmp/cached-reqsrvqnm_7i.txt' returned non-zero exit status 1.

trains_agent: ERROR: Could not install task requirements!
Command 'source /home/lv-beast/miniconda3/etc/profile.d/conda.sh && conda activate /home/lv-beast/.trains/venvs-builds/3.5 && pip install -r /tmp/cached-reqsrvqnm_7i.txt' returned non-zero exit status 1.

**Comment by bmartinn** [comment]
Hi @tomeramit 
As you noticed, you can set the 'cuda_version' in the `trains.conf`, if it is not set, in run-time `trains-agent` will try to automatically detect it.

It seems what you are after is a feature allowing you to control the 'cuda' version per experiment (assuming from the UI), is that correct?
Of course, this makes sense only if you are using `conda` as package manager, (as opposed to using dockers in docker-mode), as only `conda` can actually install the correct cuda packages.
Am I missing anything ?

What I have in mind is utilizing the "base docker image" section to pass parameters to conda, as I'm assuming a mix of conda and dockers and cuda control is not realistic.

WDYT?

**Comment by tomeramit** [comment]
In one line I have one experiment with cudatoolkit 10.0 and one with cudatoolkit10.1, and I want the conda to detect each one of them and install each one of them (in it's experiment, like a package)

I tried to remove those fields from the train conf of the remote machine

![image](https://user-images.githubusercontent.com/25516152/97258648-85a36f00-1821-11eb-92b6-1d606f4d0edf.png)

(so I dont have them at all) 
but it seems that they have default value or something (which is cuda_version 102) t madhate the environment install cudatoolkit102 (that I dont want)

this is the list of the installed package inside trains
![image](https://user-images.githubusercontent.com/25516152/97258253-b931c980-1820-11eb-9ec6-c3f1241d91b2.png)

I want to remove the default install of the cuda 102 (so every experiment will install his own cudatoolkit package)

**Comment by tomeramit** [comment]
regarding to what you wrote, it seems that if I dont set the cuda toolkit, the experiment does not detect automatically the cuda toolkit version (which is for example cudatoolkit 10.0 in this specific run), it try to use cudatoolkit 102 (even though I removed it from trains.config, and I dont have cuda102 on my comp at all)

**Comment by bmartinn** [comment]
@tomeramit my thinking is to add an option to specify the cuda version in the "Base docker image" section (See Execution tab, at the bottom "Base Docker Image")
This will allow the user to control the desired cuda version, and based on that the `trains-agent` will install  the correct cuda-toolkit.
Basically I suggest a new feature that if you set your `trains-agent` to use `conda` as package manager, you could pass
`CUDA_VERSION=10.1` in the "Base Docker Image" and that will set the CUDA_VERSION for that specific experiment (obviously taking care of the correct cuda-toolkit, and a few other stuff), 
What do you think?

**Comment by tomeramit** [comment]
@bmartinn 
I think it's good idea (I think it's better to add a different field for that like you have base_docker_image you can have base_cuda_version or something)

Adding my installed packages (no sign for cuda_toolkit):
installed packages
# Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 01:53:57) [MSC v.1916 64 bit (AMD64)]

Pillow == 7.2.0
SimpleITK == 2.0.0
certifi == 2020.6.20
chardet == 3.0.4
colorama == 0.4.3
colorlog == 4.4.0
cryptography == 3.1.1
dask == 2.30.0
h5py == 2.10.0
imgaug == 0.4.0
joblib == 0.17.0
jsonpickle == 1.4.1
log_utils == 0.3.4
matplotlib == 3.3.2
numba == 0.51.2
numpy == 1.16.5
pandas == 1.1.3
pip == 20.2.3
plotly == 4.11.0
protobuf == 3.13.0
psutil == 5.7.2
pyclipper == 1.1.0.post1
pyserialization @ git+https://github.com/BodyVisionMedical/pyserialization.git@ef992361a3a257cbd077c0306e0ad51342cc56ad#egg=pyserialization
requests == 2.24.0
scikit_image == 0.17.2
scikit_learn == 0.23.2
scipy == 1.5.2
tensorboard == 2.3.0
torch == 1.6.0
torchvision == 0.7.0
tqdm == 4.50.2
trains @ git+https://github.com/allegroai/trains.git@04b3fa809bb73d7101d1995327684ebe5b2911e3#egg=trains
urllib3 == 1.25.10
vtk == 8.1.2

**Comment by jkhenning** [comment]
Closing this as `agent.cuda_version` option was added to the agent configuration file
