### ISSUE TITLE
[Feature Request] A simple manual `Task` API

### ISSUE THREAD

**Issue by erezinman** [allegroai/clearml#230]
Following [this](https://allegroai-trains.slack.com/archives/CTK20V944/p1603799008469600) discussion in Slack, I recommend having a simple API for creating a task manually. 

I suggest the API to take a similar form to W&B's (specifically [[1]](https://allegroai-trains.slack.com/archives/CTK20V944/p1603799008469600) and [[2]](https://docs.wandb.com/sweeps) in general), that allows one to specify the "entry point" for the `Task` manually. The form we talked about in the Slack discussion was similar to:
```python
Task.create("task_name", entry_point=entry_point_for_task, arg1, arg2, arg3=arg3, globals=(...))
```
Details and thoughts on implementation are in that thread. Another option to consider (hopefully allow for both) is 
```python
Task.create("task_name", script_file=filepath_or_module)
```

Cheers.

**Comment by bmartinn** [comment]
Thanks @erezinman .
I think the seconds option should be quite easy to implement. 
Regrading the first one (i.e. specifying an entry point), the main thing is wrapping the entry point, which will need support from the `trains-agent`.
Another thought, we could actually solve both by treating the "Task.create" as remote fork.
Basically replicating the entire environment / code, but when executed by the `trains-agent`, the same execution path happens, but on the `Task.create` call, it is switched to the actual entry_point, and that becomes the execution path.

For example:
```python
def mock_entry_point():
    print('forked entry_point doing other stuff')

task = Task.init('example', 'forking')
Task.fork(task_name="forked name", entry_point=mock_entry_point)
print('doing some stuff')
```

When running locally we get :
```
doing some stuff
```
Then a second experiment is create and when executed by the `trains-agent` we get:
```
forked entry_point doing other stuff
```

What do you think?

**Comment by bmartinn** [comment]
Hi @erezinman 
We added a new API for creating a Task from code with any arbitrary function:
```python
from .sub.module import my_train_func

forked_task_function = task.create_function_task(my_train_func, complex_object=MockComplex(), basict_int=43, basic_text='text')
```
This will create a new Task in the system, this Task when executed by `trains-agent` will have the same entry-point as the creating code-base, but once the `create_function_task` is called, it will actually call the `my_train_func` with the desired arguments.

This design enables:
- Support for any complex object passing without worrying about pickling / storage
- Allow for any module/sub-module calling without worrying about namespaces module paths etc
- Enable simple argument overriding in the UI (in this example `basict_int` and `basic_text`)
- Support multiple function-task creation by the same code (for example, generating a pipeline form a set of functions)

What do you think?

**Comment by erezinman** [comment]
Great! Looks very promising!

**Comment by odedbd** [comment]
@bmartinn create_function_task has a clear mechanism for passing params to the new task. 

For Task.create (specifying script to run) it seems I'll need something similar to what you guys implemented in clearml-task, i.e. the [update_task_args](https://github.com/allegroai/clearml/blob/64042f6c4fdaaf15b6c5f816f2fbf50f89c313e2/clearml/backend_interface/task/populate.py#L297).

I looked into Task.create method, and it looks like it actually imports the CreateAndPopulate class and just returns the created task, but it is missing the args kwarg, which would have allowed setting arguments overrides via Task.create. Do you plan on adding that option?

Also, is the virtualenv (packages) inherited from the creating task if no packages kwarg is given?

**Comment by bmartinn** [comment]
Hi @odedbd 

Good point, I'll make sure we add it as extra argument to `Task.create` in the next version.

BTW: You can always use Task.set_parameters to set those parameters, just like the `clearml-task` does, that said no reason not to have it on the top level interface :)

> Also, is the virtualenv (packages) inherited from the creating task if no packages kwarg is given?

Yes, actually everything is inherited from the creating task (basically instead of creating an empty Task, it clones the base task and overwrites the fields).

**Comment by jkhenning** [comment]
Hi @odedbd , just updating this was already released in ClearML/Trains v0.16.4 🙂

**Comment by odedbd** [comment]
@jkhenning thanks for the update. I'll check it out

**Comment by jkhenning** [comment]
Hi @odedbd ,

I'm closing this issue. Please reopen if needed.
