### ISSUE TITLE
Add possibility to install dependencies from `setup.py`

### ISSUE THREAD

**Issue by iirekm** [allegroai/clearml#241]
Locally everything is ok, when I run code on agents eg with `task.execute_remotely(queue_name="default")`, I get "module not found" errors.

There's `Task.add_requirement` but it seems not working, and even if it did, I would have to copy&paste my setup.py to `add_requirement` calls.

My current workaround is `import`ing the following file at top of my experiment `.py` files:

```python
import subprocess
import sys
from os import getenv
from pathlib import Path

if getenv("TRAINS_WORKER_ID") is not None:
    subprocess.run([sys.executable, "-m", "pip", "install", "-e", "."], cwd=Path(__file__).parent.parent.parent)
```

**Comment by bmartinn** [comment]
Hi @iirekm 
I think this could actually be solved by the suggestion here #236 .
If we were to have "bash init script" section on the Task, you could actually specify that, correct ?
My only thinking is, do we want the bash script before or after the install requirements section, WDYT?

p.s.
Nice hack! a suggested improvement below :)
```python
import subprocess
from trains import Task

if not Task.running_locally():
    subprocess.run(...)
```

**Comment by iirekm** [comment]
yes, bash init script would also solve this, this is a matter of taste what's better, the init script, or what I done here

**Comment by mhashas** [comment]
@bmartinn bumping this as we would be interested also :)

**Comment by bmartinn** [comment]
Good news @mhashas , @iirekm 
Docker bash script on a Task level is planned for the next release of `clearml-server` :)

**Comment by mhashas** [comment]
Thanks @bmartinn. I also figured out a hack: set the working directory to '.' and add '-e .' to the execution requirements which will run the setup.py

**Comment by jkhenning** [comment]
Hi @iirekm, @mhashas,

The docker bash script support has now been in ClearML for a long time, so I'm closing this. Please reopen if needed.
