### ISSUE TITLE
How should I save and load models?

### ISSUE THREAD

**Issue by iirekm** [allegroai/clearml#249]
`task.upload_artifact` works with DataFrames (not perfectly, but I can download something with `get()` method)

how can I upload and download XGBRegressor models? 

- with `task.upload_artifact(my_xgbregressor)` - and then `artifacts["name"].get()` instead of model, I get path to some file, but I don't know how to use it (unpickling doesn't work, ` joblib.load(task.artifacts["model"].get())` neither)

- Trains publishes something automatically under "Output model", but I can't use it - download link is dead, with api and `task.models["output"][0]` I get strange `Model` object with no useful methods in it

How can I upload and download models? In SageMaker it dead simple (just push to appropriate directory and just use S3 location), with Trains I have trouble.

**Comment by bmartinn** [comment]
Hi @iirekm 

Below you can see an example of using an artifact.
Assuming we had a Task uploaded an artifact (a local file) by the name "model", then later we can get a copy of that file by calling 
`get_local_copy()`

```python
from trains import Task
task = Task.get_task(task_id='previously_executed_task')
my_local_copy_of_the_previously_uploaded_artifact = task.artifacts["model"].get_local_copy()
```

Specifically if the type of the artifact was known, then if we call `get()` we should get the same object as the original artifact.
Supported types are Numpy/DataFrame/PIL.Image etc. (see [documentation](https://allegro.ai/docs/task.html#trains.task.Task.upload_artifact))

If upload artifact is called with any other object and with `auto_pickle=True` , it will pickle the object and store/upload the pickled file. Then when `get()` is called it will try to unpickle the object. Unfortunately pickle is not the most stable serialization method, and sometimes the de-pickling will fail, in that case we return a string pointing to the original artifact as it was stored.

Make sense ?

**Comment by Netzeband** [comment]
Hello @bmartinn 

I have a question: Why are models handled so differently to artifacts? For example, artifacts are directly uploaded to the ClearML Server, for models you need an S3 bucket? Why isn't there an option to also upload them to the ClearML Server? Is there an option to upload artifacts to S3 instead of ClearML?

**Comment by Ammar-Azman** [comment]
`from train import Task` or `from clearml import Task` ?

**Comment by ainoam** [comment]
@Ammar-Azman For quite a while now `trains` has been renamed `clearml` 🙂.
`from clearml import Task` is the way to go.
