### ISSUE TITLE
Max size of image to uplaod

### ISSUE THREAD

**Issue by assafzam** [allegroai/clearml#257]
Hi,  I'm trying to upload an Image by the `report_image` method. 
The image is numpy array with shape (4000,3000,3) , and I got this message:
```
2020-11-25 15:32:20,383 - trains.metrics - WARNING - Failed uploading to https://files..... (Failed uploading object files.trains- ...Example Images_Train Image_00000000.jpeg (413): <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.17.8</center>
</body>
</html>
)
2020-11-25 15:32:20,384 - trains.metrics - ERROR - Not uploading 1/1 events because the data upload failed
TRAINS Monitor: Reporting detected, reverting back to iteration based reporting
```
I want to resize the image dynamically to max size, so I searched for max size of Image in documentation, but could not find it.
What is the max size?

**Comment by jkhenning** [comment]
Hi @assafzam,

This is an nginx limitation. The default payload limit for nginx is 1M.
By the way - what are the `api_server`, `web_server` and `files_server` values configured in yout `trains.conf` file?

**Comment by assafzam** [comment]
Thanks for the answer, 
We are Using our own trains server with version 0.16.1-320

**Comment by jkhenning** [comment]
That's what I assumed, but I'd like to see the exact URL format of the value in the `files_server` (and others) in your config file - I think it might help understand why the call is redirected though nginx. Can you share it? You can of course hide or replace the actual IP address or domain name 🙂

**Comment by assafzam** [comment]
🙂

files_server:  https: //files.trains-stage.gerren-eye.ca

**Comment by jkhenning** [comment]
Assuming this gets redirected to the Trains File Server (which is Flask based and doesn't pass through nginx in Trains Server's internal setup), I can only assume you have an nginx set up somewhere along the way (load balancer?).

Assuming you locate the nginx that's blocking these requests, you'll need to set up the `client_max_body_size` setting to allow larger uploads. See https://www.tecmint.com/limit-file-upload-size-in-nginx/ and http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size .

**Comment by Shaked** [comment]
As trains is behind nginx-ingress, `nginx.ingress.kubernetes.io/proxy-body-size: "0"` did the job. 

["0" disables the limit](https://stackoverflow.com/questions/55347770/nginx-ingress-kubernetes-io-proxy-body-size-not-working)
