### ISSUE TITLE
During hyperparameter search, make it possible to have the spawned children in a different project

### ISSUE THREAD

**Issue by mhashas** [allegroai/clearml#263]
Hi,

First of all, sorry for spamming you with so many issues / requests. When doing hyper-parameter search, the spawned children of the HPO are in the same project as the HPO parent. What would be really useful for me is to be able to specify the project in which the children are spawned, so that I can keep the parents and the children separated. Right now, because of the many children, I have to manually archive them in order to just view the hyper-parameter searches and be able to compare them. This gets tiring fast. 

The solution could be implemented through a parameter to the HPO object, i.e. children_project_name='', and if left empty it's the same project as the parent. 

Thanks :)

**Comment by bmartinn** [comment]
Hi @mhashas 

> First of all, sorry for spamming you with so many issues / requests.

No worries, we love ideas & suggestions :)

>  What would be really useful for me is to be able to specify the project in which the children are spawned, so that I can keep the parents and the children separated.

That is a very good point, we were discussing this issue internally, and would love to get users thoughts.
I'll start at the end, great idea, it will be very easy to add:
The [helper_create_job()](https://github.com/allegroai/trains/blob/282513ac33096197f82e8f5ed654948d97584c35/trains/automation/optimization.py#L486) function actually creates all the HPO jobs (regardless of the optimization algorithm) so we can just add an argument for the base [SearchStrategy](https://github.com/allegroai/trains/blob/282513ac33096197f82e8f5ed654948d97584c35/trains/automation/optimization.py#L226) object, and make sure it uses it.

Back to the point on the clutter the HPO generates, maybe we should only save the top X performing experiments and automatically archive the rest? Considering we have the detailed table view on the HPO  results->plots we might not actually need them, (maybe other than to compare and generate huge parallel coordinates table, but we can always get them back from the archive), WDYT?

**Comment by mhashas** [comment]
Hi @bmartinn,

The only downside that I see to your suggestion is if you do want to check a not optimal configuration, after fetching the ID you have to figure out if it's in the project or in the archive of the project. 

Personally, I will always check the parent, fetch the ID and then run a search to retrieve my experiment. As such, having the experiments in a different project (sort of a sacrificed project) would be better for me. Furthermore, since you search on ID, even if the project grows to millions of experiments, searching should still be fast. 

Anyway, I think both ideas are better than the current situation so I'm fine with either. Maybe they can both be implemented? A parameter to specify the project in which the children should be saved (default: same project) and a parameter to specify how many experiments to archive (i.e. archive_non_top_k (default: None) = 30, which would archive experiments not in top 30.

**Comment by bmartinn** [comment]
> ... to figure out if it's in the project or in the archive of the project.

This is just a system flag on the Task :)

> Maybe they can both be implemented?

Yes, let's do that!
I'm waiting for the project renaming (new name `clearml`) to kick-in and then I'll make sure we add it.

**Comment by mhashas** [comment]
hi @bmartinn,

Could you share an ETA regarding this? Thanks :)

**Comment by bmartinn** [comment]
Hi @mhashas 
Great timing, it will be part of the next version, due to be released in a few days :)

**Comment by bmartinn** [comment]
Hi @mhashas clearml v0.17.4 is out with this new feature :)
See example [here](https://github.com/allegroai/clearml/blob/34c41cfc8c3419e06cd4ac954e4b23034667c4d9/examples/optimization/hyper-parameter-optimization/hyper_parameter_optimizer.py#L90)
``` bash
pip install clearml==0.17.4
```

**Comment by mhashas** [comment]
Thanks, greatly appreciated :)
