### ISSUE TITLE
Broken link to tutorial in README

### ISSUE THREAD

**Issue by seungjaeryanlee** [allegroai/clearml#269]
The link in "Start using" is broken: perhaps it should go to [https://allegro.ai/clearml/docs/rst/getting_started/index.html](https://allegro.ai/clearml/docs/rst/getting_started/index.html) instead?

https://github.com/allegroai/clearml/blob/1484a7005ea16c5c768475b920d0eb6e5ebf687a/README.md#L32-L36

**Comment by bmartinn** [comment]
Thank you for noticing so quickly @seungjaeryanlee !
We just updated the doc site, it broke a few of the link...
Fixed now :)

**Comment by seungjaeryanlee** [comment]
Fixed in my end as well! Thank you for the quick fix. Closing the issue.
