### ISSUE TITLE
Pipeline Configuration Error

### ISSUE THREAD

**Issue by umbertopietroni** [allegroai/clearml#282]
Hi, I'm having problem reproducing the example at https://allegro.ai/clearml/docs/docs/examples/pipeline/pipeline_controller.html.

In particular, when I run the pipeline_controller.py I get this error 
```

Traceback (most recent call last):
  File "src/pipeline_controller.py", line 43, in <module>
    pipe.start()

  File "lib/python3.8/site-packages/clearml/automation/controller.py", line 193, in start
    self._task.connect_configuration(pipeline_dag, name=self._config_section)

  File /lib/python3.8/site-packages/clearml/task.py", line 1096, in connect_configuration
    raise ValueError("Multiple configurations is not supported with the current 'clearml-server'

ValueError: Multiple configurations is not supported with the current 'clearml-server', please upgrade to the latest version
```

I have the same error both on the demo ClearML server and also on my own ClearML server running on localhost. My version of clearml  is  0.17.3

Thank you

**Comment by bmartinn** [comment]
Hi @umbertopietroni 

Yes :( 0.17.3 had some issues with PyJWT v2.0.0, see if upgrading to 0.17.4 solves the issue.

(Basically what happened is it failed correctly parsing the server API version, and it defaulted to a very old version that did not support multiple configurations)
