### ISSUE TITLE
Getting highscore from leaderboard

### ISSUE THREAD

**Issue by dmus** [allegroai/clearml#283]
Hi, this looks like a great project.

My question: when an user does a new experiment that results in a new highscore within that project for some metric I want to send a slack notification. Is this possible? and if yes, how?

**Comment by bmartinn** [comment]
Thank you @dmus ❤️ 
Love the idea!
I would change the [Slack moinotring](https://github.com/allegroai/clearml/blob/master/examples/services/monitoring/slack_alerts.py) 
Basically we should change this [line](https://github.com/allegroai/clearml/blob/34c41cfc8c3419e06cd4ac954e4b23034667c4d9/examples/services/monitoring/slack_alerts.py#L113) to:
``` python
import hashlib
title = hashlib.md5('epoch_accuracy'.encode('utf-8')).hexdigest()
series = hashlib.md5('epoch_accuracy'.encode('utf-8')).hexdigest()
return dict(order_by=['last_metrics.{}.{}'.format(title, series)], )
```
*If you need to reverse the order then just add minus: `'-last_metrics.{}.{}'.format(title, series)`

This will get you the best performing experiments in a project, then we can detect if the `Task.id` changed between one query to another.

What do you think?

**Comment by dmus** [comment]
yes, this seems a good suggestion

**Comment by dmus** [comment]
And how if there should be a slack message if there is a highscore within any project? Do you have a suggestion?

Keeping track of the highscores within each project I think? Is there a way to get all the projects?

**Comment by bmartinn** [comment]
@dmus you mean like top score from all projects (say running a hackathon , with project per group, then alerting a group broke the record) ?
See this [argument](https://github.com/allegroai/clearml/blob/34c41cfc8c3419e06cd4ac954e4b23034667c4d9/examples/services/monitoring/slack_alerts.py#L154) by default it will monitor all projects, so the tasks returned by the query will not be limited to a single project. 
You can think of it as a DB query, the project is just another field to match for the query, then we sort it based on the metric.
Is this what you are looking for ?
