### ISSUE TITLE
Error: could not verify credentials

### ISSUE THREAD

**Issue by vinh-cao** [allegroai/clearml#284]
Hi,

i setup a local ClearML server following the guide for linux.
I didn't change anything from default configuration. ClearML Host is not set or set to 0.0.0.0, no Git_USER and no GIT_PASS.
I verified, all ClearML containers are up and running.

On the same machine, I tried to call `clearml-init`  and paste the credential created from the UI. But I always get the error:

> Paste copied configuration here:
api {
    web_server: http://carmbew25647.blablaland.local:8080
    api_server: http://carmbew25647.blablaland.local:8008
    files_server: http://carmbew25647.blablaland.local:8081
    credentials {
        "access_key" = "JTX1VOM02E3R248HNJF0"
        "secret_key" = "R#7z6e88r5vTCEsFVhlWqv5T@l%R8BitDqa1m)mkeXS+8SRF^N"
    }
}

> Detected credentials key="JTX1VOM02E3R248HNJF0" secret="R#7z***"
> WEB Host configured to: [http://carmbew25647.blablaland.local:8080]
> API Host configured to: [http://carmbew25647.blablaland.local:8008]
> File Store Host configured to: [http://carmbew25647.blablaland.local:8081]
> 
> ClearML Hosts configuration:
> Web App: http://carmbew25647.blablaland.local:8080
> API: http://carmbew25647.blablaland.local:8008
> File Store: http://carmbew25647.blablaland.local:8081
> 
> Verifying credentials ...
> Error: could not verify credentials: key=JTX1VOM02E3R248HNJF0 secret=R#7z6e88r5vTCEsFVhlWqv5T@l%R8BitDqa1m)mkeXS+8SRF^N
> Enter user access key:
> Enter user secret:

can you guide me to fix the problem? Thanks in advance!
Vince

I added this to the `apiserver.conf`:

```
auth {
        # Fixed users login credentials
        # No other user will be able to login
        fixed_users {
                enabled: true
                users: [
                        {
                                username: "vi"
                                password: "blablabland"
                                name: "Vince"
                        }
                ]
        }
}
tasks {
    non_responsive_tasks_watchdog {
        # In-progress tasks that haven't been updated for at least 'value' seconds will be stopped by the watchdog
        threshold_sec: 7200

        # Watchdog will sleep for this number of seconds after each cycle
        watch_interval_sec: 900
    }
}
```

**Comment by bmartinn** [comment]
Hi @vinh-cao 
Which clearml version are you using?
We had some issues with PyJWT v2.0.0 that were fixed with `clearml` 0.17.4
Could you try with:
``` bash
pip install clearml==0.17.4
```
And if the error persists then maybe 
``` bash
pip install -U "pyjwt<2"
```

🤞

**Comment by vinh-cao** [comment]
Unfortunately, the error still remain:

> Detected credentials key="D1ILPN0XUU5QKGR7JFDD" secret="%Mr5***"
WEB Host configured to: [http://carmbew25647.blablaland.local:8080]
API Host configured to: [http://carmbew25647.blablaland.local:8008]
File Store Host configured to: [http://carmbew25647.blablaland.local:8081]

> ClearML Hosts configuration:
> Web App: http://carmbew25647.blablaland.local:8080
> API: http://carmbew25647.blablaland.local:8008
> File Store: http://carmbew25647.blablaland.local:8081
> 
> Verifying credentials ...
> Error: could not verify credentials: key=D1ILPN0XUU5QKGR7JFDD secret=%Mr5L=M&W5!FHRp=OzkaK5Z4Teg0028D5u(%dtS7UAffq&9sTz
>

**Comment by jkhenning** [comment]
Hi @vinh-cao ,

Can you try to reach the API server from the same machine (where you're running `clearml-init`)?

If you're on Linux, try:
`curl http://carmbew25647.blablaland.local:8008`
and
`curl http://localhost:8008`

and share the results (even if they seem like an error 🙂 )

**Comment by vinh-cao** [comment]
Thanks Jake for your help. I solved the problem after receiving unresolved DNS hostname with curl. I have set http_proxy and https_proxy, but the link is the local device name. Unsetting the proxies solved the problem.

**Comment by sriram-dsl** [comment]
![image](https://github.com/allegroai/clearml/assets/137028273/ebee5666-0aad-4e97-b029-8a30abf9e91a)

can you resolve this
```

(clearml) suravera@LAPTOP-FGKIL16M:/mnt/c/srtyu/work$ clearml-init
ClearML SDK setup process

Please create new clearml credentials through the settings page in your `clearml-server` web app (e.g. http://localhost:8080//settings/workspace-configuration)
Or create a free account at https://app.clear.ml/settings/workspace-configuration

In settings page, press "Create new credentials", then press "Copy to clipboard".

Paste copied configuration here:
api { 
    web_server: http://<server_ip>:8080
    api_server: http://<server_ip>:8008
    files_server: http://<server_ip>:8081
    credentials {
        "access_key" = "NIN***"
        "secret_key"  = "uN1***"
    }
}
Detected credentials key="NIN***" secret="uN1c***"
Port 8080 is the web port. Replacing 8080 with 8008 for API server

ClearML Hosts configuration:
Web App: http://<server_ip>:8080
API: http://<server_ip>:8008
File Store: http://<server_ip>:8081

Verifying credentials ...
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fe0fe943d90>, 'Connection to <server_ip> timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fe0fe9433d0>, 'Connection to <server_ip> timed out. (connect timeout=3.0)')': /auth.login
Error: could not verify credentials: key=NIN***
 secret=uN***
Enter user access key: NIN***
Enter user secret: uN1***
Verifying credentials ...
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fe0fe943190>, 'Connection to <server_ip> timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fe0feaccb50>, 'Connection to <server_ip> timed out. (connect timeout=3.0)')': /auth.login
Error: could not verify credentials: key=NIN***
secret=uN1***
Exiting setup without creating configuration file
(clearml) suravera@LAPTOP-FKIL416M:/mnt/c/srtyu/work$
```

i have launched the clearml server in a system with ip : <server_ip> 
trying to connect to it, from another machine
server is up
