### ISSUE TITLE
Feature request: abort multiple tasks on UI

### ISSUE THREAD

**Issue by Mano3** [allegroai/clearml#286]
Hi, we encounter that issue at least 10 times per day, hahaha.
We wish to select multiple tasks and abort/enqueue/dequeue/reset them and it's currently not possible and we have to do so for every single task.
Our pipeline puts up many tasks in parallel so upon bug (on our side) we need to abort said tasks, and that's a really exhausting thing to do every time.

Thanks!!

**Comment by bmartinn** [comment]
Hi @Mano3 
With `clearml-server` 0.17.0 , when archiving multiple Tasks, if they are pending, it will automatically dequeue them.
Maybe we should make sure that if they are running they are also aborted?

WDYT?

**Comment by Mano3** [comment]
That's good but not enough. I don't want to archive them, I simply want to abort/reset/dequeue/enqueue them and that's not possible with multiple tasks now. :)

**Comment by bmartinn** [comment]
Good news @Mano3 the next `cleaml-server` version should include a few other multi-task actions (such as enqueue / dequeue / reset etc.)

**Comment by Mano3** [comment]
@bmartinn abort too? Haha

**Comment by jkhenning** [comment]
Closing this as it was already released. Please reopen if required.
