### ISSUE TITLE
HPO picking up uncommited local changes

### ISSUE THREAD

**Issue by mhashas** [allegroai/clearml#290]
Hi,

I will try to describe my issue as clear as possible.

On friday I started an HPO. The base task runs on latest in branch develop. Everything is running smooth
Now it's monday, I start working on a new ticket, so I create a new branch based on develop. The HPO is still running in the background. I start implementing the ticket and in a break I take a look at the HPO, where I have a surprise:

The new tasks spawned by the HPO are breaking. If I look at the child at the commit id and the branch, it's the last commit from develop. However the error that it's showing is along:

file xxxx.py line 53: 
if
^
SyntaxError: invalid syntax

This is the exact spot I was currently coding at and there's a not-finished if statement. 

Is this normal behaviour? Is there anyway to circumvent this? My HPO is based on the HPO example with optuna

**Comment by bmartinn** [comment]
Hi @mhashas 
I'll start et the end.
> Is this normal behavior? Is there anyway to circumvent this? My HPO is based on the HPO example with optuna

No, it is not :)

Could you describe the setup itself?
The thing is, all HPO tasks are replicas of the "base task", these tasks are replicated into a new clean venv on the `clearml-agent` machine or inside a docker on the same machine. In both cases your development code has nothing to do with it.

That said, could it be you have some sort of shared folder between the machines, or that accidentally you edited code on the agent's machine inside the temp venv environment (by default it is all under `~/.clearml` or `~/.trains`)?

**Comment by mhashas** [comment]
@bmartinn 

You are right, it is because of a shared folder, thanks!
