### ISSUE TITLE
duplicate models when using pytorch lightning with ddp accelerator

### ISSUE THREAD

**Issue by tankeco** [allegroai/clearml#292]
When using pytorch lightning with ddp accelerator on 4 gpus, I find every checkpoint is recorded 4 times on web UI with different ids. One is on `default_output_uri` (s3://...) and three are on `file:///...` .

![4](https://user-images.githubusercontent.com/1119389/105330789-a9eace00-5c0d-11eb-9039-4776e295125f.png)

Note pytorch lightning automatically ensures that the model is saved only on the main process: https://pytorch-lightning.readthedocs.io/en/stable/weights_loading.html#manual-saving-with-accelerators

**Comment by bmartinn** [comment]
Hi @tankeco 
Could you maybe test the fix? it's already part of the latest RC
```
pip install clearml==0.17.5rc2 
```

**Comment by tankeco** [comment]
it fixed :)

**Comment by bmartinn** [comment]
Great news @tankeco :) closing this issue.
