### ISSUE TITLE
remote diff should not be stripped

### ISSUE THREAD

**Issue by tankeco** [allegroai/clearml#294]
remote diff is stripped here:
https://github.com/allegroai/clearml/blob/master/clearml/backend_interface/task/repo/detectors.py#L142

This causes the `git apply` sometimes fail. 

In contrast, the processing is correct when it is not remote diff:
https://github.com/allegroai/clearml/blob/master/clearml/backend_interface/task/repo/detectors.py#L126

**Comment by bmartinn** [comment]
Hi @tankeco 
No need to be shy, if you find a bug feel free to just PR a fix :)

Regrading the specific issue, in both cases the results from git commands are stripped only if they are Not `diff` (in the remote case it includes `diff_remote` and `diff_remote_fallback`), see Commands [here](https://github.com/allegroai/clearml/blob/715a0d7edc33b6ff91affe525194fa0c525d98f3/clearml/backend_interface/task/repo/detectors.py#L57)
Is there a specific scenario it fails?

**Comment by bmartinn** [comment]
Closing after the fix was meged
