### ISSUE TITLE
0.17.5 RCs do not detect scikit-learn dependency

### ISSUE THREAD

**Issue by odedbd** [allegroai/clearml#296]
I've been testing 0.17.5rc0-0.17.5rc2 and scikit-learn dependency isn't being detected. As a result my scripts, which used to run fine on remote, fail on import sklearn. I verified that indeed scikit-learn is not listed in the dependencies for the task. Reverting to 0.17.4 resolved this issues.

**Comment by bmartinn** [comment]
Thanks @odedbd 
I was able to locate the issue, a fix will be ready soon, I'll update here.
BTW: This will only affect `scikit-learn`, since the import is different from the package naming :)

**Comment by odedbd** [comment]
@bmartinn that's great. Is there an option to manually register dependencies, in a addition to the automagical discovery? Some API like task.add_dependency('package_name',version=None) where version is optional if you want to just grab the latest? With such an API I could fix such a problem on my end, at least until it would be solved "properly".

**Comment by jkhenning** [comment]
Hi @odedbd ,

> Is there an option to manually register dependencies, in a addition to the automagical discovery? Some API like task.add_dependency('package_name',version=None) where version is optional if you want to just grab the latest?

Yes indeed, you can use:
`task.add_requirements(package_name, package_version=None)`

🙂

**Comment by odedbd** [comment]
That's good to know 👍

**Comment by bmartinn** [comment]
@odedbd 
Updating here the latest RC fixes this issue, please feel free to test:
```
pip install clearml==0.17.5rc3
```

**Comment by odedbd** [comment]
Working, thanks!

**Comment by graelo** [comment]
Hi,

For future readers, the api for manually registering dependencies is currently a class method (note the `Task`, not `task`)

```python
Task.add_requirements("requests", "2.29.0")
```

and this statement must be placed _before_ `Task.init(...)`
