### ISSUE TITLE
Problem with an argparse argument with default [None]

### ISSUE THREAD

**Issue by odedbd** [allegroai/clearml#297]
I have a script with an argparser argument defined as follows-

parser.add_argument('--max_depth', type=int, nargs='+', default=[None], )

The expected input is a sequence of integers to be interpreted as a list of ints, with the default being a list with a single None item.

This works fine locally, but fails remotely - the value in the remotely executed script is ['None'] (a string) instead of [None]. The configuration tab on the web UI lists [None] for this argument (no string quotations). 

I verified the value when executed remotely by logging the args Namespace object at the start of my script.

**Comment by bmartinn** [comment]
Thanks @odedbd ,
I was able to reproduce the issue, and I will update here once the fix is released (should not take long).

**Comment by bmartinn** [comment]
Hi @odedbd 
The latest RC should contain the fix, please feel free to test :)
```
pip install clearml==0.17.5rc3
```

**Comment by odedbd** [comment]
@bmartinn 
I tested with 0.17.5rc3, nut now it looks as if ALL properties are registered at their default values, ignoring the command line arguments altogether. 

When running locally (but reporting to the web server) I can see that the local code is using the correct arguments provided via command line, but on the task Configuration tab I see the default values for all arguments.
So, at least for me, this rc is even more broken in terms of argument parsing.

When using task.execute_remotely I see all arguments are also at their defaults and that's reflected both in the Configuration tab and in the task execution logs.

**Comment by jkhenning** [comment]
Hi @odedbd ,

Is there any change in latest versions?

**Comment by odedbd** [comment]
@jkhenning it was solved on 0.17.5rc6, thanks!
