### ISSUE TITLE
How to directly enqueue new tasks without ever running them locally?

### ISSUE THREAD

**Issue by ErenBalatkan** [allegroai/clearml#299]
From what i have seen, current methodology for enquing tasks on remote is as follows;

1. Run task locally
2. Make a copy of the initial task
3. Modify parameters of copy
4. Enqueue the copy

However, i do not ever want to run task locally, is there a method for enquing new taks directly without ever running them locally?

This is not a problem if i start tasks from the remote machine, but that kind of eliminates point of using ClearML for me as i am using it to abstract out remote machines. From my point of view, I should only setup ClearML Agent on server and never again should even be bothered with anything on server.

Currently, this mechanicsm can easily be simulated by having a boolean flag on train script. Such as
```
if not is_local:
   train();
else:
    cloned_task = clone(task)
    enqueue(copy_task)
```

and this will simply prevent running the actual code on local machine. But i was wondering if there is a more elegant solution already available? Is there way to seperate task initialization code from actual task running code?

**Comment by ainoam** [comment]
Hi @ErenBalatkan,

This is exactly what [Task.execute_remotely](https://allegro.ai/clearml/docs/rst/references/clearml_python_ref/task_module/task_task.html?highlight=execute_remotely#clearml.task.Task.execute_remotely) is for.
Its use is demonstrated in multiple places in the ClearML [examples](https://github.com/allegroai/clearml/tree/a29a655a6ea3424906392bafb8d2fab292397f3a/examples) (e.g. [training pipeline](https://github.com/allegroai/clearml/blob/a29a655a6ea3424906392bafb8d2fab292397f3a/examples/pipeline/step3_train_model.py))

Is this what you had in mind?

**Comment by ErenBalatkan** [comment]
> Hi @ErenBalatkan,
> 
> This is exactly what [Task.execute_remotely](https://allegro.ai/clearml/docs/rst/references/clearml_python_ref/task_module/task_task.html?highlight=execute_remotely#clearml.task.Task.execute_remotely) is for.
> Its use is demonstrated in multiple places in the ClearML [examples](https://github.com/allegroai/clearml/tree/a29a655a6ea3424906392bafb8d2fab292397f3a/examples) (e.g. [training pipeline](https://github.com/allegroai/clearml/blob/a29a655a6ea3424906392bafb8d2fab292397f3a/examples/pipeline/step3_train_model.py))
> 
> Is this what you had in mind?

Precisely! Thanks for the quick response.

**Comment by bmartinn** [comment]
For the sake of completeness, we introduced [clearml-task](https://github.com/allegroai/clearml/blob/master/docs/clearml-task.md) to create a Task from CLI, or programmatically with the new [Task.create](https://github.com/allegroai/clearml/blob/ebc0733357ac9ead044d0ed32d41447763f5797e/clearml/task.py#L598) interface.
