### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by jax79sg** [allegroai/clearml#300]
Link [https://allegro.ai/clearml/docs/rst/webapp/index.html](https://allegro.ai/clearml/docs/rst/webapp/index.html) references the following links. All are broken.

https://www.allegro.ai/clearml/docs/docs/webapp_exp_track_visual.html
https://www.allegro.ai/clearml/docs/docs/webapp_exp_reproducing.html
https://www.allegro.ai/clearml/docs/docs/webapp_exp_tuning.html
https://www.allegro.ai/clearml/docs/docs/webapp_exp_comparing.html
https://www.allegro.ai/clearml/docs/docs/webapp_exp_sharing.html
https://www.allegro.ai/clearml/docs/docs/webapp_archiving.html
https://www.allegro.ai/clearml/docs/docs/webapp_workers_queues.html
https://www.allegro.ai/clearml/docs/docs/webapp_profile.html

**Comment by ainoam** [comment]
@jax79sg Thanks for pointing it out.

Until the docs are fixed, notice the break is a missing 'webapp' key in the path e.g. 'https://www.allegro.ai/clearml/docs/docs/webapp_exp_track_visual.html' -> 'https://www.allegro.ai/clearml/docs/docs/**webapp**/webapp_exp_track_visual.html'

**Comment by ainoam** [comment]
@jax79sg All fixed now. Thanks again for pointing it out.
