### ISSUE TITLE
Error 11 : Missing required fields (page_size is required when page is requested): field=page_size

### ISSUE THREAD

**Issue by BrianG13** [allegroai/clearml#301]
Hi,

My project Experiments dashboard page is not working anymore, and I can't see my running experiments.
When I reach the main page I can see my experiments:
![image](https://user-images.githubusercontent.com/51123168/106452616-d4038200-6490-11eb-9d84-bbf27a15f362.png)

The following error raises when try to enter that page:
![image](https://user-images.githubusercontent.com/51123168/106451966-ea5d0e00-648f-11eb-8c67-acfc8b221859.png)

And if I press OK, I receive a blank page:
![image](https://user-images.githubusercontent.com/51123168/106452017-fe087480-648f-11eb-8e5f-195279e5563a.png)

How can I fix this issue? There is a chance that I lost all the logs & tracking for my project experiments?

Note: I checked and my server docker is still running.
Note2: No connection issues.
Note3: I managed somehow to reach an experiment page, but it shows a different error `Error 1 : Internal server error: err=Cannot resolve field "null", extra_info=None`
![image](https://user-images.githubusercontent.com/51123168/106452788-07dea780-6491-11eb-9fa6-e2aef22361ce.png)

Appreciate your help,
Thanks!

**Comment by jkhenning** [comment]
Hi @BrianG13,

This is a known UI issue that will be solved in the next release.

It's related to a bug in the ordering of experiments requested by the UI. To solve, simply choose an column to sort by (by clicking on the column title's sort control) - any sorting you select should clear up this issue and return you to a normal display.

**Comment by BrianG13** [comment]
Thank you for your fast reply!
It works! 😃
