### ISSUE TITLE
Problem with multirun in hydra

### ISSUE THREAD

**Issue by antoinebrl** [allegroai/clearml#306]
Hello :wave:!

I am facing some issues when launching my experimentations with hydra multirun `hydra -m/--multirun`.

First, I noticed the configuration (`omegaconf`) was not visible in the dashboard when multirun is used.
To reproduce:
```python
# main.py
import hydra
from clearml import Task
from omegaconf import DictConfig, OmegaConf

@hydra.main(config_name="config")
def my_app(cfg : DictConfig) -> None:
    print(OmegaConf.to_yaml(cfg))
    task = Task.init(project_name='hydra-clearml', task_name='hydra-clearml', reuse_last_task_id=False)

if __name__ == "__main__":
    my_app()
```

```
pip install hydra-core clearml
python main.py +test.test=1  # omegaconf logged
python main.py -m +test.test=1,2,3,4  # omegacong not captured
```

I wanted to force the configuration, so I added `task.connect_configuration(OmegaConf.to_container(cfg, resolve=True))`.
I later realized it would not completely resolve the issue as **all runs are stored under the same task** and therefore only keeping the latest config. This is a plot taken from the task which has 4 runs. **It is not a comparison between tasks, it's the same task with all runs!**
![Screenshot from 2021-02-08 12-11-26](https://user-images.githubusercontent.com/17803473/107222113-6f09d800-6a0c-11eb-8813-233a2cb852b7.png)

### Solution

I think the best solution (and expected behaviour) would be for `clearml` to create one task per hydra run. This solution has the benefit of enabling performance evaluation under several hyper parameters.

**Comment by bmartinn** [comment]
Hi @antoinebrl 
>  think the best solution (and expected behavior) would be for clearml to create one task per hydra run. This solution has the benefit of enabling performance evaluation under several hyper parameters.

I think you are right and this should be the correct behavior for hydra multi-run.
The only "caveat" I can see is that you will have to have the `Task.init` inside the hydra app, but I think this is reasonable. 
WDYT?

In order to validate the solution, could you verify that the following toy example will achieve the requested behavior ?

``` python
# main.py
import hydra
from clearml import Task
from omegaconf import DictConfig, OmegaConf

@hydra.main(config_name="config")
def my_app(cfg : DictConfig) -> None:
    print(OmegaConf.to_yaml(cfg))
    task = Task.init(project_name='hydra-clearml', task_name='hydra-clearml', reuse_last_task_id=False)
    print('doing some stuff')
    task.close()

if __name__ == "__main__":
    my_app()
```

**Comment by antoinebrl** [comment]
Hi @bmartinn

> The only "caveat" I can see is that you will have to have the Task.init inside the hydra app, but I think this is reasonable.
WDYT?
I don't think this is a big deal but it should be documented I would say.

Closing the task does the trick —it creates as many tasks as runs.

Unfortunately the `OmegaConf` configuration is not saved by default. I tried to force it under the same name: `task.connect_configuration(OmegaConf.to_container(cfg, resolve=True), name="OmegaConf")`. The configuration of each run is now visible in the dashboard but it is not considered as a set of hyper parameters.

![Screenshot from 2021-02-09 10-26-36](https://user-images.githubusercontent.com/17803473/107350611-8e167180-6ac1-11eb-8012-19c589a204c4.png)
![Screenshot from 2021-02-09 10-27-03](https://user-images.githubusercontent.com/17803473/107350613-8eaf0800-6ac1-11eb-885a-744b89f057ce.png)

**Comment by bmartinn** [comment]
Hi @antoinebrl 
It seems like we have a solution , and implementation wise this is fairly simple, let me check when we can push a fix.

> I don't think this is a big deal but it should be documented I would say.

I suggest we print a warning if you call `Task.init` outside of the app, saying multi-run is ill-supported, wdyt?
It will still work, only if you are using mulri-run you will end-up with a single Task, make sense ?

> Unfortunately the OmegaConf configuration is not saved with multirun. ...

This seems like a bug (regardless of the multi-run feature), can you see the OmegaConf when you manually execute the script (i.e. without multi-run)? Following on that, what are the python / hydra / clearml / OS you are using ?

**Comment by antoinebrl** [comment]
Hi @bmartinn 

> implementation wise this is fairly simple

:+1: 

I like the idea of the warning message which recommends creating and closing the task inside the app when multirun is activated.

The hydra config is captured correctly when multirun is not used. I see two problems here: the automatic capture of hydra config when multirun is on, and treating the configuration pushed with `task.connect_configuration` as hyper parameters.

**Comment by bmartinn** [comment]
> I like the idea of the warning message which recommends creating and closing the task inside the app when multirun is activated.

No need to explicitly call `close`, only the Task.init() is important (the auto-close should be handled automatically if a multi-run is used)

Regrading the `omegaconf` issue, good news, I was able to reproduce the issue with multi-run.
A fix is on its way ;) I'll update here soon

**Comment by bmartinn** [comment]
@antoinebrl could you see if the latest version from git works as expected (it should,  hopefully :) )
```
pip install git+https://github.com/allegroai/clearml.git
```

**Comment by antoinebrl** [comment]
It is looking good!
Runs are broke down into several tasks and the omegaconf generated by hydra is correctly captured.
Well done!

**Comment by bmartinn** [comment]
@antoinebrl just updating here, an RC is out including the fix for this issue :)
```
pip install clearml==0.17.5rc4 
```
