### ISSUE TITLE
Incorrect remote URL manipulation in case of Gitlab SSH remotes 

### ISSUE THREAD

**Issue by dltkhacene** [allegroai/clearml#307]
Hello!

First, I'd like to thank the allegroai team for this gem.

While working with the platform locally, I encountered the issue where the resulting manipulated remote URL is unusable because of how gitlab (and the self managed gitlabs) uses ssh authentication.

It's particularly related to https://github.com/allegroai/clearml/blob/0.17.4/clearml/backend_interface/task/repo/util.py#L23 where the user and password are removed from the remote URL (which is understandable), whereas gitlab uses links in the form `ssh://git@gitlab.com:awesome_dev/awesome_repo.git` where the general user is git and it won't work if the user is not present.

I suggest that a check should be made if there is only a user a no password, no URL manipulation should be done. Or maybe check if the user is _git_ the URL is returned as it is.

Any feedback on this issue is welcome!

clearml version: 0.17.4

**Comment by bmartinn** [comment]
> First, I'd like to thank the allegroai team for this gem.

Your kind words are very appreciated :heart:

The `clearml-agent` has two mode of authentication for pulling git repo's
1. user/pass (or user/token). If in your `clearml.conf` you provide [git_user / git_pass](https://github.com/allegroai/clearml-agent/blob/822984301889327ae1a703ffdc56470ad006a951/docs/clearml.conf#L18) , then
the agent will convert all git repository links to `https://user:pass@git_host_server/`.
2. SSH key authentication. To select this mode, in your `clearml.conf` set [force_git_ssh_protocol: true](https://github.com/allegroai/clearml-agent/blob/822984301889327ae1a703ffdc56470ad006a951/docs/clearml.conf#L25). In this case the agent assumes you have SSH keys inside your `~/.ssh` folder, and it will 
convert all git repo links to `ssh://git@git_host/`. 

@dltkhacene I think that what you are looking for is (2), WDYT ?

**Comment by dltkhacene** [comment]
Hello! 
Thank you for your quick reply!
I have tried the force git ssh protocol, but it stills alter the url of the remote.
I'm a bit carried away for the moment, I'll be back with more details.

**Comment by dltkhacene** [comment]
Hello again!
I'm really sorry I didn't find the time to inspect this issue in detail. I will close the issue for now and will reopen when I have more time.
Thanks again and keep up the great job!

**Comment by bmartinn** [comment]
Sure thing, if the issue arise please re-open.
