### ISSUE TITLE
Pipeline status "Pending" no matter what

### ISSUE THREAD

**Issue by maffei2443** [allegroai/clearml#308]
Hi, I'm new on ClearML.
I tried to execute the [pipeline example][ex] but I got the (permanent) status "Pending".
I would like to know how to effectively **start** the pipeline.

![pending-clearml](https://user-images.githubusercontent.com/19755960/107650265-0d8c7800-6c5d-11eb-8d71-11b1d5c55f4f.png)

[ex]: https://github.com/allegroai/clearml/blob/master/examples/pipeline/pipeline_controller.py

**Comment by bmartinn** [comment]
Hi @maffei2443 
Was the issue solved?

**Comment by maffei2443** [comment]
@bmartinn well not exactly. I suppose I should have instantiated some workers, but even after doing this the task took soooo long to finally run and failed on step2. I really couldn't understand how to use workers/queue .

**Comment by bmartinn** [comment]
Sure @maffei2443 you can read more about workers here:
https://github.com/allegroai/clearml-agent
https://allegro.ai/clearml/docs/docs/concepts_fundamentals/concepts_fundamentals_workers_and_queues.html
https://allegro.ai/clearml/docs/docs/use_cases/clearml_agent_use_case_examples.html

BTW: If you are looking for information you can always ask on the Slack channel, there is always someone there that will gladly help you out.
