### ISSUE TITLE
Scientific notation number in list not converted correctly in cloned task

### ISSUE THREAD

**Issue by trbschneider** [allegroai/clearml#313]
### Description
I encountered a problem when cloning a task from the webui where the Hyperparameters contain a list or tuple with scientific notation (such as 2e-6 etc). When running the task the first time, it runs fine but when cloning the task and running again, the numeric value in scientific notation is interpreted as a string. See below for minimal example to reproduce:

### Code
```[python]
from clearml import Task
task = Task.init()
parameters = {
    'list': [1.0, 2e-6],    
}
parameters = task.connect(parameters)
print(parameters)
print(parameters['list'][1]-parameters['list'][0])
```

### Steps to reproduce
(I reproduced the issue on google collab and with the clearml demoserver)

1. Run above code
Output:
```
{'list': [1.0, 2e-06]}
-0.999998
```
2. Clone task on web UI and enqueue
3. Cloned task will fail due to type mismatch between list items
Output:
```
{'list': [1.0, '2e-06']}
Traceback (most recent call last):
File "/root/.clearml/venvs-builds/3.7/code/Untitled17.py", line 10, in <module>
print(parameters['list'][1]-parameters['list'][0])
TypeError: unsupported operand type(s) for -: 'str' and 'float'
```
### Software versions
clearml==0.17.4
Clearml server version: 0.17.0-67 (https://demoapp.demo.clear.ml/)

**Comment by bmartinn** [comment]
Thank you @trbschneider , we were able to reproduce and confirm the issue.
It seems to stem from PyYAML parsing of the text, basically `'2.0e-06'` will  be parsed as float but `'2e-06'` will be parsed as string. Apparently this is a known [PyYAML issue](https://github.com/yaml/pyyaml/pull/174)
Let me see what we can do, I'll update here once there is a working fix.

**Comment by bmartinn** [comment]
Hi @trbschneider 
Good news, the fix is available :) 
Feel free to test it with:
```
pip install git+https://github.com/allegroai/clearml.git
```

**Comment by jkhenning** [comment]
Closing this as it was already released. Please reopen if required.
