### ISSUE TITLE
Custom metrics in Web UI Project overview not persistent

### ISSUE THREAD

**Issue by daandres** [allegroai/clearml#314]
I'm using the experiments page of a project in ClearML Web UI to visualize some custom metrics. Therefore I've customized my table via (https://allegro.ai/clearml/docs/docs/webapp/webapp_exp_table.html?highlight=customize#adding-metrics).
But whenever I leave the page for another project and go back, the table will be resetted. Is there a way to store configuration for a specific project?

On Stackoverflow I was suggested to open an issue here. (https://stackoverflow.com/questions/66317706/clearml-web-ui-custom-column-not-persistent/66360938#66360938)

**Comment by ainoam** [comment]
@daandres Looking at the current [demo app](https://demoapp.demo.clear.ml/) it seems that per-project column selection persists on navigating between projects.

Which version of the ClearML server are you working with (you can find this out in the Profile page), is it your own install?

**Comment by daandres** [comment]
The issue also exist in Demo App. It does not affect the "normal" columns. Just the custom metric columns. 

I installed ClearML sevrer on a private instance. And just updated with docker-compose pull. (Version is not displayed like in Demo)

I'll work on a concrete path to reproduce this issue. But it involves sevaral projects and page reload. So when editing on one project, the metric column on other project vanishs. Sometimes only a page refresh reflects this.

**Comment by ainoam** [comment]
@daandres There's indeed different behaviour between the "normal" or "common" columns (e,g.  'Name' or 'Status') whose visibility is "global" in the sense it affects all projects (i.e. hiding the 'Tags' column will impact all projects) and the custom metric columns whose visibility preference is persistent per user, per project.

When I mentioned that it seems to be working on the demo app, I was considering the following scenario:
- Enter project A
- Add custom metric column 'Metric x' to the experiment table
- Navigate to projects, then enter project B
! No column for 'Metric x'
- Navigate to projects, then enter project A
- 'Metric x' column is present.

However, there seems to indeed be an issue with a slightly more elaborate flow, where in the second project (B) you also add a custom column (e.g. 'Metric y'), and this results in 'nullifying' your initial configuration in the first project (A).
This issue should be resolved in the next ClearML Server release.

**Comment by daandres** [comment]
I can confirm, the last paragraph, tahts the main issue. having multiple projects with each custom metric columns, deletes previous custom metric column on other project. 

Ok I'll close this issue, when I can check it afte new release is public available.

**Comment by jkhenning** [comment]
Closing this as it was already released. Please reopen if required.
