### ISSUE TITLE
Unable to load image

### ISSUE THREAD

**Issue by acjoseph** [allegroai/clearml#323]
Hello,

I am running a local version of the ClearML server using the provided Docker image. I am trying to save images and have them reported in the ClearML web UI, however the images do not load and when I click on an open image link I get a 404 Not Found page.

My output directory is `/opt/clearml/data/fileserver` and the images that I am trying to load within the web UI are properly saved there.

Any help would be appreciated!

**Comment by jkhenning** [comment]
Hi @acjoseph,

Can you share your `clearml.conf` file's contents? Specifically, what are the values in the `api` section?

Also, can you please share the part of your code in which you initialize the ClearML Task and report the image?

**Comment by acjoseph** [comment]
I figured out the problem. I had a line-break (`\n`) in the title of the image I was saving:

```
logger.report_media(title = "Title\nSubtitle", series = 'plot', iteration = iteration, local_path = fname)
```

Removing the line-break fixes the issue and allows the images to be viewed.

**Comment by bmartinn** [comment]
@acjoseph FYI title/series will now be properly quoted even if you do pass `/r` , `/n`
Thanks for catching it :)
