### ISSUE TITLE
[FR] Add CLEARML_DEFAULT_OUTPUT_URI to set up output_uri from env var

### ISSUE THREAD

**Issue by vfdev-5** [allegroai/clearml#328]
Following [this discussion on the slack](https://clearml.slack.com/archives/CTK20V944/p1617633172312200), I'd like to ask for a feature to setup `output_uri` from env var:
```bash
export CLEARML_DEFAULT_OUTPUT_URI="https://files.community.clear.ml/"
python main.py
```
and it should log models to specified output_uri and not the local storage.

Thanks !

**Comment by bmartinn** [comment]
Thanks @vfdev-5, sounds good to me,
A few notes:
-  If you have `default_output_uri` configured in your `clearml.conf` the environment variable `CLEARML_DEFAULT_OUTPUT_URI` will **override** the configuration file value.
- If you pass a value to `output_uri` in the `Task.init(..., output_uri='s3://use_bucket/')` call, the `CLEARML_DEFAULT_OUTPUT_URI`  variable, as well as the  `default_output_uri`, are **ignored**

Updating here once we have an RC out :)

**Comment by bmartinn** [comment]
Hi @vfdev-5 
Just updating here that an RC is out :)
```
pip install clearml==-0.17.6rc1
```

**Comment by jkhenning** [comment]
Hi @vfdev-5, closing this. Please re-open if required.
