### ISSUE TITLE
report_histogram with string type x values

### ISSUE THREAD

**Issue by kyunghyukkim** [allegroai/clearml#332]
Can report_histogram take x values as characters? 
Can layout_config take such x values?
For example, xs = ['a', 'b', 'c'] and ys = [0.1, 0.2, 0.3]
logger.report_histogram(title='title', series='series', 
                        iteration=0, np.array(ys), xaxis='abc_series', layout_config={??})

I tried report_plotly and could generate such a histogram with character type x values. 
fig = px.histogram(df[['x', 'y']], x='x') # df['x'] = ['a', 'b', 'c'] and df['y'] = [0.1,0.2,0.3]
logger.report_plotly(title='title', series='series', iteration=0, figure=fig)

But, when two different experiments were compared, two separate plots were generated. If these two plots can be overlapped like by using report_histogram, I would also take this route of report_plotly. 
Thank you.

**Comment by bmartinn** [comment]
Hi @kyunghyukkim 
Are you referring to naming the different histogram bucket (bars) ? 
If this is the case, I think what you are looking for is the `x_labels` argument, see [report_histogram](https://allegro.ai/clearml/docs/rst/references/clearml_python_ref/logger_module/logger_logger.html#clearml.logger.Logger.report_histogram)

Example:

```python
from clearml import Task
Task.init(project_name='examples', task_name='histogram example')
logger = Task.current_task().get_logger()
# report a single histogram
histogram = np.random.randint(10, size=10)
# optional histogram bucket labels
histogram_labels = ['bucket {}'.format(i) for i in range(len(histogram))]
logger.report_histogram(
    "single_histogram",
    "random histogram",
    iteration=iteration,
    values=histogram,
    xaxis="title x",
    yaxis="title y",
    xlabels=histogram_labels,
)
```

**Comment by kyunghyukkim** [comment]
Hi @bmartinn 
Thank you for your helpful answer!
