### ISSUE TITLE
Legend missing while plotting from pandas dataframe + seaborn.

### ISSUE THREAD

**Issue by milongo** [allegroai/clearml#337]
Hi,

If I load up a Pandas DataFrame and plot it using `seaborn.lineplot()`, the default behavior on `plt.show()` is that the legend includes the names of the columns. Logging the resulting figure using clearml's `logger` results in a plot in which the line names are lost and read `"_line0, _line1, _line2, ..." etc.

Example below:

```
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from clearml import Task
import pandas as pd
import datetime
import pandas_datareader.data as web
from pandas import Series, DataFrame
sns.set_theme()
# Connecting ClearML with the current process,
# from here on everything is logged automatically
task = Task.init(project_name='examples', task_name='Matplotlib example')
start = datetime.datetime(2016, 1, 1)
end = datetime.datetime(2017, 1, 11)
df = web.DataReader("AAPL", 'yahoo', start, end)
df.tail()
sns.lineplot(data=df)
logger = task.get_logger()
logger.report_matplotlib_figure(
                title="example", series="plot", iteration=0, figure=plt.gcf()
            )

```

Please note the difference between calling `plt.show()` and the resulting plot in the experiment's Plot tab.

**Comment by bmartinn** [comment]
Hi @milongo 
I verified the issue, this is what I'm getting:
![newplot (16)](https://user-images.githubusercontent.com/51887611/115162044-c3cf6c00-a0a9-11eb-89b1-ad75c4686674.png)

I'm assuming we are supposed to get the legend with the proper series names like in this one:
![fig](https://user-images.githubusercontent.com/51887611/115162076-08f39e00-a0aa-11eb-8f03-2c9cbd410fff.png)

**Comment by bmartinn** [comment]
Hi @milongo,
can you verify the latest from the git solves the issue ?
```
pip install git+https://github.com/allegroai/clearml.git
```

**Comment by milongo** [comment]
Hi @bmartinn , looks good to me for now! I will close for now. Thank you!
