### ISSUE TITLE
Logout Failed

### ISSUE THREAD

**Issue by buti1021** [allegroai/clearml#349]
When trying to logout from the UI on a self hosted ClearML server I receive the following error:
Logout Failed Unable to find endpoint for name login.logout and version 2.13

**Steps to reproduce:**

- Deploy ClearML Server with Win10 following:
- https://allegro.ai/clearml/docs/docs/deploying_clearml/clearml_server_win.html
- Log in on the UI
- Try to log out

**Comment by jkhenning** [comment]
Hi @buti1021,

Thanks for pointing this out. We'll soon release a patch release to solve this 🙂

**Comment by buti1021** [comment]
Fixed
