### ISSUE TITLE
Minimum System Requirements

### ISSUE THREAD

**Issue by tahsinkedi** [allegroai/clearml#350]
Hello all, 
We are planning to install clearml and start discovering it in our ML team. 
I was looking for minimum system requirements and couldn't find it anywhere.
What is the required or suggested cpu, memory and disk space to use it ? 
Thanks

**Comment by jkhenning** [comment]
Hi @tahsinkedi, welcome to ClearML 😄 

We usually regard the minimum system requirements as those we use when running our AWS AMIs, which are usually:
- 2 vCPUs
- 8GB RAM
- At least 100GB of disk space

Note that disk space is mostly used for the fileserver storage (which you might not use if you intend to use different cloud storage solutions), and for ElasticSearch storage (which may depend on the number of metrics reported by your experiments and the overall number of experiments), but this may be increased over time, of course.

**Comment by tahsinkedi** [comment]
Thank you @jkhenning for the very fast response
