### ISSUE TITLE
Unable to mount Google Drive in clearml docker agent - container arguments mess up with spaces and backslashes in the path 

### ISSUE THREAD

**Issue by johnml1135** [allegroai/clearml#358]
I want to mount G:/Shared Drive/MY_SHARED_DRIVE to my docker container with the argument `-v "G:/Shared Drive/MYSHARED_DRIVE":/data`, but clearml sees the space in the path (even though it is surrounded by double  quotes), splits it up into multiple arguments and drops the double quotes.  This makes mounting drives with spaces unusable.

Moreover, when having a path with backslashes such as `\\my\windows\network\path`, it doubles all the backslashes to `\\\\my\\windows\\network\\path`.  This is not desirable as it also needs to be manually updated.

**Comment by bmartinn** [comment]
Hi @johnml1135 
So first you are correct, docker arguments are broken by "space" as this is the default for docker run commands.
If this is a fixed mount (which sounds like it is), how about you add it to the `clearml.conf`,  where arguments are properly sperated as they are a list of strings.
See example [here](https://github.com/allegroai/clearml-agent/blob/4f7407084d1900a79d455570c573e60f40208742/docs/clearml.conf#L134)
```
agent.extra_docker_arguments: ["-v", "G:/Shared Drive/MYSHARED_DRIVE:/data"]
```

Regardless we could add support for `shlex` parsing (I'm just trying to think if it will break other setups)

**Comment by johnml1135** [comment]
I did put in into clearml.conf and it separated it there by spaces as well.  I was not able to find a work around after messing with it for 1-2 hours.

**Comment by bmartinn** [comment]
Hi @johnml1135 
I verified the `cleaml.conf` workaround and it seems to work. 
Could you share the exact log of the agent failing, when you pass the mount using the configuring `agent.extra_docker_arguments: ["-v", "G:/Shared Drive/MYSHARED_DRIVE:/data"]` ?

**Comment by johnml1135** [comment]
Ok - I'll check again Monday if it works.  If it does, that at least is a good workaround.

**Comment by johnml1135** [comment]
Updating clearml.conf worked!  Specifically, I:
* Updated clearml.conf:
  * `extra_docker_arguments: ["-v","G:\Shared drives\MY_FOLDER:/data/my-folder"]`
* Reran the experiment - now it had access to the data!

Note: if I was running this in docker directly, the command would be:
`docker run -it -v "G:\Shared drives\MY_FOLDER":/data/my-folder ubuntu ls /data/my-folder`
with double quotes (") around the drive name with spaces.  In `extra_docker_arguments`, these double quotes are not needed.

This is a good workaround.  I also agree that it would be challenging to have this same behavior in the single window (string, not list).  As this is acceptable for my needs, I am ok with closing this issue.

**Comment by bmartinn** [comment]
Sounds good to me 👍  closing the issue
