### ISSUE TITLE
ClearML mis-recognizes module name when populating script path and makes no Args 

### ISSUE THREAD

**Issue by johnml1135** [allegroai/clearml#359]
I have a python file I call as a module (i.e., `python -m my.module.path my_arg`) and when ClearML makes an experiment out of it, it messes up the "SCRIPT PATH" in the Experiment.  Specifically, it records it as this:
* SCRIPT PATH: `-m my.module my_arg`

The "Args" of the Experiment are allocated correctly, just not then script path.

Work around: I am able to update the script path manually and run the files.

**Comment by bmartinn** [comment]
@johnml1135 it sounds like it records the setup correctly.
In order for the `clearml-agent` to run your code as a python module, the `script path` has to start with "-m module_name".
Are you referring to the additional "my_arg" as the wrong setup?

**Comment by johnml1135** [comment]
Let me be clearer:

* command: `python -m part_1.part_2.part_3 arg_a`
* What is populated in SCRIPT_PATH: `-m part_1.part_2 arg_a`
* What should be populated in SCRIPT_PATH: `'-m part_1.part_2.part_3`

The last part of the module name is being chopped off and the first arg is kept in SCRIPT_PATH as well as being in the Args section.  This should not be, instead it should be the entire module name (all 3 sections) and no args.

Is that clearer?

**Comment by bmartinn** [comment]
Thanks, it makes sense now. 
Let me see if I can reproduce this behavior.

**Comment by johnml1135** [comment]
Have you been able to reproduce it?

**Comment by johnml1135** [comment]
Moreover another related issue is happening - when there is more than 1 parameter passed, they all end up in the "SCRIPT_PATH" but the ARGS hyperparameter does not appear.  This is a breaking issue because I cannot add a ARGS set of parameters in the GUI.

**Comment by johnml1135** [comment]
The "no Args" specifically is causing **running experiments from the web to not work at all**.  Args appeared to be populated last week, but a recent change seems to have broken it.

**Comment by bmartinn** [comment]
Hi @johnml1135 
I was not able to reproduce this issue (tested with the latest RC `1.0.3rc1`).
Could you maybe help with a simple toy example to reproduce the issue? Or maybe point to a public repository to test with ?

**Comment by johnml1135** [comment]
I put this script in a repo under .\folder1\folder2\clearml_test.py:
```
import argparse

from clearml import Task


def main() -> None:
    parser = argparse.ArgumentParser(description="Extracts text corpora from Paratext projects")
    parser.add_argument("arg", nargs="*", metavar="name", help="my arg")
    parser.add_argument("--kwarg", default=False, action="store_true", help="KW Arg")

    args = parser.parse_args()
    Task.init(project_name="Trial", task_name=str(args.arg) + "_KWArg:" + str(args.kwarg))


if __name__ == "__main__":
    main()
```

I executed: `$ python -m folder1.folder2.clearml_test hello --kwarg`
The SCRIPT PATH created was: `-m folder1.folder2 hello --kwarg`
The Args are:
`Arg = ['hello']`
`kwarg = True`

**Comment by bmartinn** [comment]
Thanks @johnml1135 
I was able to reproduce the issue.
Fix is being worked on :)

**Comment by johnml1135** [comment]
Thanks - I look forward to the fix!

**Comment by bmartinn** [comment]
Hi @johnml1135 
A fix was merged, do you feel like verifying it solved the issue ?
```
pip install git+https://github.com/allegroai/clearml.git
```

**Comment by bmartinn** [comment]
@johnml1135 this is strange...
Running `python -m folder1.folder2.clearm_test --kwarg`
I'm getting `Args/kwarg: True` as well as `Args/arg: ['hello']`  in the configuration tab.

This is the exact script I'm using
```python
import argparse
from clearml import Task


def main() -> None:
    parser = argparse.ArgumentParser(description="Extracts text corpora from Paratext projects")
    parser.add_argument("arg", nargs="*", metavar="name", help="my arg")
    parser.add_argument("--kwarg", default=False, action="store_true", help="KW Arg")

    args = parser.parse_args()
    Task.init(project_name="Trial", task_name=str(args.arg) + "_KWArg:" + str(args.kwarg))


if __name__ == "__main__":
    main()
```

**Comment by johnml1135** [comment]
I figured it out through walking through the debugger.  My code was a little different in an important way.  I needed to import clearml before I parse the args - because the parsed args are registered when initializing.  The following code can reproduce the issue (if it is one at all):

``` python
import argparse


def main() -> None:
    parser = argparse.ArgumentParser(description="Extracts text corpora from Paratext projects")
    parser.add_argument("arg", nargs="*", metavar="name", help="my arg")
    parser.add_argument("--kwarg", default=False, action="store_true", help="KW Arg")
    parser.add_argument("--clearml", default=False, action="store_true", help="KW Arg")

    args = parser.parse_args()

    if args.clearml:
        from clearml import Task

        Task.init(project_name="Trial", task_name=str(args.arg) + "_KWArg:" + str(args.kwarg))


if __name__ == "__main__":
    main()
```

Part of the relevant code that makes the core decision is:
* Check if the argparser has already been called when [initializing the task](https://github.com/allegroai/clearml/blob/2e95881c76119964944eaa0289549617e8afeee9/clearml/task.py#L584)

**Comment by johnml1135** [comment]
Moreover, by the Args just staying in the `SCRIPT PATH` rather than the `Args` hyper parameter, it can still be used.  Your discretion to close or try to fix this further.

**Comment by bmartinn** [comment]
> I figured it out through walking through the debugger. My code was a little different in an important way.

Nice @johnml1135 !
Yes the actual code connecting with the argparse is called when importing the package, when you manually import the `clearml` package After you have parsed all the arguments, the knowledge is gone, hence missing Args section.
May I suggest you always import `clearml` , and only on "demand" call `Task.init` ? 
This way when you do you will have a full log of the argparser.
wdyt ?

**Comment by johnml1135** [comment]
I now know enough to make my code work (import clearml before using argparse), and the bugs are worked out (in 1.0.3).
