### ISSUE TITLE
Job is not closing anymore

### ISSUE THREAD

**Issue by Thibaud-Ardoin** [allegroai/clearml#361]
Hello, 

Thanks for the new versioning, and generally for all your great work. 
Since I updated to 1.0, I have processes that stays open after my program crashes... I need to ^C in order to finish the process in the end. And on remote machines it is quite a pain.

Am I missing something in the update that create this holding of the process ? Or is there a bug ?

Thanks in advance for your help
Best,
T.

**Comment by bmartinn** [comment]
Hi @Thibaud-Ardoin 
Is this a locally executed process or remote (i.e. agents spins it) ?
What's the exact `clearml` version you are using ?
Can you test with the latest RC? I think we fixed a similar issue, `pip install clearml==1.0.3rc0` 
What is the exact setup (OS/Python etc.) and how can I reproduce it?

p.s.
Thank you for the kind words ❤️  :)

**Comment by Thibaud-Ardoin** [comment]
Sorry for the late reply...
But yes indeed it works when updating to that version, thank you !
