### ISSUE TITLE
Using Task.add_requirements() with Task.init() results in warnings but it appears it still works.

### ISSUE THREAD

**Issue by ecm200** [allegroai/clearml#364]
I am running a training script to train PyTorch based CNNs for image classification problems.
To set up the experiment on the _clearml-server_, I am first running the script locally to create the training experiment on the server. The environment I am using to train PyTorch models has a couple of none PYPI packages which I need installed into the remote environment for successful execution.

The first one is a local package that I have created for training networks, encompassing the use of _PyTorch Ignite_, which is called CUB_TOOLS.
The second is a latest master branch version of the TIMM repository.

The code block I have implemented to create the ClearML experiment is as follow:

```python
## CLEAR ML
# Connecting with the ClearML process
task = Task.init(project_name='Caltech Birds', task_name='Train network on CUB200', task_type=Task.TaskTypes.training)
# Add the local python package as a requirement
task.add_requirements('./cub_tools')
task.add_requirements('git+https://github.com/rwightman/pytorch-image-models.git')
# Setup ability to add configuration parameters control.
params = {'TRAIN.NUM_EPOCHS': 20, 'TRAIN.BATCH_SIZE': 32, 'TRAIN.OPTIMIZER.PARAMS.lr': 0.001, 'TRAIN.OPTIMIZER.PARAMS.momentum': 0.9}
params = task.connect(params)  # enabling configuration override by clearml
print(params)  # printing actual configuration (after override in remote mode)
```

On execution locally, the terminal reports the following:

```
ClearML Task: created new task id=6165c74fe8ab419b815e5cf0df55f11d
ClearML results page: http://ecm-clearml-server-001.westeurope.cloudapp.azure.com:8080/projects/30034b3199e24123896c8eff9bf16d29/experiments/6165c74fe8ab419b815e5cf0df55f11d/output/log
2021-05-19 09:27:33,690 - clearml.task - WARNING - Requirement ignored, Task.add_requirements() must be called before Task.init()
2021-05-19 09:27:33,705 - clearml.task - WARNING - Requirement ignored, Task.add_requirements() must be called before Task.init()
```

It reports an issue that the **Task.add_requirements()** should be called before **Task.init()**. However, when inspecting the environment files associated with the experiment, it seems to have been added correctly to the list of requirements. Execution of the experiment on a remote compute instance using _clearml-agent_ results in the correct setup of the environment, with the additional manually specified requirements  added. For example:

```
matplotlib == 3.3.4
numpy == 1.20.2
pandas == 1.2.4
pytorch_ignite == 0.4.4
pytorchcv == 0.0.65
scikit_image == 0.18.1
tensorboard == 2.4.1
torch == 1.8.1
torch_lucent == 0.1.7
torchvision == 0.9.1
yacs == 0.1.8
./cub_tools
git+https://github.com/rwightman/pytorch-image-models.git
```

Unless I have not understood the way the system works, it looks as though the warnings are wrong and confusing.

**Comment by bmartinn** [comment]
Hi @ecm200 
> It reports an issue that the Task.add_requirements() should be called before Task.init(). However, when inspecting the environment files associated with the experiment, it seems to have been added correctly to the list of requirements.

Yes, since the package detection happens in the background, there is no way to guarantee that it will catch the new requirement modification (e.g. `add_requirements()` call) before it completes, hence we recommend calling it before Task.init()  (notice it is a class method )
The assumption is that in most cases there is one single Task.init per execution, so putting the add_requirements on a class level is not that terrible. The other option would be that the add_requirements will trigger another session of "python package analysis". It is possible to implement, but it seemed excessive at the time...
wdyt?

**Comment by ecm200** [comment]
Hi @bmartinn,

I have now called the _add_requirements()_ class method before the _init()_ call of the Task class, and this has stopped the warnings. I think it makes sense to do it this way, and I think you are right about the other ways being excessive.

```python
# Connecting with the ClearML process
# First add the repo package requirements that aren't on CONDA / PYPI
Task.add_requirements('git+https://github.com/ecm200/caltech_birds.git@clearml_integrations#egg=cub_tools&subdirectory=cub_tools/')
Task.add_requirements('git+https://github.com/rwightman/pytorch-image-models.git')
# Now connect the script to ClearML Server as an experiment.
task = Task.init(project_name='Caltech Birds', task_name='Train PyTorch CNN on CUB200 using Ignite [Library: '+cfg.MODEL.MODEL_LIBRARY+', Network: '+cfg.MODEL.MODEL_NAME+']', task_type=Task.TaskTypes.training)
```
