### ISSUE TITLE
Clone Experiment Failed - Error 800 : Data validation error

### ISSUE THREAD

**Issue by johnml1135** [allegroai/clearml#365]
I tried to clone an experiment and got:

ERROR
Clone Experiment failed

More info
Error 800 : Data validation error: container={'setup_shell_script': ValidationError(StringField only accepts string values,)}

The container shell script is empty, but the container arguements are: -v \\\\wsl$\Ubuntu\data:/data

**Comment by bmartinn** [comment]
@johnml1135 could it be you have a `$` inside the docker argument, Is this `-v \wsl$\Ubuntu\data:/data` correct ?
It seems like an odd mixture of `/` and `\` I'm assuming Windows ?

**Comment by jkhenning** [comment]
Hi @johnml1135 ,

Are you using your own hosted ClearML Server?

If so, we'll be releasing a patch version for the server very soon with a fix that might be related to your issue - we've fixed validation errors for `null` values inside the container (which produce the same error response) and I suspect this might be your issue.

I'll update here when the new version is out.

**Comment by johnml1135** [comment]
I am using the pro version (https://app.pro.clear.ml/).
The \\\\wsl$\Ubuntu\data:/data is to call out something mounted in a WSL container.  I included it if there was an issue, but it appears that this was not the driving issue for the error.

**Comment by johnml1135** [comment]
Is the new version out?

**Comment by jkhenning** [comment]
The new version was just released :)
https://github.com/allegroai/clearml-server/releases/tag/1.0.2
