### ISSUE TITLE
python 2.7 compatibility is broken

### ISSUE THREAD

**Issue by yuvlyg** [allegroai/clearml#366]
Seems like python2 support is broken, with incompatible python3 syntax
```
In [1]: import clearml
  File "/home/yuval/.local/lib/python2.7/site-packages/clearml/automation/optimization.py", line 1514
    copy(dict(**params, **{"status": id_status.get(job_id)})))  # noqa
                      ^
SyntaxError: invalid syntax
```
Installed clearml-1.0.2 with pip, on WSL1 (ubuntu 18.04 on win10), python 2.7.17
Thanks!

**Comment by jkhenning** [comment]
Hi @yuvlyg,

Thanks for reporting this - we'll push a fix soon.

However, we are actually thinking of deprecating Python 2.7 support soon - most optimization packages don't support it anyway, and it is long past it's End-of-Life - do you have any special use-case for using it?

**Comment by yuvlyg** [comment]
Thanks @jkhenning , I have a repo whose migration to python3 is delayed, nothing special :)
