### ISSUE TITLE
Add configuration to draft experiment

### ISSUE THREAD

**Issue by johnml1135** [allegroai/clearml#370]
After an experiment is made, if there are no HYPER PARAMETER Args or Environment, they cannot be created.  I am requesting that this feature be added, specifically:
* When an Experiment is in draft mode
* Select the Configuration tab
* In the left column (USER PROPERTIES and HYPER PARAMETERS), have a new button called "Add"
* When selected, it allows the user to add whichever fields (Args, Environment, etc.) that are not already present in the Configuration.

**Comment by ainoam** [comment]
@johnml1135 I think that the original idea considers that to have any impact, any such parameter must depend on existing code in the original script to be affected by the parameters value, and so it might be confusing if you add parameters through the UI where the executed script does not handle them.

Which use case are you considering?

**Comment by johnml1135** [comment]
I see why this could cause more problems than it solves.  This is related to `Args` not showing up when I call a python module: `python -m my.package.module` - #359.  I guess when that one resolves, this would not be needed.
