### ISSUE TITLE
Tracked scalars dissapear after experiment ends

### ISSUE THREAD

**Issue by mhashas** [allegroai/clearml#383]
Hi,

I was just looking at an experiment I did yesterday and saw that scalars after a certain point got cut off (i.e. alphabetically everything after "li" is cut off / dissapeared). We do have 30+ scalars that we track as we are in a multitask scenario. If I start a new experiment however, they are all there, but once its finished they disappear. Any ideas?

PS: We have 1.0.3 clearml and the latest clearl server

**Comment by jkhenning** [comment]
Hi @mhashas ,

Can you add some more info? for example, do you see these scalars before the experiment ends? if so, where?

**Comment by mhashas** [comment]
Hi, in the scalars tab of the experiment. I can see them during training, but once the experiment ends they are "cut-off"

**Comment by mhashas** [comment]
Here is a minimum script you can use to test this. It seems there is a maximum of 100 scalars that are supported, everything over is "cut-off" 

`
import random
from clearml import Task

task = Task.init(project_name="scalar_disappearing_test", task_name="scalar_test")

logger = task.get_logger()
random_names = [str(i) for i in range(150)]

for i in range(100):
    for name in random_names:
        logger.report_scalar(title=name, series="Test", value=random.uniform(0, 1), iteration=i)
`

**Comment by mhashas** [comment]
In my case, when my experiment ends I add some final scalars, which tips the scalar count over 100, so some get cut-off :)

**Comment by jkhenning** [comment]
Hi @mhashas ,

So that clears it up - there's currently a query limit for the UI set at 100 for metric/variant aggregations. Are you using a locally-hosted server?

**Comment by mhashas** [comment]
Hi,

Yes, we do :)

**Comment by jkhenning** [comment]
Well, in that case, you can increase the configured limit using the `services.events.events_retrieval.max_variants_count` setting.
You can do that using:
- environment variables in your `docker-compose.yml` file (or `docker-compose.override.yml`) under the `apiserver.environment` section:
 * `CLEARML__SERVICES__EVENTS__EVENTS_RETRIEVAL__MAX_METRICS_COUNT: "50"`
 * `CLEARML__SERVICES__EVENTS__EVENTS_RETRIEVAL__MAX_VARIANTS_COUNT: "200"`
- A config file named `services.conf` placed in the server's configuration folder (usually `/opt/clearml/config`) containing the following:
  ```
  events.events_retrieval.max_metrics_count: 50
  events.events_retrieval.max_variants_count: 200
  ```

You can of course use different values, but currently it's advised that the multiplication of these two values will not exceed 10,000.

**Comment by mhashas** [comment]
In case anybody else encounters this, it's actually the other way around:

CLEARML__SERVICES__EVENTS__EVENTS_RETRIEVAL__MAX_METRICS_COUNT: "200"
CLEARML__SERVICES__EVENTS__EVENTS_RETRIEVAL__MAX_VARIANTS_COUNT: "50"

Thanks a lot for the help @jkhenning, have a nice day :)
