### ISSUE TITLE
[Feature request] Support click CLI

### ISSUE THREAD

**Issue by klekass** [allegroai/clearml#386]
I am using 'click' instead of argparse for my CLI, therefore command line arguments are not recognised as such. This causes problems when using clearml-agent and remote execution. If i understood correctly, the task is pulled by the agent and after environment setup, the worker calls the training script again, with the command line arguments catched from ArgumentParser. Using click, this leads to the problem, that command line arguments are not recorded, and the remote worker fails, because no command line arguments are provided. 
My current workaround is, to use default arguments and task.connect() on those, such that the default arguments are updated after the task has been started by the agent. However, this solution does not allow to use 'required' command line arguments.

The following MWE, when called with 'python mwe.py --dataset CUSTOM_DATASET' would print 'CUSTOM_DATASET' on my local machine but on the remote machine it would use the default parameter 'DEFAULT_DATASET'. Making the parameter --dataset required, the script would crash.
 
```
import clearml
import click

@click.command()
@click.option('--dataset', type=str, default='DEFAULT_DATASET')
def main(dataset):

    print(dataset)

    task = clearml.Task.init(project_name='example_project', task_name='example_task')
    task.execute_remotely(queue_name='example_queue')


if __name__ == '__main__':
    main()

```

**Comment by jkhenning** [comment]
Hi @klekass, thanks for opening this - we'll put this in the pipeline and update here 🙂

**Comment by bmartinn** [comment]
Hi @klekass , initial support for click was added to the main branch 🎊 
Could you verify it works as expected on your code?
```
pip install git+https://github.com/allegroai/clearml.git
```

**Comment by klekass** [comment]
Hi @bmartinn, it works perfectly. Thanks a lot 🙂

**Comment by bmartinn** [comment]
Yey! I'll update here once the RC is out

**Comment by klekass** [comment]
There seems to be a bug using flags:

```
import clearml
import click


@click.command()
@click.option('--some_flag', is_flag=True)
def main(some_flag):

    task = clearml.Task.init(project_name='example_project', task_name='example_task')
    task.execute_remotely(queue_name='docker_test')


if __name__ == '__main__':
    main()

```

using this example, the remote host fails with the following error, if the flag is not set:

`Error: Invalid value for '--some_flag':  is not a valid boolean`

**Comment by bmartinn** [comment]
Hi @klekass 
A fix was pushed, it should work now 🤞 , could you verify on your code ?
```
pip install git+https://github.com/allegroai/clearml.git
```

**Comment by klekass** [comment]
Works! 🥳  Thanks!

**Comment by jkhenning** [comment]
Hi @klekass,

I'm closing this. Please re-open if there are any issues.
