### ISSUE TITLE
Uploading dataset to MinIO

### ISSUE THREAD

**Issue by VodopaDev** [allegroai/clearml#391]
Hi!
I have been trying for some time to upload a Dataset to some MinIO S3 server using the `--storage` CLI option or the `output_url` arg in `Dataset.create(...)`

My config (related to S3/MinIO) is as follow:
```
api {
    web_server: http://web_server_url.com
    api_server: http://api_server_url.com
    files_server: http://files_server_url.com
    credentials {
        "access_key" = "access"
        "secret_key" = "secret"
    }
}

sdk {
    aws {
        s3 {
            credentials: [
                {
		  host: "minio_url:80" # url has no http:// or s3://, only the domain
		  bucket: "clearml" # Does it have importance?
		  key: "minio_key"
		  secret: "minio_pass"
		  multipart: false
		  secure: false
                }
            ]
        }
    }
    development.default_output_uri: "s3://minio_url:80/clearml" # This one works for task artifacts!
}
````

While it correctly works when uploading task's artifacts, using the Dataset interface doesn't work with my many tries:
- `output_url = minio_url`: upload to the local folder with the url as name
- `output_url = minio_url/clearml`: same as above
- `output_url = http://minio_url/clearml`: POST failed 
- `output_url = s3://clearml`: _Failed uploading: An error occurred (InvalidAccessKeyId)_.
- `output_url = s3://minio_url/clearml`: same as above.
- `output_url = s3://minio_url:80/clearml`: _SSL validation failed_. This one is really strange, I tried all possible set-ups with the `secure` parameter in sdk.aws.s3 conf and also activated https for the MinIO server but it still did not work.

Is there an obvious configuration I missed?

**Comment by JDennisJ** [comment]
Hi @VodopaDev,

The s3://minio_ip:9000/bucket_name should work, can you try with IP? 
BTW, why port 80?

**Comment by VodopaDev** [comment]
Hi @JDennisJ!
Strangely it worked today after I removed the port from the URL, deactivated SSL on MinIO and put the _secure_ field to false. Thanks for your help 😄
I use port 80 because it is the port exposed by OpenShift (RedHat k8s) when you make a k8s Service accessible from outside the cluster.  

I don't know if it is the right place to write this for feature suggestions but this problem made me think of two features:
- instead of using s3://minio_url/bucket, one could use s3://bucket and it would be completed with Minio's URL if it is defined by the _host_ field in config. One downside is that it would forbidden the use of an Amazon bucket and a Minio bucket if they share the same name.
- as for task output, the config could have a _development.default\_dataset\_uri_, to automatically upload dataset to a specific storage instead of the fileserver.

**Comment by JDennisJ** [comment]
Hi @VodopaDev,

Happy to read that your issue is solved now :)

> instead of using s3://minio_url/bucket, one could use s3://bucket and it would be completed with Minio's URL if it is defined by the host field in config. One downside is that it would forbidden the use of an Amazon bucket and a Minio bucket if they share the same name.

Yes, this won't allow the user to have both AWS bucket and Minio bucket and we want to have this option.

> as for task output, the config could have a sdk.development.default_dataset_uri, to automatically upload dataset to a specific storage instead of the fileserver.

You can define the task's `output_uri` (storage for the task) in several places, `sdk.development.default_dataset_uri` is one example for it, you can also use `CLEARML_DEFAULT_OUTPUT_URI` as an environment variable for it.
