### ISSUE TITLE
Suggestion: Add loading bar to Clearml-data add SHA2 generation

### ISSUE THREAD

**Issue by ErenBalatkan** [allegroai/clearml#393]
Since generation of SHA2 can take up some time, a loading bar would be greatly beneficial for displaying when the process will finish and if the process is progressing without any errors.

I delved a bit into the clearml code and I believe this should get the job done, but I'm not %100 sure.

https://github.com/allegroai/clearml/blob/75d05775709d2d2f7bf1691d90748dbf3b06f754/clearml/datasets/dataset.py#L984
```
self._task.get_logger().report_text('Generating SHA2 hash for {} files'.format(len(file_entries)))
pool = ThreadPool(cpu_count() * 2)
pool.map(self._calc_file_hash, file_entries)
pool.close()
self._task.get_logger().report_text('Hash generation completed')
```
to
```
import tqdm
self._task.get_logger().report_text('Generating SHA2 hash for {} files'.format(len(file_entries)))
pool = ThreadPool(cpu_count() * 2)
pool.map(self._calc_file_hash, file_entries)
for _ in tqdm.tqdm(pool.imap_unordered(self._calc_file_hash, file_entries), total=len(file_entries)):
        pass
pool.close()
self._task.get_logger().report_text('Hash generation completed')
```

**Comment by jkhenning** [comment]
Hi @ErenBalatkan,

Would you like to contribute a PR for this change? We'd love that 🙂 

(as a side note - the `import tqdm` should be `try/except ImportError` protected so that this feature will only be in effect if tqdm is installed)

**Comment by ErenBalatkan** [comment]
#396 Here is the PR.

I checked if I could also do the same for the file upload phase but upload system seems more complex then what I can figure without really delving into it.

**Comment by jkhenning** [comment]
Thanks! I'll take a look soon :)

**Comment by jkhenning** [comment]
Merged, thanks!
