### ISSUE TITLE
[Feature] Allow explicitly adding remote execution dependencies

### ISSUE THREAD

**Issue by idantene** [allegroai/clearml#395]
It would be great if one could specify local dependencies for remote execution (e.g. files on the local file system), that would in turn be uploaded to the file server before running `execute_remotely()` and downloaded in the remote task before running the code.

This is also done "behind the scenes" for uncommitted git changes, so it would be nice if the user could specify additional files.

**Comment by bmartinn** [comment]
Hi @idantene 
Is this feature basically an extension of #340  ?

**Comment by idantene** [comment]
Hey @bmartinn, thanks for replying so fast!
I suppose it is, yes, though this is specifically for the `execute_remotely()` call (so the `clearml-agent` is running by default).
If I were to compare this to `pip` and `setup.py`, then it would be nice to have the equivalent of `package_data=...` (see [here](https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html))

**Comment by bmartinn** [comment]
Hi @idantene 
I see the use case, to make things easier, I'll continue the conversation in #340, to create a concise discussion / knowledge base.

**Comment by bmartinn** [comment]
Closing this issue and continuing the discussion in the original #340
