### ISSUE TITLE
[Feature] Extend DataFrame support in report_table to allow for MultiIndex

### ISSUE THREAD

**Issue by idantene** [allegroai/clearml#399]
If we modify [pandas_reporting.py](https://github.com/allegroai/clearml/blob/master/examples/reporting/pandas_reporting.py#L28) to use a `MultiIndex` instead of an index, the WebUI will concatenate the `MultiIndex` entries using a comma:

![image](https://user-images.githubusercontent.com/12184618/125318559-9d386e80-e342-11eb-83ed-1547d872c453.png)

Notice how `training,main` and `training,ba_mean_h...` are originally two-level `MultiIndex` in pandas.

**Comment by JDennisJ** [comment]
Hi @idantene ,

Sure, we will add it to the table reporting.
Just to be sure, you added the `MultiIndex` with `pd.MultiIndex.` ?

**Comment by idantene** [comment]
The original index in the above example is created directly by using a dictionary input to `pd.DataFrame` (and can also be achieved with e.g. `groupby`, etc). I don't think the method used to create the `MultiIndex` is of critical importance..?

**Comment by JDennisJ** [comment]
Nope, isn't important, just wanted to reproduce your specific case.

Will keep you updated about it

**Comment by bmartinn** [comment]
Hi @idantene 
A fix was pushed to the main branch, care to test ?
```
pip install git+https://github.com/allegroai/clearml.git
```

**Comment by idantene** [comment]
Hey @bmartinn, I'd love to! Just to clarify though
1. Do I install this on the local/remote agent?
2. If remote agent, do I need to restart my queues?

**Comment by idantene** [comment]
Hey @bmartinn, I was finally able to test it out.
Much better now, although there's now a `null` header for the indices.

![image](https://user-images.githubusercontent.com/12184618/128835405-4f7ae463-6983-4686-9881-80411b43d532.png)

**Comment by jkhenning** [comment]
Closing this as this was already released. Please reopen if required.
