### ISSUE TITLE
No debug samples after 100 epochs

### ISSUE THREAD

**Issue by horefice** [allegroai/clearml#405]
Hi there,

I was running my experiments and I saw that debug samples are not available after 100 epochs. I have re-run a simpler version of my experiment and yet it yields the same results. The images' urls after 100 epochs are just pointing to a "Not Found" address and the naming also looks to be wrong/reset (ex: http://localhost:8081/my_project/MyExp/metrics/Visualization%20images/%20train/Visualization%20images_%20train_00000001.jpeg for an image in the 102 epoch that shouldn't be indexed/named as *001.jpeg).

I have 1.0.3 clearml and the clearml server was updated a few weeks ago.

**Comment by bmartinn** [comment]
Hi @horefice 
Any chance you can share a simple reproducible code ?
BTW: by default the last 100 iteration of each title/series is stored.
This can be changed by editing the `clearml.conf` [here](https://github.com/allegroai/clearml/blob/fb6fd9ac4a6820b4d1d3b8d6dcc60208a45d0718/docs/clearml.conf#L32):
Can you try changing it to 200 and test?
```
file_history_size: 200
```

**Comment by horefice** [comment]
Hi @bmartinn

Thank you for your explanation. I was actually in doubt if it was a bug or a misconfigured feature :)
Since it is a working setting, i have it covered. I will be closing the issue.

Thank you again and have a nice day!
