### ISSUE TITLE
Selectively disable automatic logging

### ISSUE THREAD

**Issue by klekass** [allegroai/clearml#408]
I am looking for a way to selectively disable automatic logging. I was surprised, that i could not find anything in the docs or on github, since I think there are several applications where it makes sense to disable automatic logging, therefore I am opening this issue instead of asking on SO. Currently I am looking for a way to disable automatic logging of TF_DEFINES, beacause I am using remote execution, where the agent runs multiple subprocesses. Since all the subprocesses' arguments are logged under the same name to the ClearML server (TF_DEFINE), the arguments of different subprocesses interfere with each other. I can explain my problem in more detail if necessary, but I think the precise application does not really matter. 

Is there a way to disable automatic logging of TF_DEFINES (or arguments in general)?

**Comment by JDennisJ** [comment]
Hi @klekass,

> Is there a way to disable automatic logging of TF_DEFINES (or arguments in general)?

TF_DEFINES are part of tensorflow and tensorboard logging. You can disable any framework logging with `auto_connect_frameworks` parameter in your `Task.init` call, so for disabling the `TF_DEFINES` logging, you can have:

`task = Task.init(project_name="My Project", task_name="My Task", auto_connect_frameworks={"tensorflow":False, "tensorboard": False})` but it will disable **all** `tensorflow` and `tensorboard` logging too.

You can disable also just the python Argument Parser (or just part of it) with `auto_connect_arg_parser` parameter, you can view all the options [here](https://clear.ml/docs/latest/docs/references/sdk/task#taskinit).

And for console logging - https://clear.ml/docs/latest/docs/faq#controlling_logging

> I was surprised, that i could not find anything in the docs or on github, since I think there are several applications where it makes sense to disable automatic logging

I will message this one to our docs team, maybe we can add an example for `auto_connect_frameworks` usage, what do you think?

**Comment by klekass** [comment]
Hi @JDennisJ, thanks for the quick reply! 

It would be nice, however, to have a bit more fine grained control over what is being logged to the server, if tensorflow/tensorboard is enabled. The `auto_connect_arg_parser` argument for example provides the possibility to add a dictionary to control which argumetns are being logged. Would it be possible to have such a feature also for the individual frameworks? As an example I can think of  model logging: I would like to use all the amazing features of clearml auto-logging, but my training pipline produces a checkpoint every n steps. It is unnecessary to upload all those models, so it would be nice to have the possibility to disable model logging (and upload only the models I want to keep).

**Comment by JDennisJ** [comment]
Hi @klekass 

> it would be nice to have the possibility to disable model logging (and upload only the models I want to keep).

Trying thinking with you about the best interface doing so, how could ClearML know the models you want to keep? Do you have something you thought about? feel free to share / suggest 😃

**Comment by klekass** [comment]
Actually, I was only thinking about about a way to **selectively** turn off automatic logging (e.g. model logging, or TF_DEFINES logging). The models i want to keep, can be logged manually. I was just using model logging as an example, initially I wanted to turn of TF_DEFINES 🙂 

Since `auto_connect_arg_parser` already provides an interface for selective logging

```auto_connect_arg_parser={'do_not_include_me': False, }```

Why not using the same interface for other frameworks? E.g.

```auto_connect_frameworks={'matplotlib': True, 'tensorflow': { 'scalars': True, 'models': False ...   }, ...}```

**Comment by JDennisJ** [comment]
This is the current status for TF, you can enable TB and disable TF. ClearML will report you TB reports (ClearML automagic TB outputs) but the models won't be reported.

The only exception for you in this case is the TF_DEFINE flags, maybe adding those to the dict as well can be a solution for it?

**Comment by bmartinn** [comment]
Hi @klekass 
Currently if you only want Tensorboard to be automagically logged, without auto-logging loaded/stored models you can use:
`Task.init(..., auto_connect_frameworks={'tensorflow': False, 'tensorboard': True,})`
Funny enough `TF_DEFINES` are logged in both cases, we could probably add that as well, wdyt?

**Comment by klekass** [comment]
I have to admit, it wasn't entirely clear to me what was being logged by Tensorflow and what was being logged by Tensorboard, since TF_DEFINES were logged in both cases. I think TF_DEFINES should either only be logged by one of the frameworks or even better, as @bmartinn suggests, as a separate 'framework'.

**Comment by bmartinn** [comment]
Hi @klekass 
You can now test it :) 
``` python
from clearml import Task

task = Task.init(... , auto_connect_frameworks={'tfdefines':False})
```

Install the latest directly from the git repository:
```
pip install git+https://github.com/allegroai/clearml.git
```

**Comment by jkhenning** [comment]
Closing this as it was already released. Please reopen if required.
