### ISSUE TITLE
app.community.clear.ml down ?

### ISSUE THREAD

**Issue by Thibaud-Ardoin** [allegroai/clearml#410]
Hello,

It seems that the page to dashboard the training just got down...
All the saving of information if failing aswell.
``2021-07-26 12:03:00,060 - clearml.Metrics - ERROR - Action failed <504/0: events.add_batch (<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
)>
``

**Comment by jkhenning** [comment]
Hi @Thibaud-Ardoin,

Yeah, we've just had a Cloud HW failure issue - the servers are back up, and we're investigating.

**Comment by Thibaud-Ardoin** [comment]
Nice, thanks for your quick reaction !!
