### ISSUE TITLE
Exception during artifacts retrieving

### ISSUE THREAD

**Issue by luigiba** [allegroai/clearml#411]
Hello, I'm trying to code a flow where a clearML Task read from a source of data, divides it into _n_ batches and then starts _n_ different subtasks to process them in parallel. Each batch (a pandas DataFrame) is first uploaded as an artifact (using the method `upload_artifact`) so that the subtasks (created through the function `create_function_task`) can access them using the artifacts dictionary.

After uploading an artifact, I tried to retrieve it using `task.artifacts["artifact_name"].get()`. The latter raises the following exception:
```
Traceback (most recent call last):
  File "examples\clearml_integration.py", line 115, in <module>
    batch = parent_task.artifacts[parameters["Function/artifact_name"]].get()
  File "C:\Users\lb\.clearml\venvs-builds\3\lib\site-packages\clearml\binding\artifacts.py", line 160, in get
    self._object = pd.read_csv(local_file, index_col=[0])
  File "C:\Users\lb\.clearml\venvs-builds\3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\lb\.clearml\venvs-builds\3\lib\site-packages\pandas\io\parsers\readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\lb\.clearml\venvs-builds\3\lib\site-packages\pandas\io\parsers\readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\lb\.clearml\venvs-builds\3\lib\site-packages\pandas\io\parsers\readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\lb\.clearml\venvs-builds\3\lib\site-packages\pandas\io\parsers\readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\lb\.clearml\venvs-builds\3\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas\_libs\parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 642, in pandas._libs.parsers.TextReader._get_header
  File "pandas\_libs\parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 1917, in pandas._libs.parsers.raise_parser_error
  File "C:\Users\lb\AppData\Local\Programs\Python\Python38\lib\_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "C:\Users\lb\AppData\Local\Programs\Python\Python38\lib\gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "C:\Users\lb\AppData\Local\Programs\Python\Python38\lib\gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b',s')
```

From the UI, I noticed that the batch artifacts are stored using the extension `".csv.gz"`. However, after downloading them though the UI, I also noticed that they contains plain csv. No compression is made. I think that the exception is raised by pandas library when reading them because it has inferred gzip comrpession even if the file contains plain csv data.

**Additional Information**

Python Version:
   `Python 3.8.10`

Pip freeze output:
```
attrs==20.3.0
backports.entry-points-selectable==1.1.0
certifi==2021.5.30
chardet==4.0.0
clearml==1.0.4
clearml-agent==1.0.0
distlib==0.3.2
filelock==3.0.12
furl==2.1.2
future==0.18.2
humanfriendly==9.2
idna==2.10
joblib==1.0.1
jsonschema==3.2.0
mypy-extensions==0.4.3
neo4j==4.2.0
numpy==1.21.1
orderedmultidict==1.0.1
packaging==21.0
pandas==1.3.1
pandera==0.6.5
pathlib2==2.3.6
Pillow==8.3.1
platformdirs==2.1.0
psutil==5.8.0
pyhocon==0.3.58
PyJWT==2.0.1
pyparsing==2.4.7
pyreadline==2.1
pyrsistent==0.18.0
python-dateutil==2.8.2
pytz==2021.1
PyYAML==5.3.1
requests==2.25.1
scikit-learn==0.24.2
scipy==1.7.0
six==1.15.0
threadpoolctl==2.2.0
typing==3.7.4.3
typing-extensions==3.10.0.0
typing-inspect==0.7.1
urllib3==1.26.6
virtualenv==20.6.0
wrapt==1.12.1
```

**Comment by JDennisJ** [comment]
Hi @luigiba,

Thanks for the detailed information, I will try to reproduce it on my side.

Can you try running the [artifacts](https://github.com/allegroai/clearml/blob/master/examples/reporting/artifacts.py) and [get_artifacts](https://github.com/allegroai/clearml/blob/master/examples/reporting/artifacts_retrieval.py) examples?

**Comment by luigiba** [comment]
Hi @JDennisJ 
I've just tried it. The run was successful for both of them

**Comment by JDennisJ** [comment]
Hi @luigiba ,

I tried to reproduce this issue but no luck.

Can you attach a small toy example? do you maybe have a sample file you are using and can share?

**Comment by luigiba** [comment]
Hi @JDennisJ , below the toy example

```python

import pandas as pd
from clearml import Task
import clearml
import time


task_name = "TASK_NAME"
task = Task.init(project_name="PROJECT_NAME", task_name=task_name)
task.execute_remotely(queue_name="default")


def get_batch_generator(number_of_batch=3, number_of_rows_per_batch=100):
    """
    dummy data generator
    """
    for _ in range(0, number_of_batch):
        yield pd.DataFrame([j for j in range(0, number_of_rows_per_batch)], columns=["col"])


# main task execution
if task.name == task_name:
    i = 0
    task_ids = []
    for batch in get_batch_generator():
        i += 1
        # upload batch artifact
        func_name = "batch_{}_{}".format(round(time.time() * 10000), i)
        task.upload_artifact(name=func_name, artifact_object=batch)

        # start and enqueue clearml subtask that will process it
        subtask = task.create_function_task(
            func=lambda x: x,
            func_name=func_name,
            task_name="{}_{}".format(task.name, func_name),
            artifact_name=func_name,
            task_id=task.id
        )
        task.enqueue(subtask, queue_name="default")
        task_ids.append(subtask.id)

    # wait for subtasks to finish
    for task_id in task_ids:
        clearml.Task.get_task(task_id=task_id).wait_for_status(check_interval_sec=30.0)

#subtask execution
else:
    parameters = task.get_parameters()

    parent_task_id = parameters["Function/task_id"]
    parent_task = Task.get_task(task_id=parent_task_id)
    print("parent task {} has the following artifacts: {}".format(parent_task_id, parent_task.artifacts))

    # retrieve the artifact (this generate the exception)
    batch = parent_task.artifacts[parameters["Function/artifact_name"]].get()

    # process the batch ...



```

**Comment by bmartinn** [comment]
Hi @luigiba 
> From the UI, I noticed that the batch artifacts are stored using the extension ".csv.gz". However, after downloading them though the UI, I also noticed that they contains plain csv.

I think this is the issue here, could it be a Windows / Linux pandas issue.
Specifically see [here](https://github.com/allegroai/clearml/blob/6a91374c2dd177b7bdf4c43efca8e6fb0d432648/clearml/binding/artifacts.py#L365), this is a `to_csv` call, with compression argument, which should create a '`.csv.gz`' file, but I suspect that on Windows (in some scenarios) you end up with `.csv` file. It also seems the file extension is fixed to [.csv.gz](https://github.com/allegroai/clearml/blob/6a91374c2dd177b7bdf4c43efca8e6fb0d432648/clearml/binding/artifacts.py#L215)

Could you verify this is the case in your Windows machine (i.e. `to_csv` with compression creating `.csv` file not `.csv.gz`)?

**Comment by luigiba** [comment]
Hi @bmartinn , I've tried. The call `df.to_csv(path, compression="gzip")` creates a compressed csv file on my Windows machine. Afterwards, I'm able to read it using `pd.read_csv(path, compression="gzip")`

**Comment by bmartinn** [comment]
Hi @luigiba 
Sorry for the delay, quick update, this issue seems to be a very very odd behavior of the `cleaml-fileserver`, that for some reason deduces the `csv.gz` is actually a `csv` file compressed with `gzip`, then the headers change and the client (browser or python) will un-gzip the stream, and you end up with the `csv` content, but with the `.csv.gz` extension.

This is basically the root cause of the problem, notice the actual files stored are okay, and if you use any other storage option (object-storage / shared folder etc.) there won't be any problem.

We are looking into it, and will probably release a hot patch version for the `cleaml-server` once the problem is fixed (should not take long).

**Comment by jkhenning** [comment]
Hi @luigiba,

ClearML Server v1.1.1 was released with a specific fix for this issue - please check it out and let us know if it works for you 🙂

**Comment by luigiba** [comment]
Hello everyone, I confirm you that with the new release the issue no longer exists. Thank you 👍

**Comment by michelkok** [comment]
Hi guys, I think this issue needs to be reopened as I seem to be having this issue. I'm on v2 of the server (and training from Windows most of the time). 
Weird thing is that it is seemingly random - some of the csv's are corrupted and others are fine.
