### ISSUE TITLE
Error could not verify credentials with clearml servers behind k8s ingress. 

### ISSUE THREAD

**Issue by okyspace** [allegroai/clearml#416]
Hi, I have tested that I can setup properly when I hit direct to the ip of the clearml servers. but when i uses domain names with ingress to route to clearml servers, it fails. 
Specifically, when i do clearml-init to initialise the servers, it fails. 

I can connect to the clearml servers using domain names through browsers though. 
May I know if there is specific url that clearml needs for the verification?

**Comment by jkhenning** [comment]
Hi @okyspace,

What error are you seeing exactly? What can you get to using the browsers and what is the response you see?

**Comment by okyspace** [comment]
@jkhenning Apologies. I got the port number mixed up, thus the servers were not running correctly.
