### ISSUE TITLE
[possible bug] clearml-task cwd

### ISSUE THREAD

**Issue by valeriano-manassero** [allegroai/clearml#423]
I'm trying to create a task that is not in repository root folder.

Let's say the directory is called `test_folder` ; the following command works:

```
clearml-task --project test_project --name remote_test --script test_folder/test_artifact.py --repo git@github.com:testest/test --branch main --requirements test_folder/requirements.txt  --skip-task-init --task-type data_processing
```

but we know it's better so set `WORKING DIRECTORY` in the task itself so:

```
clearml-task --project test_project --name remote_test --script test_artifact.py --repo git@github.com:testest/test --branch main --requirements requirements.txt  --skip-task-init --task-type data_processing --cwd test_folder
```
Error: Script entrypoint file '/Users/test-user/clearml-pipelines/git@github.com:testest/test/step1_dataset_artifact.py' could not be found.

Basically it's not possible to set `WORKING DIRECTORY` using clearml-task while it's obviously possible using ClearML UI on already existing task to customise it.

**Comment by valeriano-manassero** [comment]
After @bmartinn comments on Slack I think the error message is misleading a bit; using https in front of `--repo` enabled me to set also the working directory with this command:

```
clearml-task --project test_project --name remote_test --script test_artifact.py --repo https://github.com/testest/test --branch main --requirements requirements.txt  --skip-task-init --task-type data_processing --cwd test_folder
```

Not sure if we need to keep this issue open.

**Comment by bmartinn** [comment]
Thanks @valeriano-manassero 
The detection of the remote SSH repository failed, thus it assumed this is a local repository, raising an error when the folder was not found.
It should be fixed now on the main branch, let me know if it worked.

```
git install git+https://github.com/allegroai/clearml.git
```

**Comment by valeriano-manassero** [comment]
Tested and it works! Ty!
