### ISSUE TITLE
bug: `Task.set_initial_iteration` doesn't affect the server

### ISSUE THREAD

**Issue by patzm** [allegroai/clearml#439]
I want to report two problems:
1. The docs for the parameter `iteration` of any `Logger.report_*` method are not matching what happens.
2. Setting the _initial iteration_ doesn't affect the server.

For instance, if I have a `clearml.Task` instance which is being resumed from iteration `100`, the initial iteration (as returned by `Task.get_initial_iteration`) is `100`. Lets say I want to report a scalar for iteration `105` by calling [`Logger.report_scalar`](https://allegro.ai/clearml/docs/rst/references/clearml_python_ref/logger_module/logger_logger.html#clearml.logger.Logger.report_scalar)
```python
clearml_logger.report_scalar(value, iteration=105)
```

However, it gets plotted for iteration 205 on the server (i.e. 100 + 105). Hence the docs should say here that `iteration` really is an offset to the _initial iteration_. There would be two ways to do this properly:
1. manually calculate the offset
   ```python
   clearml_logger.report_scalar(value, iteration=105 - clearml_task.get_initial_iteration())
   ```
   This works for all manual summaries, however not for the automatically done summaries (GPU / CPU / memory utilization; see #440)
2. Initially set the _initial iteration_ statically to `0`, relying on an external recovery of the current iteration. This is broken however. When I do this, my local instance of `clearml_task` gets updated properly. However,
   ```python
   clearml_logger.report_scalar(value, iteration=105)
   ```
   will still cause the server to show that summary value for iteration 205, not 105.

**Comment by patzm** [comment]
yes that makes sense. And by simply subtracting the initial iteration (as I showed above in the example), that works.

However consider a scenario where checkpoints are not done at every iteration, but say every 100 iterations (deep learning for instance). If the worker gets stopped for some reason at say iteration 105, it hasn't written a checkpoint for that iteration. The last checkpoint was for iteration 100. So if the worker resumes, and for some reason randomness affects the progression, then a fork in logic is possible. Hence, reports that have previously been written for the iterations 101, 102, 103, 104, and 105 might not be like that anymore. It would be great if they could be overwritten (which ClearML supports afaik). However, for that to work, one needs to be able to _(re)set_ the initial iteration to the iteration from which the worker resumes its work (the checkpoint).

WDYT?

**Comment by bmartinn** [comment]
> However consider a scenario where checkpoints are not done at every iteration, but say every 100 iterations

You are absolutely correct, this is a great argument for needing to set it manually.
The issue with "last_iteration" is that the server actually updates it, and if we overwrite it once, the next report will change it back again. 

I can think of two solutions:

1) We allow an additional "set_last_checkpoint" iteration, that will store an additional runtime value on the Task. Then when we continue the execution we first look for the specific runtime value "set_last_checkpoint", if it is not there, we revert to "last_iteration".

2) Like (1) only we set it automatically when we auto-magically log/store the model (e.g. on the torch.save/tf.save calls)

wdyt?

**Comment by patzm** [comment]
I like the idea. I would see (2) as an extension to (1) though. I would still implement `set_last_checkpoint` (and thus expose), and then simply call it when detecting that a checkpoint was written. If people use ClearML as a even more agnostic (i.e. not knowing about DL frameworks as TF or PT), it still allows them to bind all functionality properly. Think about a new DL framework coming around. Or an entirely different field that also wants to report stuff.

**Comment by bmartinn** [comment]
> I like the idea. I would see (2) as an extension to (1) though. I would still implement set_last_checkpoint (and thus expose), and then simply call it when detecting that a checkpoint was written

Agreed! Let's call it a new feature request :) 
@patzm Could you close this issue and open a new feature request issue with the [discussed](https://github.com/allegroai/clearml/issues/439#issuecomment-907882223) design ?

**Comment by patzm** [comment]
I think this comment is a good summary of the idea already: https://github.com/allegroai/clearml/issues/440#issuecomment-908284422
