### ISSUE TITLE
Wall time + hidden experiments slows the web page severly!

### ISSUE THREAD

**Issue by InCogNiTo124** [allegroai/clearml#441]
We run a clearml experiments instance.
We have quite a few metrics, but the system is usually snappy enough.

![image](https://user-images.githubusercontent.com/12953598/131346175-d1ea4f82-f389-4e3f-ad52-e8269cee1049.png)

However, a peculiar behaviour is presented when selecting wall time horizontal axis: when all experiments are shown, the web page does not freeze but _hiding_ some of the graphs freezes the web page and crashes the site.

The web page is still fluid if all the graphs are shown with wall time, or any other horizontal axis with hidden plots

it seems that the specific configuration of wall time + hiding some plots is excruciatingly slow

**Comment by InCogNiTo124** [comment]
Tested on Chrome, Brave and Firefox

**Comment by bmartinn** [comment]
Thank you for reporting @InCogNiTo124 !
What's the `clearml-server` version you are using ?
How do I reproduce it ? Do I need a certain amount of metrics ?  Or certain amount of reported values ?

**Comment by InCogNiTo124** [comment]
> Thank you for reporting @InCogNiTo124 !
> What's the `clearml-server` version you are using ?

I cant seem to find the exact version since we used `allegroai/clearml:latest` when deploying, but the sha digest is `9223d063ced1d2172a6602d3c42658862f84c0545e2f7b059ed7d8ac650e283d`, that should be enough

> How do I reproduce it ? Do I need a certain amount of metrics ? Or certain amount of reported values ?
We reproduce the behaviour while comparing two experiments with those 11 metrics from above, and not a lot of values

**Comment by InCogNiTo124** [comment]
I've actually obtained clearance to share the logs with you to reproduce (if you have the ability)

Just load the graphs up, they are already in the wall time format, and if you hide some graphs, you'll experience the freeze
[clearml-freeze-logs.zip](https://github.com/allegroai/clearml/files/7090364/clearml-freeze-logs.zip)

**Comment by bmartinn** [comment]
Thank you @InCogNiTo124 for the full logs.
We were able to reproduce the issue, this is a frontend bug, and it will be fixed in the upcoming release.
I can also confirm this bug will only manifest itself on the comparison page when you have hidden scalar plots (do not ask me why ;) )

**Comment by InCogNiTo124** [comment]
> We were able to reproduce the issue, this is a frontend bug, and it will be fixed in the upcoming release.
> I can also confirm this bug will only manifest itself on the comparison page when you have hidden scalar plots (do not ask me why ;) )

I am very glad you fixed that. I'll be sure to watch the commits closely to find out what is happening :))

When's the next release?

**Comment by jkhenning** [comment]
Hi @InCogNiTo124 ,

We don't have a set date yet, but I assume it will be in the coming weeks - I'll update here once we have a target.

**Comment by jkhenning** [comment]
Closing this as this was already released. Please reopen if required.
