### ISSUE TITLE
Jupyter notebook preview not generated due to UnicodeEncodeError error

### ISSUE THREAD

**Issue by 14thApostle** [allegroai/clearml#442]
While trying to save a very simple jupyter notebook, noticed that the "notebook preview" was not being generated.
Tracked down the error to be an UnicodeEncodeError
![image](https://user-images.githubusercontent.com/52763947/131526013-95fc3203-971a-40d2-8c30-fbdf5c3837f4.png)
at [codebase](https://github.com/allegroai/clearml/blob/master/clearml/backend_interface/task/repo/scriptinfo.py#L412)

Changing it to 
```
with open(local_html.as_posix(), 'wt', encoding="utf-8") as f:
    f.write(html)
``` 
fixes it. I can open a PR for this.

**Comment by bmartinn** [comment]
Thank you @14thApostle !
Yes please PR the fix :)
