### ISSUE TITLE
clearml-task looking for requirements.txt file

### ISSUE THREAD

**Issue by eliorc** [allegroai/clearml#444]
Attempting to create a template from a task, I use the `clearml-task` CLI tool when my intention is only to create a template and not actually run it so I can later execute it in a pipeline.

When executing the command `clearml-task --script ....py --name "..." --project "..."` I get the following error

```
ClearML launch - launch any codebase on remote machine running clearml-agent
Creating new task

Error: requirements.txt not found [/home/elior/Dev/Projects/XXXXX/requirements.txt] Use --requirements or --packages
```

**Comment by bmartinn** [comment]
Hi @eliorc 
I believe a fix was just pushed to the main branch, could you verify it solved the issue ?

```
pip install git+https://github.com/allegroai/clearml.git
```

**Comment by eliorc** [comment]
> Hi @eliorc
> I believe a fix was just pushed to the main branch, could you verify it solved the issue ?

Verified, works :D

**Comment by eliorc** [comment]
@bmartinn when should we expect to see this in the official release?

**Comment by bmartinn** [comment]
RC should be out tomorrow (I think), and a few days later final release (v1.1)

**Comment by eliorc** [comment]
@bmartinn hi, we are at version v1.1.1 - is this already incorporated?

**Comment by bmartinn** [comment]
Sorry @eliorc , I forgot to update here on the new release :)
Yes `v1.1.1` contains the fix.
Closing the issue (if it resurfaces, please reopen)
