### ISSUE TITLE
Empty "Plots" section in case of missing time delay ("NO CHART DATA") 

### ISSUE THREAD

**Issue by TanjaLossau** [allegroai/clearml#446]
I initialize a task locally via Task.init() and started a python script for experiment evaluation which includes the generation of multiple evaluation plots in clearml. However, for some of my experiments, the plots section was empty.

It took me a while to realize that inserting a time delay may help.
Depending on the position of the time delay, some plots appeared and some not.

In my current implementation, I added a time delay of 2 seconds after the last task.get_logger().report_plotly block to ensure that all evaluation plots are uploaded to clearml. This should of course not be the way to go.
Is there an alternative way to ensure that the plots have been successfully uploaded to the server before ending the task?

**Comment by bmartinn** [comment]
Hi @TanjaLossau 

> In my current implementation, I added a time delay of 2 seconds after the last task.get_logger().report_plotly block to ensure that all evaluation plots are uploaded to clearml. 

So is it a matter of flushing the results ?
What is the clearml version, python version and OS ?
How can we reproduce it ?
Lastly, can you verify the problem exists with the latest RC:

```
pip install clearml==1.0.6rc1
```

**Comment by TanjaLossau** [comment]
Hi @bmartinn,

thanks for the quick response. 
My versions were/are
Clearml: 1.0.5 (but also after updating to 1.0.6rc1 the issue still occured) 
Python:  3.8.8
OS: opensuse15.1

Unfortunately, it is not reproducable.
However, I can observe that it happens more often if I schedule my jobs on a SLURM cluster as described in issue #406  using either

self._clearml_task=Task.get_task(task_id=self.clearml_task_id)
self._clearml_task.init(auto_connect_frameworks=False)

or 

task.close()
Task.get_task(task_id=task.id).mark_started(force=True).

I wrote the following example clearml plotting step. Using the default settings for npts and nlines a delay > 3 seconds was necessary to prevent the empty plot section.

-------------------------------------------

class ClearmlPlot(AbstractStep):
    def __init__(self, npts = 1000000, nlines = 10, delay=0):
        super(ClearmlPlot, self).__init__()

        self._npts = npts
        self._nlines = nlines
        self._delay = delay

    def update(self, meta_data: MetaData = None) -> MetaData:

        clearml_plot_series = [{   "name": f'line_{i}',
                                    "data": np.c_[np.arange(self._npts),
                                                  np.random.uniform(0.5+0.5*i/self._nlines,1,(self._npts,))*np.arange(self._npts)]
                                } for i in range(self._nlines)]

        self.clearml_task.get_logger().report_line_plot(
            title="Dummy Plot",
            series=[SeriesInfo(**series_params) for series_params in clearml_plot_series],
            iteration=self.clearml_task.get_last_iteration(),
            xaxis="x random",
            yaxis="y random"
        )

        if self._delay > 0:
            # add time delay to ensure that all plots are available in clearml
            import time
            time.sleep(self._delay)

        return MetaData()

**Comment by bmartinn** [comment]
Thanks @TanjaLossau , I was able to reproduce the behavior.

Let me shed some light on the mechanism of the event reporting.
The `report_line_plot` call generates the reporting events, these events are then passed to a background process/thread, where they are batched together (flushed every X seconds) and sent to the server.

In your case, all the reports (multiple calls to the `update` method) are actually batched into a single request sent to the server, together with the size of the event (i.e. the number or points on the graph) it creates a delay between the report call and actual data stored on the server. This is why adding a delay basically triggers the auto flush (i.e sending all the outstanding event reporting).
You can also replace the sleep with `Task.current_task().flush()` which will trigger the background event sending mechanism.

Make sense ?

**Comment by TanjaLossau** [comment]
Thanks @bmartinn for the explanation.
The flushing helped to solve the issue. So I will close the issue.
