### ISSUE TITLE
[Feature Request] Upload Artifact Fails on Non-Standard Dictionaries

### ISSUE THREAD

**Issue by jalexand3r** [allegroai/clearml#452]
Currently `upload_artifact` only checks whether an object is a `dict` before dumping to JSON:
https://github.com/allegroai/clearml/blob/51d70efbffa87aa41b46c2024918bf4c584f29cf/clearml/binding/artifacts.py#L380

However, there is no guarantee that values within the dictionary are JSON serializable (e.g. dictionaries of `DataFrames` will fail). 

Although it may not be best practice to upload dictionaries of objects instead of uploading each object individually, there are good use cases for the former. It would be nice to have error handling that defaults to pickling objects if `auto_pickle` is true and standard data type uploading fails.

**Comment by bmartinn** [comment]
Hi @jalexand3r 
> Although it may not be best practice to upload dictionaries of objects instead of uploading each object individually, there are good use cases for the former. It would be nice to have error handling that defaults to pickling objects if auto_pickle is true and standard data type uploading fails.

This is a good idea. So let's assume we try to upload a non-jsonable dict, we output a warning (e.g `JSON serialization failed, falling back to pickle`), then we would just pickle the dict itself, and upload the pkl file as artifact.
Is this what you had in mind?

**Comment by jalexand3r** [comment]
I would check the `auto_pickle` argument after the warning and before pickling, but yes, that is essentially what I had in mind.

**Comment by bmartinn** [comment]
Sounds good to be, @jalexand3r do you mind renaming the issue to feature request ?

**Comment by jkhenning** [comment]
Closing this as it was already released. Please reopen if required.
