### ISSUE TITLE
clearml only grabs local changes, not staged/chached changes

### ISSUE THREAD

**Issue by johnml1135** [allegroai/clearml#457]
When I have both staged/cashed and local changes, I get the following error (redacted with "***********"):
```
Using cached repository in "/root/.clearml/vcs-cache/***********.git"
Note: checking out '**********'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
  git checkout -b <new-branch-name>
HEAD is now at *********** Initial stab at child models.
type: git
url: git@github.com:*****/******.git
branch: HEAD
commit: ***********
root: /root/.clearml/venvs-builds/3.8/task_repository/***********.git
Applying uncommitted changes
Executing: ('git', 'apply', '--unidiff-zero'): b'error: patch failed: scripts/***********.py:6\nerror: scripts/***********.py: patch does not apply\n'
Failed applying diff
clearml_agent: ERROR: Failed applying git diff:
diff --git a/scripts/***********.py b/scripts/***********.py
index 5e47660..38fb68e 100644
--- a/scripts/scratchpad_s3.py
+++ b/scripts/scratchpad_s3.py

***********

ERROR! Failed applying git diff, see diff above.
``` 

It appears as if the staged changes are not actually applied?

**Comment by bmartinn** [comment]
Hi @johnml1135 

> When I have both stashed and local changes, I get the following error (redacted with "***********"):

Are you saying the stored `git diff` on the Task is corrupted in some way?
My only theory at the moment is that `git diff` is storing the uncommitted changes delta from the "staged state" and not the committed state...
Can you test with `sdk.development.store_code_diff_from_remote: true` in your `clearml.conf` file?
https://github.com/allegroai/clearml/blob/4955c7a784499252c6415dd6273bcae63f6a526b/docs/clearml.conf#L157

**Comment by johnml1135** [comment]
I believe the command should be `git diff HEAD` rather than `git diff`.  I am looking here as a reference: https://stackoverflow.com/questions/8452820/how-to-compare-the-working-tree-with-a-commit#:~:text=git%20diff%20%2D%2Dcached%20This,added%20them%20to%20the%20index.

Specifically, `git diff HEAD` will compare the working tree with the most recent checked in revision.  It is still the responsibility of the user to push the most recent revision to the origin though.

**Comment by johnml1135** [comment]
I believe here is the location that the change could be made:
https://github.com/allegroai/clearml/blob/1cb5dbb276026644ae20fef63d58256cdc887818/clearml/backend_interface/task/repo/detectors.py#L235-L241

**Comment by bmartinn** [comment]
Hi @johnml1135 
Can you verify the following fix solves the issue:
(btw: I did a quick test and it seems that this fix has no negative effects :slightly_smiling_face: )

https://github.com/allegroai/clearml/blob/1cb5dbb276026644ae20fef63d58256cdc887818/clearml/backend_interface/task/repo/detectors.py#L235-L241
```python
   diff=["git", "diff", "--submodule=diff", "HEAD", ], 
   diff_fallback_remote=["git", "diff", "HEAD",], 
```
If it does, could you PR it?

**Comment by jkhenning** [comment]
Hi @johnml1135, closing this. Please re-open if required.
