### ISSUE TITLE
Tags for tasks

### ISSUE THREAD

**Issue by israelwei** [allegroai/clearml#46]
Hello,
Is it possible to add "tags" for different tasks? It will be comfortable to search among different tasks by the tags created for them (For example, show all tasks with tags "adam"), and then compare them more easily- in order to not provide an over-descriptive task_name.

**Comment by bmartinn** [comment]
Hey @israelwei awesome idea! and to frank the actual underlying support already exists. 
We will adding this feature to the UI soon :)
Anyone wants to promote this feature request, feel free to up-vote

**Comment by manish2295** [comment]
Hi @bmartinn 
Is this feature added to the UI?

**Comment by bmartinn** [comment]
Hi @manish2295 
YES (finally!) next version, due to be released at the end of this month will have tags! :tada:

**Comment by bmartinn** [comment]
Hi @manish2295 ,

Forgot to update, but tags are officially supported as of Trains Server v0.15.0 😄
