### ISSUE TITLE
UI suggestion for searching in configuration tab

### ISSUE THREAD

**Issue by Alexfinkelshtein** [allegroai/clearml#467]
Pain point:
When viewing a task configuration tab, given a "complex" configuration with many entries, it takes some effort to scroll through the configuration to find some entry of interest. Unfortunately, the browser search "can't see" the whole configuration probably due to something like lazy loading.

Suggestion:
introduce a search bar in the top

**Comment by ainoam** [comment]
@Alexfinkelshtein Thanks for summarizing this [community discussion](https://clearml.slack.com/archives/CTK20V944/p1633505435308600). This should make it into one of the coming UI releases.

**Comment by jkhenning** [comment]
Closing this as this was already released. Please reopen if required.
