### ISSUE TITLE
Sub process logger

### ISSUE THREAD

**Issue by ophirazulai** [allegroai/clearml#482]
Hi,

Here is the description of the problem:

I have process A who creates logger using this command:
task = Task.init(project_name=args.clearml_proj_base + “/training”, task_name=args.clearml_task,
                     tags=[args.loss,‘patch size’ +  str(args.patch_size), str(args.num_features)+‘_’+str(args.max_features)+‘_’+str(args.unet_depth) , ‘two channels’, ‘lr_default’],
                     continue_last_task=False)
    logger = task.get_logger()

Then this process submit new job/process B (for inference) in our cluster and this job runs on a different computer.
The new job creates logger using:
task = Task.init(project_name=project_name, task_name=task_name)
or
task = Task.init(project_name=project_name, task_name=task_name, continue_last_task=False, reuse_last_task_id = False)
or
task = Task.init(project_name=project_name, task_name=task_name, continue_last_task=False)

Different project_name and task_name.

The problem is that all of B logs are created in the A task.
Also there is no entry for the new project_name/task_name.

Thanks,
Ophir Azulai
IBM Research AI

**Comment by jkhenning** [comment]
OK, but what does `submit_job` do? how do you create the new task?

**Comment by ophirazulai** [comment]
It is internal IBM job scheduler that simply starts new process on a different computer. 

Can it be that something is passed in the system variables ? Maybe a quick fix will be to override it

**Comment by jkhenning** [comment]
What I'm not sure is how you start a new process on the other machine - what do you provide to the ClearML Task.init(), how do you provide the `clearml.conf` configuration etc? What is being copied and/or reused from the current machine?
