### ISSUE TITLE
Error with reporting scalar code

### ISSUE THREAD

**Issue by 117Spartan** [allegroai/clearml#486]
https://github.com/allegroai/clearml/blob/e53a76b713910adaf87578c69e86f8154d4ab4c1/clearml/logger.py#L152

When running, I get this error:

```
Logger.current_logger().report_scalar(title='scalar metrics','series', value=scalar_series[iteration], iteration=iteration)
                                                                 ^
SyntaxError: positional argument follows keyword argument
````

Simple fix is to make it `series='series'`

And I don't think the code is complete, because it seems like the output only shows one dot in the graph. Here's the code that I think would be better:

```
for iteration in range (10):
    Logger.current_logger().report_scalar(title='scalar metrics', series='series', value=scalar_series[iteration], iteration=iteration)
```

so now that you can see a line graph in the results > scalars page.

**Comment by jkhenning** [comment]
Hi @117Spartan,

Noted, we'll push a fix soon. Thanks!

**Comment by jkhenning** [comment]
Hi @117Spartan,

Just updating that the docstring was updated according to your suggestion 🙂 - please close this issue if you have no further comments
