### ISSUE TITLE
[Feature Request] Automatic periodic or performance-based retraining of models?

### ISSUE THREAD

**Issue by Waerden001** [allegroai/clearml#487]
[Use Case]
Suppose we have several models in our clearml model registry, and we continuously monitor the performances of each model.  We might want to retrain the models periodically or retrain the models based on the monitored performances. 

[Pain]
Manually setting the retraining schedule is painful if we have dozens of models. 

[Possilble Solution]
- Is there a way in clearml to  automatically retrain a bunch of models based on the monitored performances?  
- Is there a standard way to automatically retrain the models periodically?

**Comment by jkhenning** [comment]
Hi @Waerden001,

You can use the Task Scheduler and set a trigger to retrain some models, based on any metrics reported to the system (see [here](https://github.com/allegroai/clearml/blob/master/examples/scheduler/trigger_example.py) for en example) - for example, you could set up a TaskScheduler with a model trigger on any model with tag `should_retrain`, and externally signal the need to retrain a model by placing such a tag on the required model

**Comment by Waerden001** [comment]
> Hi @Waerden001,
> 
> You can use the Task Scheduler and set a trigger to retrain some models, based on any metrics reported to the system (see [here](https://github.com/allegroai/clearml/blob/master/examples/scheduler/trigger_example.py) for en example) - for example, you could set up a TaskScheduler with a model trigger on any model with tag `should_retrain`, and externally signal the need to retrain a model by placing such a tag on the required model

Oh That looks great! Thanks~
