### ISSUE TITLE
DatasetTrigger triggered by tasks

### ISSUE THREAD

**Issue by FawadAhmed322** [allegroai/clearml#491]
I setup a DatasetTrigger with a dataset_project argument specified. I did not however set any arguments like trigger_on_publish or trigger_on_tags etc. What would happen is that when I published a dataset, the trigger would activate as expected. I set a schedule_task so it would enqueue a task. Only problem is that since I enqueued it in the same project as the one I set dataset_project as, the DatasetTrigger would activate, which would in turn activate another task. This would go on recursively. I don't think a DatasetTrigger should be triggered by things other than Dataset Related.

**Comment by jkhenning** [comment]
Hi @FawadAhmed322,

Just updating that following the [Slack channel thread](https://clearml.slack.com/archives/CTK20V944/p1636547890397100) we were able to reproduce it, and will introduce a fix soon 🙂

**Comment by bmartinn** [comment]
Hi @FawadAhmed322 
The fix to the issue was pushed, you can test it with the latest RC:
```
pip install clearml==1.1.5rc1
```

**Comment by FawadAhmed322** [comment]
I've had no issues after installing ClearML 1.1.5rc1. Thanks for the fix.
