### ISSUE TITLE
[feature request / bug?] Correct metric logging after continuing experiments

### ISSUE THREAD

**Issue by crazyfrogspb** [allegroai/clearml#496]
[Slack thread](https://clearml.slack.com/archives/CTK20V944/p1634905036055200)

I have a problem with correct metric logging when continuing tasks on spot instances. Even if I manually set initial iteration to 0, continued task still adds a huge offset to all logged metrics (epoch + previous_last_iteration).

This makes analyzing experiments trained on the spot instances very difficult.

Perhaps, it would be possible to add an option to overwrite this offset.

**Comment by jkhenning** [comment]
Hi @crazyfrogspb ,

Thanks for the issue. As discussed in the Slack thread, we'll add a new `Task.init()` argument to instruct ClearML **not** to add the last iteration count to the reported iteration number when resuming a task.

We'll update here when it's in 🙂

**Comment by jkhenning** [comment]
@crazyfrogspb just to make sure, how do you call `Task.init()` in this task right now? Can you share the code snippet?

**Comment by crazyfrogspb** [comment]
```
import argparse
import time
from datetime import datetime

import tzlocal
from clearml import Task
from clearml.backend_interface.session import SendError


def create_parser():
    parser = argparse.ArgumentParser(description="Monitor ClearML task (MMG)")

    parser.add_argument("--task_id", type=str, required=True)
    parser.add_argument("--sleep_time", type=float, default=30.0)
    parser.add_argument("--restart_if_aborted", action="store_true")
    parser.add_argument(
        "--freeze_timeout", type=float, default=600.0, help="restart task if it has not been updated for this time"
    )

    return parser


def check_if_frozen(task, freeze_timeout):
    local_timezone = tzlocal.get_localzone()
    last_updated = task.data.last_update.astimezone(local_timezone)
    frozen_for = (datetime.now() - last_updated.replace(tzinfo=None)).seconds

    return frozen_for >= freeze_timeout


def monitor_task(args):
    restart_statuses = ["failed", "stopped"] if args.restart_if_aborted else ["failed"]
    while True:
        task = Task.get_task(task_id=args.task_id)
        status = task.get_status()
        if status in restart_statuses or (
            args.freeze_timeout and status == "in_progress" and check_if_frozen(task, args.freeze_timeout)
        ):
            print(
                f"Something is wrong. Task status is {status}, it has been frozen for {check_if_frozen(task, args.freeze_timeout)} seconds"
            )
            if task.models["output"]:
                for model in task.models["output"]:
                    if "_last" in model.url:
                        task.mark_started()
                        task.set_parameters_as_dict(
                            {
                                "General": {
                                    "checkpoint_file": model.url,
                                }
                            }
                        )
                        task.set_initial_iteration(0)
                        try:
                            Task.enqueue(task=task, queue_name=task.data.execution.queue)
                            print("Task was successfully requeued")
                        except SendError:
                            # if task is already queued, this error is raised
                            pass
            else:
                queue_name = task.data.execution.queue
                task.reset()
                Task.enqueue(task=task, queue_name=queue_name)
                print("Task was successfully restarted")
        else:
            print(f"Task status is {status}")
            time.sleep(args.sleep_time)


if __name__ == "__main__":
    parser = create_parser()

    args = parser.parse_args()

    monitor_task(args)

```

**Comment by jkhenning** [comment]
Thanks! 🙂

**Comment by jkhenning** [comment]
@crazyfrogspb I think that meanwhile, as a workaround you can add:

```python
task.set_initial_iteration(0)
```

in the actual task itself (i.e. the one running on a spot)

**Comment by crazyfrogspb** [comment]
nice, will try today

**Comment by crazyfrogspb** [comment]
didn't work =( still getting the same results

**Comment by bmartinn** [comment]
Okay quick update , the following hack/fix will set the initial offset to 0 (source [slack channel](https://clearml.slack.com/archives/CTK20V944/p1638123435134000?thread_ts=1638086294.125800&cid=CTK20V944))
```python
Task._report_subprocess_enabled = False
task = Task.init(...)
task.set_initial_iteration(0)
```

Now for the real fix, I'm thinking OS environment or passing a special value to [continue_last_task](https://github.com/allegroai/clearml/blob/b3a2b3425c5098ebfc0598c9dfb3e670d4a87706/clearml/task.py#L202) in `Task.init` , something like:
`continue_last_task='disable_initial_iteration_offset'`
wdyt?

**Comment by crazyfrogspb** [comment]
I'm really excited for this hack =)

with regard to how implement it, I don't really have a strong preference, but it would be great if I could control it from the script that monitors task status

**Comment by bmartinn** [comment]
Hi @crazyfrogspb 
A fix was pushed, can you verify with the latest version 
```
pip install git+https://github.com/allegroai/clearml.git
```

Now we can override the initial offset :)
```python
from clearml import Task
...
task = Task.init(..., continue_last_task=0, reuse_last_task_id='<task_id_here>')
```

**Comment by crazyfrogspb** [comment]
in the code above, do I simply need to replace `task = Task.get_task(task_id=args.task_id)` with `task = Task.init(continue_last_task=0, reuse_last_task_id=args.task_id)`?

**Comment by jkhenning** [comment]
Hi @crazyfrogspb,

> in the code above, do I simply need to replace task = Task.get_task(task_id=args.task_id) with task = Task.init(continue_last_task=0, reuse_last_task_id=args.task_id)?

Yes, indeed.
By the way, we release a new RC version `1.1.5rc3` a few days ago, can you verify this works for you now?

**Comment by crazyfrogspb** [comment]
maybe I'm misunderstanding something, but this doesn't quite do what I'm trying to achieve in my monitoring script. if I use Task.init in my monitoring script, it resets the task (for example, installed packages section) and start logging script's output.

**Comment by jkhenning** [comment]
@crazyfrogspb thats' what will happen when you run it locally, but how do you continue running it again? locally as well?

**Comment by crazyfrogspb** [comment]
at this point my experiments are running on EC2 spot instances, but the monitoring script is run locally. previous hack/fix worked perfectly for this scenario

**Comment by jkhenning** [comment]
Closing this issue. Please reopen if required.
