### ISSUE TITLE
MinIO supported on port 9000 only

### ISSUE THREAD

**Issue by valeriano-manassero** [allegroai/clearml#498]
It looks it's not possible to setup MinIO with TLS to be used as Storage end; looking at the code I see there is a check about url containing `:9000` and setup host in case it's there. If not host is not set assuming it's AWS.

https://github.com/allegroai/clearml/blob/9527b2ca0318b493462e9f1e6c436fb4462e3459/clearml/backend_config/config.py#L397

I think this is a big limitation, especially in arigapped environments where a lot of MinIO installations are used and exposed on port 443 with TLS enabled.

If I will have some spare time I can try to issue a PR for this.

**Comment by bmartinn** [comment]
Hi @valeriano-manassero 
You need to specify `secure: true` here:
https://github.com/allegroai/clearml/blob/9527b2ca0318b493462e9f1e6c436fb4462e3459/docs/clearml.conf#L101

You also need to make sure you still have the port specified here 
(even if this is the default SSL/TLS port, for example: `host: "my-minio-host:443"`)
https://github.com/allegroai/clearml/blob/9527b2ca0318b493462e9f1e6c436fb4462e3459/docs/clearml.conf#L97

Finally when you setup the `default_output_uri`, or `files_server` in the `clearml.conf`, or when passing `output_uri`  to `Task.init(...)`, you need to specify the port:

```
sdk.development.default_output_uri: "s3://my-minio-host:443/bucket/"
```

**Comment by valeriano-manassero** [comment]
Hi @bmartinn ,
ty for pointing me on the right direction; I was already using `secure` true but I was missing to declare port and I saw in the logs ClearML was trying to contact AWS.

If I can suggest, maybe we can improve a bit the docs so it's clear that using a custom endpoint (like MinIO) requires to always declare the port in url.

**Comment by bmartinn** [comment]
> If I can suggest, maybe we can improve a bit the docs so it's clear that using a custom endpoint (like MinIO) requires to always declare the port in url.

Yes we totally should :) 
Do you have a specific suggestion on where to add this information ?  (maybe [here](https://clear.ml/docs/latest/docs/integrations/storage#configuring-aws-s3))

**Comment by valeriano-manassero** [comment]
> Do you have a specific suggestion on where to add this information ?  (maybe [here](https://clear.ml/docs/latest/docs/integrations/storage#configuring-aws-s3))

I can issue a PR on https://github.com/allegroai/clearml-docs/blob/main/docs/integrations/storage.md if it's ok for you.
