### ISSUE TITLE
Default AMI Id for AWS Autoscaler does not exist

### ISSUE THREAD

**Issue by johnmccain** [allegroai/clearml#506]
The default AMI Id for the AWS Autoscaler (`ami-04c0416d6bd8e4b1f`) does not appear to exist as a public image in AWS. Trying to use the default will result in an error when attempting to spin up a new instance:

```
Error: Failed to start new instance, An error occurred (InvalidAMIID.NotFound) when calling the RunInstances operation: The image id '[ami-04c0416d6bd8e4b1f]' does not exist

```

Is there a new recommended AMI Id?

**Comment by johnmccain** [comment]
Correction, it looks like an AMI with that id does exist but only in us-east-1. Could we add a note in the documentation regarding the region-specific nature of the default AMI?

**Comment by ainoam** [comment]
@johnmccain The coupling of an AMI ID to an AWS region is an AWS EC2 staple. Which part of the documentation did you follow that you feel would have benefited such a note?

**Comment by johnmccain** [comment]
A note on [this page](https://clear.ml/docs/latest/docs/guides/services/aws_autoscaler/) mentioning the name of the recommended AMI would be helpful--I just had a bit of trouble finding the correct AMI for my region at first since I did not know which region the default was associated with. The matching AWS region is shown as a default in the autoscaler setup process, so that's partly on me for not digging enough first.
