### ISSUE TITLE
Bug in the debug samples with auto-refresh

### ISSUE THREAD

**Issue by H4dr1en** [allegroai/clearml#512]
Hi, 

There is a small bug with auto-refreshing in the DEBUG SAMPLES Tab of the Web UI:
If it is ON, then it will always force the first series to be displayed, regardless of what has been selected by the user.

Eg: If I have two Metrics, say `Metric_1` and `Metric_2` , I compare two experiments, go to debug sample, turn auto-refreshing ON, for one of the two experiments, I switch from `Metric_1` to `Metric_2` , then as soon as the auto-refreshing happens, the debug samples from the `Metric_1` will be shown for both experiments, even if I still see `Metric_2` as the one selected

Reported version in the Web UI > Profile: ` 1.1.1-135 • 1.1.1 • 2.14`

**Comment by jkhenning** [comment]
Hi @H4dr1en,

Thanks for reporting this - we'll add it to the Bugs TODO list :)

**Comment by jkhenning** [comment]
Closing this as this was already released. Please reopen if required.
