### ISSUE TITLE
Bad Request when authenticating to ClearML server

### ISSUE THREAD

**Issue by mmiller-max** [allegroai/clearml#517]
### Summary

I'm getting a bad request error (400) when trying to connect to a self hosted server via the python API. I've traced it down to the `Content-Length` header. If I set it to `0` or remove it the request is successful, but otherwise it is set to 2 and the request fails. I believe the root cause is this line:

https://github.com/allegroai/clearml/blob/fd2d6c6f5d46cad3e406e88eeb4d805455b5b3d8/clearml/backend_api/session/session.py#L710

Replacing the default argument with `None` like below ensures that the `Content-Length` header is set correctly and works for the request in question, but seems to break other things (I'll keep looking).

```python
data = {"expiration_sec": exp} if exp else None
```

Unfortunately the error is not repeatable on the ClearML community server (I'm not sure why!) so hard to provide a MWE.

### What I did

Set the environment variables `CLEARML_API_ACCESS_KEY`, `CLEARML_API_SECRET_KEY`, `CLEARML_API_HOST`, `CLEARML_WEB_HOST`, `CLEARML_FILES_HOST` to connect to my self-hosted server (which is running v1.1.0 as 1.1.1 is not available in the GCP Images yet).

Attempt to connect via:

```python
from clearml import Task
project = "ProjectName"
Task.get_tasks(project_name=project))
```

And get this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/experiment-test-qPFpYaQg-py3.9/lib/python3.9/site-packages/clearml/task.py", line 847, in get_tasks
    return cls.__get_tasks(task_ids=task_ids, project_name=project_name, tags=tags,
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/experiment-test-qPFpYaQg-py3.9/lib/python3.9/site-packages/clearml/task.py", line 3535, in __get_tasks
    for task in cls._query_tasks(project_name=project_name, task_name=task_name, **kwargs)]
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/experiment-test-qPFpYaQg-py3.9/lib/python3.9/site-packages/clearml/task.py", line 3553, in _query_tasks
    cls._get_default_session(),
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/experiment-test-qPFpYaQg-py3.9/lib/python3.9/site-packages/clearml/backend_interface/base.py", line 101, in _get_default_session
    InterfaceBase._default_session = Session(
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/experiment-test-qPFpYaQg-py3.9/lib/python3.9/site-packages/clearml/backend_api/session/session.py", line 201, in __init__
    self.refresh_token()
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/experiment-test-qPFpYaQg-py3.9/lib/python3.9/site-packages/clearml/backend_api/session/token_manager.py", line 112, in refresh_token
    self._set_token(self._do_refresh_token(self.__token, exp=self.req_token_expiration_sec))
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/experiment-test-qPFpYaQg-py3.9/lib/python3.9/site-packages/clearml/backend_api/session/session.py", line 739, in _do_refresh_token
    six.reraise(*sys.exc_info())
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/experiment-test-qPFpYaQg-py3.9/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/experiment-test-qPFpYaQg-py3.9/lib/python3.9/site-packages/clearml/backend_api/session/session.py", line 725, in _do_refresh_token
    raise LoginError(
clearml.backend_api.session.session.LoginError: Failed getting token (error 400 from https://api.cleaml.mydomain.com): Bad Request
```

### Setup

```
clearml==1.1.4
$ python --version
Python 3.9.9
```

**Comment by jkhenning** [comment]
Hi @mmiller-max ,

That's super strange :)

Since the open community server and the open source server are very similar with regard to API serving, I'm really struggling to understand the root cause for this. Are you sure this is not something related to some network components between you and your server? Can you try doing the same but from the server machine itself?

In any case, I'll try to reproduce with a local server.

**Comment by mmiller-max** [comment]
Hi @jkhenning, thanks for getting back to me!

> Are you sure this is not something related to some network components between you and your server?

After a bit more digging, it seems like the api endpoint (or something along way) doesn't accept any `GET` requests where the `Content-Length` header is greater than 0.

> Can you try doing the same but from the server machine itself?

Will give it a go!

**Comment by mmiller-max** [comment]
Yep, changing the request to POST does fix it. For the auth login just changing the default for `_send_request` worked, but for the example above I can't find where the method is set - I've tracked it as far as `https://github.com/allegroai/clearml/blob/fd2d6c6f5d46cad3e406e88eeb4d805455b5b3d8/clearml/backend_api/session/session.py#L554`.

**Comment by jkhenning** [comment]
It's actually set by `action=req_obj._action`

**Comment by mmiller-max** [comment]
When debugging the example above, `req_obj._action` was equal to `get_all` whereas `req_obj._method` was equal to `get`.

I modified this line

https://github.com/allegroai/clearml/blob/cf9671c2539c05dac40c00ef707193b1ca6b9cab/clearml/backend_api/session/request.py#L11

To be `_method = 'post'` which in turn changes `req_obj._method` to be `post` and `get_tasks` now works correctly

Are they any potential downsides to setting this to POST?

**Comment by jkhenning** [comment]
Sorry, my bad, I mean `method` indeed 🙂

**Comment by jkhenning** [comment]
> Are they any potential downsides to setting this to POST?

Not really, this can be configured per-endpoint

**Comment by mmiller-max** [comment]
> this can be configured per-endpoint

Great! Is this something that's possible to do in the user config?

Just wondering what the best way to proceed with this is, or if ultimately it needs a new version released?

**Comment by jkhenning** [comment]
The best way is a PR, so we can push an RC quickly :)

However, your original issue was with the `auth.login` call - this issue will affect all calls, and that's something I'm more reluctant to change (as different call methods might affect error handling and resending)

Maybe the quickest thing to do it figure out what's blocking the GET requests from sending a payload?

**Comment by mmiller-max** [comment]
OK sure. I'll push up a PR which gets me working and will let you do any further tests, and will see what I can do on my end to get the payload sent through.

For the `auth.login` call, could we add the kwargs to where `_send_request` is called in `_do_refresh_token` so it only affects that? Or is affecting that what you're concerned about?

E.g.

```python
res = self._send_request(
    service="auth",
    action="login",
    auth=auth,
    json=data,
    headers=headers,
    method='post',
    refresh_token_if_unauthorized=False,
)
```

**Comment by mmiller-max** [comment]
> It's the majority of the other calls I'm worried about :)

Is it a change that can be tested and demonstrated to be OK and therefore would be likely to make it into a release, or do you think it's too big a change? (Perhaps an env var is a nice solution to this too, at least as a development feature)

**Comment by jkhenning** [comment]
> Is it a change that can be tested and demonstrated to be OK and therefore would be likely to make it into a release, or do you think it's too big a change?

Since this has to do with how load-balancers handle these requests and how resends are handled on the client side (by Python's requests package etc.), it seems like a relatively big change, one I wouldn't want to push right now...

> Perhaps an env var is a nice solution to this too, at least as a development feature

That's a really good idea! Since my main concern is production use and stability - having this kind of override that can be enabled in development (or even in production, if you so choose, under the current "disclaimer") is a very good solution - would you like to PR it? 🙂

**Comment by mmiller-max** [comment]
> it seems like a relatively big change, one I wouldn't want to push right now...

Makes sense yep.

> would you like to PR it?

Yes I'll get one ready!

Thanks for your quick response with this, really appreciated 👍
