### ISSUE TITLE
Wrong series names for bar plot (matplotlib)

### ISSUE THREAD

**Issue by esthergold** [allegroai/clearml#518]
When using clearml automatic reporting of matplotlip plots, label and color are not propagated to clearml UI.

For example:
```
import matplotlib.pyplot as plt
plt.bar([1, 2, 3], [1, 2, 3], 0.5, label="label 1", color="blue")
plt.legend()
plt.show()
```
The created plot in python:
![image](https://user-images.githubusercontent.com/25911143/146779578-21d9d039-c4e4-4365-b5ca-91224a87342e.png)
While in clearml:
![image](https://user-images.githubusercontent.com/25911143/146779622-e22db6bb-af8d-44c5-8d8f-8aa69df7d31d.png)

**graph.metric 0** is presented instead of **label 1**.

**Comment by jkhenning** [comment]
Hi @esthergold,

Thanks for reporting this. We'll take a look - I think it has something to do with the ClearML WebApp overriding some of your settings.

**Comment by esthergold** [comment]
Thank you!

**Comment by jkhenning** [comment]
Hi @esthergold, closing this. Please re-open if required.
