### ISSUE TITLE
Run HPO completely locally

### ISSUE THREAD

**Issue by thepycoder** [allegroai/clearml#520]
When running an HPO task, I can run the optimizer task itself in my local environment, but I seem to have no choice but to run a separate agent to actually process the resulting training tasks.
This seems like overkill for someone without access to multiple machines and just adds overhead by recreating the environment again.

There already exists a `LocalClearmlJob` job type that we could use for this functionailty.
https://github.com/allegroai/clearml/blob/fd2d6c6f5d46cad3e406e88eeb4d805455b5b3d8/clearml/automation/job.py#L573

So maybe we should have it as an argument when calling `optimizer.start()`? That would make most sense.

I'm starting work on a PR for this.

**Comment by jkhenning** [comment]
Done
