### ISSUE TITLE
[Feature Requests] [WebUI] Experiment comparison and more

### ISSUE THREAD

**Issue by idantene** [allegroai/clearml#529]
Hey ClearML team! Hope you all had a great start for the new year :)
I have not scanned the current issues, so if any of the following suggestions are already reported - my apologies.

Over the last couple of weeks I've been experimenting and enjoying ClearML, and have found some UI suggestions that I think would be great to have and hopefully require minimal effort.

1. Allow filtering by project in the "All Experiments" project, it would be great if one could also filter by the project, just like filtering by tags (notice the lack of a funnel icon next to _PROJECT_) :
![image](https://user-images.githubusercontent.com/12184618/147890332-2347457f-0ee2-4762-98a0-dfba4ddf1f70.png)
2. In the "Compare Experiments" page, when adding experiments to comparison via the "Add Experiments" button, the columns are not adjustable (and one cannot filter in that view). For nested projects, this can be a nuisance since you can't see the relevant project. It would be great to be able to adjust column widths and be able to filter, similar to the experiments table.
![image](https://user-images.githubusercontent.com/12184618/147890399-cdddd42b-0488-4660-a59c-2526b2788214.png)
3. On that note, it would be nice to have a quick link in the sidebar for an empty experiment comparison page, where one could just add the desired experiments. The use case would be to add experiments from different projects.
    - Similarly, it would be nice if one could choose multiple experiments from different projects in the experiments table, "add to cart", and compare. In other words, something along this flow: navigate to project a, select N tasks for comparison, click "add to comparison", navigate to project b, select M tasks for comparison, click "add to comparison" or "compare with cart", etc.
4. Last but not least, when navigating with nested projects, it would be nice to have the "one level up" clickable somewhere. Currently one cannot navigate one level up because all N levels are collapsed to the three dots:
![image](https://user-images.githubusercontent.com/12184618/147890493-9ba91dc1-ef56-42aa-94c4-6158ebc6358e.png)
There are many ways to go about this of course, some of the UI ideas that come to mind:
    - Perhaps the easiest, show the project name immediately above the current one so it's clickable, i.e. `PROJECTS > ... > sub_test > subsub_test`
    - Alternatively, just stick a one-folder-up icon
    - Nautilus has forward and backward icons to go between hierarchy

Thanks!

**Comment by ainoam** [comment]
@idantene 

> I have not scanned the current issues, so if any of the following suggestions are already reported - my apologies.

No worries :) Always happy to get more feedback!!

> Allow filtering by project in the "All Experiments" project

Makes a lot of sense - Should be easy to add a filter to the "Project" column in one of the near versions.

> In the "Compare Experiments" page, when adding experiments to comparison via the "Add Experiments" button .... It would be great to be able to adjust column widths and be able to filter, similar to the experiments table.

We've noticed. This is coming in the next server release.

> it would be nice if one could choose multiple experiments from different projects in the experiments table...

This "comparison cart" is a great idea - It might have a slightly wider impact in terms of table layout, so I'll make sure it's in the roadmap to be taken into consideration.
Note that comparison across projects is already available as an extension of an existing same-project comparison (i.e. add experiments from different projects), 

> when navigating with nested projects, it would be nice to have the "one level up" clickable somewhere

Definitely agree. We're going to be redoing **WHEN** the `...` menu appears so as to make better use of the available screen width, so for most use cases you'll always see the desired parent available for direct navigation.

**Comment by idantene** [comment]
That is great news @ainoam, can't wait! :)

**Comment by idantene** [comment]
@ainoam any updates on these? I've seen at least (2) has been implemented in 1.2.0, which is great! :D

We've also been discussing internally regarding the experiment comparison, and there's a wide consensus that the "basket idea" or shopping-cart for experiment comparison is probably the best way to go. Being able to right click a task and choose "add to comparison" and then later on view the comparison would be super handy.

**Comment by ainoam** [comment]
@idantene (4) should be coming in the next release (well, as part of the rehaul I mentioned in the previous comment), and I hope that (1) should make it into the release after that.

The "comparison cart" notion is on our list, but somewhat further out.

**Comment by jkhenning** [comment]
Closing this as it was already released. Please reopen if required.
