### ISSUE TITLE
Unable to use ClearML

### ISSUE THREAD

**Issue by LanceKnight** [allegroai/clearml#532]
Hello, 

I suddenly got this error today. I was able to use Clear ML yesterday. I couldn't even visit clear.ml or https://app.community.clear.ml/projects using chrome on my CentOS machine (using firefox is fine on the same machine though). The version of clearml I have is 1.0.2. I didn't make any changes to the clearml. I just found this error when I tried to resume my work from yesterday by just running the codes again.

> WARNING:urllib3.connectionpool:Retrying (Retry(total=239, connect=239, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2ba4a05fed68>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /auth.login
WARNING:urllib3.connectionpool:Retrying (Retry(total=238, connect=238, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2ba4a05fef98>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /auth.login
WARNING:urllib3.connectionpool:Retrying (Retry(total=237, connect=237, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2ba4a0622128>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /auth.login
WARNING:urllib3.connectionpool:Retrying (Retry(total=236, connect=236, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2ba4a0622278>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /auth.login

**Comment by jkhenning** [comment]
Hi @LanceKnight ,

There seems to be some DNS issue from some providers that causes failure in name resolution when accessing clear.ml
I tried changing my DNS provider settings to Google and Cloudflare and both work - can you try that?

**Comment by LanceKnight** [comment]
Hi, @jkhenning,

Thanks for answering. I'm not sure why the problem is mysteriously gone...maybe the system admin did something related to the DNS settings. Thank you anyway!
