### ISSUE TITLE
No unit tests?

### ISSUE THREAD

**Issue by tienduccao** [allegroai/clearml#536]
Hi, I couldn't find any unit tests in this repository :open_mouth: .

**Comment by jkhenning** [comment]
Hi @tienduccao, we do have internal app tests that we run regularly, but we're still behind on unit tests. If you'd like to help, we'd love that 🙂

**Comment by tienduccao** [comment]
Hi @jkhenning , sure I'm happy to help.
Could you help me to identify which modules are the most important to test first?
Thanks.

**Comment by jkhenning** [comment]
Hi @tienduccao , sure! 👍 
IMO the best place to start is with the various bindings, as these are most likely to be affected by changes in 3rd-party libraries

**Comment by tienduccao** [comment]
Cool, I'll take a look and make a PR soon
