### ISSUE TITLE
Plotly express imshow not showing properly in ClearML

### ISSUE THREAD

**Issue by guillaumelorre28** [allegroai/clearml#538]
Hello, I am using imshow from plotly to display a color heatmap. 
https://plotly.com/python-api-reference/generated/plotly.express.imshow.html
Using text_auto=True, the numeric values are displayed in the figure.
However, they do not appear when I report the figure in ClearML using report_plotly.

```python
import numpy as np
from clearml import Task
import plotly.express as px


matrix = np.random.uniform(size=(10, 10))
matrix = np.round(matrix, 2)

fig = px.imshow(matrix, text_auto=True)

fig.show()

task = Task.init(project_name="test", task_name="plotly_figures")
logger = task.get_logger()
logger.report_plotly(title="color_map", series="test", figure=fig)
```
The text is well displayed when using fig.show() but not in the reported figure in ClearML.

Thanks in advance.

**Comment by bmartinn** [comment]
Hi @guillaumelorre28 
Tested with `plotly==5.5.0` and `clearml==1.1.6rc0` this is what I'm getting
Plotly fig show:
![plotly](https://user-images.githubusercontent.com/51887611/149596064-5b419de3-7ad7-4e40-8e92-872d97d43f55.png)
ClearML UI:
![clearml](https://user-images.githubusercontent.com/51887611/149596062-578b391d-0724-48cb-beba-ca9231814a79.png)

Do you mean the the text values inside the matrix cells are missing ?

**Comment by guillaumelorre28** [comment]
Thanks for replicating the problem. Yes, my issue is about the missing text values inside the matrix cells.
I am using it for making a confusion matrix and it is nicer with the values.

**Comment by bmartinn** [comment]
Quick update @guillaumelorre28, the fix will be released in the next `clearml-server` (as this is a front-end UI issue)

**Comment by jkhenning** [comment]
Closing this as it was already released. Please reopen if required.
