### ISSUE TITLE
Probably, incorrect bucket config filtering

### ISSUE THREAD

**Issue by KernelA** [allegroai/clearml#544]
The method `from_list` returns the original list of configurations.
https://github.com/allegroai/clearml/blob/ad735f93e084818a82b5236f9f42411f549338f3/clearml/backend_config/bucket_config.py#L55

But some item may be invalid. Probably, this method must return `valid_configs` instead `configs`:
https://github.com/allegroai/clearml/blob/ad735f93e084818a82b5236f9f42411f549338f3/clearml/backend_config/bucket_config.py#L66

**Comment by erezalg** [comment]
Hi @KernelA! 
ClearML rc was released fixing this issue! install it by running "pip install clearml==1.2.0rc0"
Let us know if it solves the problem :)

**Comment by KernelA** [comment]
I did not have any problems with it, but i noticed this issue when exploring code for working with S3.

**Comment by jkhenning** [comment]
@KernelA in that case, I'll close this issue 🙂 

Thanks for your time!
