### ISSUE TITLE
Problems with poetry and incorrect python version 

### ISSUE THREAD

**Issue by ColdTeapot273K** [allegroai/clearml#549]
Environment:
clearml==1.1.6
clearml-agent==1.1.1
poetry==1.1.12
pyenv==2.2.3
OS==4.14.256-197.484.amzn2.x86_64

---
The problem: 
If I override system python with arbitrary python version using `pyenv` with `pyenv global ...`, and configure `poetry` as package manager in `clearml.conf`, a `clearml-agent` worker can crash on startup because it tries to link to system python, rather than `pyenv` python, which is easily incompatibe with dependencies.

E.g. Amazon Linux 2 standard python is 3.7 while fresh `numpy` requires python 3.9:

![image](https://user-images.githubusercontent.com/54956904/150486000-fca0da0b-0f69-4a1e-af1c-abbc40cbe4b5.png)

This is not solved by pointing `python_binary:` in `clearml.conf` to the `pyenv` python binary explicitly, see https://github.com/allegroai/clearml/issues/523#issuecomment-1017218754

---
Solution:

I've tracked the issue to `poetry` repo, e.g. https://github.com/python-poetry/poetry/issues/4199, https://github.com/python-poetry/poetry/pull/4852 among others. The problem is, `poetry` with the new installer (`install-poetry.py`) doesn't respect `pyenv global` setting untill explicitly told to use that python in the current session via `poetry use ...`. 
Now, we cannot explicitly add any shell commands on `clearml-agent` startup (`poetry use ...`) unless we use `docker` (at least i didn't found any other way). 
And `poetry` + `docker` don't play together well (besides `docker` would be overkill to use for any task). 

What can be done is:
1. either using unstable `poetry 1.2` patched with https://github.com/python-poetry/poetry/pull/4852
2. or, more stable way - use `poetry` installed with deprecateed installer (the `get-poetry.py`, not the `install-poetry.py`)

Maybe add some note to `clearml` docs?

**Comment by jkhenning** [comment]
Hi @ColdTeapot273K,

Thanks for sharing such a detailed description and possible solutions 👍 

> Maybe add some note to clearml docs?

I think the FAQ is a good place to start, WDTY?

**Comment by ainoam** [comment]
@ColdTeapot273K I've taken the liberty to add your comments [here](http://localhost:3000/docs/clearml_agent#poetry-mode), Makes sense?
