### ISSUE TITLE
Main/Master Branch Pickup

### ISSUE THREAD

**Issue by samsipe** [allegroai/clearml#551]
When running a ClearML task on a GitHub repo with a `main` default branch vice a `master` default branch, the checkout will fail, unless the `main` branch or a commit or tag is specified. 

```
clearml-task --project asdf --name asdf --repo https://github.com/asdf/asdf.git --script asdf/asdf.py --queue default
```
results in:
```
Repository cloning failed: Command '['git', 'checkout', 'origin/master', '--force']' returned non-zero exit status 1.
```
unless `--branch main` is added explicitly. Just thought it might be good to fix since `main` is the new `master`.

**Comment by jkhenning** [comment]
Hi @samsipe ,

What happens when you simply try `git clone https://github.com/asdf/asdf.git` on a new clean setup (i.e. with no special git configuration)?

**Comment by samsipe** [comment]
The usual expected behavior. This is just a normal private GitHub repository with a `main` default branch instead of a `master` default branch since it was made recently.

**Comment by jkhenning** [comment]
Well, actually ClearML doesn't specify which branch, and lets Git/GH decide, which is why I asked... Are you sure you're running this test on the same machine? I assume the task is picked up by a ClearML Agent - where is the agent running?

**Comment by samsipe** [comment]
Are you certain? I just ran a junk task against the clear ml docs repo which has a `main` default branch and got the same error.

```
$ clearml-task --project asdf --name remote_test --repo https://github.com/allegroai/clearml-docs.git --script asdf/asdf.py --queue default
```
> yes, I know asdf/asdf.py doesn't exist but it doesn't even get to that script being called

```
Executing task id [56304bb5d7fb4864b7efa6fd71c45848]:
repository = https://github.com/allegroai/clearml-docs
branch = 
version_num = 
tag = 
docker_cmd = nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04
entry_point = amplify/train.py
working_dir = .

created virtual environment CPython3.8.10.final.0-64 in 279ms
  creator CPython3Posix(dest=/root/.clearml/venvs-builds/3.8, clear=False, no_vcs_ignore=False, global=True)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==21.3.1, setuptools==60.2.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator


cloning: https://github.com/allegroai/clearml-docs

1643058209463 alienware-clearml:gpu0 DEBUG 
error: pathspec 'origin/master' did not match any file(s) known to git
Repository cloning failed: Command '['git', 'checkout', 'origin/master', '--force']' returned non-zero exit status 1.

clearml_agent: ERROR: Failed cloning repository. 
1) Make sure you pushed the requested commit:
(repository='https://github.com/allegroai/clearml-docs', branch='', commit_id='', tag='', docker_cmd='nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04', entry_point='amplify/train.py', working_dir='.')
2) Check if remote-worker has valid credentials [see worker configuration file]


1643058209661 alienware-clearml:gpu0 DEBUG Process failed, exit code 1
```

You can even see where it's trying to call `master`

```
'['git', 'checkout', 'origin/master', '--force']'
```

The only other thing I can think is that it's use an older `git` version that's in the container `nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04` but it also failed with `--docker ubuntu:latest`.  

Can someone try and reproduce this please?

**Comment by jkhenning** [comment]
Hi @samsipe, it seems you're right... Since GitHub supports both `master` and `main` (and `master` is still used in most other places), I think we'll add some logic that simply detects such an issue with `master` and retries with `main`.

Meanwhile, is the `--branch main` fix good enough for you? If not, you're more than welcome to add an env var that allows overriding the default Git branch name, at least until we'll add the proper retry feature...

**Comment by samsipe** [comment]
`--branch main` is totally fine with me, I just pulled my hair out troubleshooting what I thought was a git permission issue, before I realized it was the `main`/`master` thing. 

So adding a note to the docs for now or even just recommending to include a `--branch` for now would be more than enough I think.

**Comment by ainoam** [comment]
@samsipe Would you say [this note](https://github.com/allegroai/clearml-docs/blob/main/docs/apps/clearml_task.md#branch-and-working-directory) would cover it?

**Comment by samsipe** [comment]
I think that's helpful! And it's nut just GitHub, it's all of Git since `Git 2.28.0` I think. So I would certainly update that eventually for anyone that won't dig that deep into the docs. 

I might update your [example](https://clear.ml/docs/latest/docs/guides/clearml-task/clearml_task_tutorial) with `--branch master` and your note from above too for now too so it's clear to folks that land there as well.

Also, since I have you, thanks for building ClearML. It has been very helpful for me so far in a project I am work on! 

Feel free to close this issue.

**Comment by jkhenning** [comment]
Hi @samsipe,

We've just released ClearML Agent v1.2.0rc2 that should take care of this issue - feel free to try it out and let us know if it works 🙂

**Comment by samsipe** [comment]
Awesome, thanks for reaching out, I will take a look.

**Comment by jkhenning** [comment]
Hi @samsipe, closing this. Please re-open if required.
