### ISSUE TITLE
Provide option auto_delete_file to Task.update_output_model

### ISSUE THREAD

**Issue by 421psh** [allegroai/clearml#554]
Hi!

Please provide the option `auto_delete_file` to `Task.update_output_model`.  I have a need to save model weights both remotely and locally. However, now it is not so conveniently configured. I have to create an instance of the `OutputModel` class and call the method `update_weights` with` auto_delete_file=True`, although this is already done in `Task.update_output_model`.

**Comment by jkhenning** [comment]
Hi @421psh ,

Are you using any framework or doing all of this manually?

**Comment by 421psh** [comment]
Basically, I use Pytorch-lightning. There are no problems with it, all savings are auto-magical. But I faced this issue when I was developing my custom service for TensorRT model conversion.

**Comment by jkhenning** [comment]
I seem but when you call `Task.update_output_model()` it calls `update_weights()` and the default there is `auto_delete_file=True` - do you need to be able to specify `auto_delete_file=False`?

**Comment by 421psh** [comment]
Exactly, I want `auto_delete_file=True` **not** to be hard-coded in `Task.update_output_model()` method.

**Comment by jkhenning** [comment]
Great, I'll push this commit soon and it'll be available in the next RC.
