### ISSUE TITLE
how to avoid label text crop when hover?

### ISSUE THREAD

**Issue by davidenitti** [allegroai/clearml#562]
When I hover a scalar plot the name of the label is cropped e.g. name_loss_l1 becomes name_loss... 
is it possible to avoid to the crop and visualize the full label?
thanks

**Comment by ainoam** [comment]
@davidenitti Are these scalar plots under "Results>Scalars" or "Results>Plots" (in other words, how did you generate these plots)?

**Comment by davidenitti** [comment]
"Results>Scalars"

**Comment by ainoam** [comment]
@davidenitti In this case, there's currently no way around it at this time.

Thanks for pointing it out - We'll try to look into ways to improve this in coming releases.

**Comment by davidenitti** [comment]
thanks, is there a way to modify the server/client to fix this? can you point the line of code that does the crop? if it's just a few line of code I can do it myself

**Comment by shyallegro** [comment]
Hi @davidenitti,
these graphs get rendered using plotly.js, it might be possible to setup plotly better, maybe using the hovertexttemplate property.
the [code is here](https://github.com/allegroai/clearml-web/blob/master/src/app/webapp-common/shared/experiment-graphs/single-graph/single-graph.component.ts)

**Comment by shayh** [comment]
@davidenitti 
maybe defining a hover template, as describe [here](https://plotly.com/python/hover-text-and-formatting/) might solve the issue

**Comment by shyallegro** [comment]
@davidenitti
maybe defining a hover template, as describe [here](https://plotly.com/python/hover-text-and-formatting/) might solve the issue
but since this is scalar it will have to be done in the UI, probably in single-graph.component.ts

**Comment by davidenitti** [comment]
@shyallegro I still don't understand how to fix this, and what to change exactly and where.
I also found this solution https://github.com/getredash/redash/pull/5661/commits/860a44562c362f7bd3b2cf7ad8e2453992442702#diff-9c860ef60adbf48838674a87c7681f2c35e8c55ac4175e624708cba367c4a833

but I still don't know what to apply it in the code.

**Comment by davidenitti** [comment]
@shyallegro  so I fixed adding
hoverlabel: {    namelength: -1,       },
after line 229 and before 230
in this file src/app/webapp-common/shared/experiment-graphs/single-graph/single-graph.component.ts

the only issue now is that the text is divided in many lines making the textbox big in height.
do you know how to increase the width limit in some way (not sure it's the issue)? or avoid the text division?
I won't bother any more!
thank you very much

**Comment by shyallegro** [comment]
@davidenitti 
I don't know how to increase the width, we'll try to investigate further.
in the mean time I guess having a high box is better then not being able to read the text, if you like send us a pull request and we'll add your code.

**Comment by jkhenning** [comment]
Closing this issue. Please reopen if required.
