### ISSUE TITLE
Documentation: seaborn plot reporting is not demonstrated

### ISSUE THREAD

**Issue by noamsgl** [allegroai/clearml#570]
Hi and thanks for your wonderful product!

In this example script, you claim to demonstrate seaborn plot reporting but you don't show it.

https://github.com/allegroai/clearml/blob/d53dbbf697ad67b23e66d7979b3598d69a42e3ee/examples/reporting/matplotlib_manual_reporting.py#L1

**Comment by ainoam** [comment]
@noamsgl Thanks for noticing. We'll make sure rectify the situation and update here.
In the meantime, notice that that ClearML does automatically capture seaborn plots (see [here](https://github.com/allegroai/clearml/blob/8658198f8bac976e5c2766190d8c593c2308bfa1/examples/frameworks/matplotlib/matplotlib_example.py)) - What exactly do you need?

**Comment by noamsgl** [comment]
No further comments.
