### ISSUE TITLE
Reseting os.fork after task closing

### ISSUE THREAD

**Issue by razmikmelikbekyan** [allegroai/clearml#605]
In `clearml/binding/environ_bind.py` os.fork is patched. After the current experiment is finished and I am calling `task.close()`

After that, I continue my code with some other staff and use some multiprocessing which fails, since os.fork is patched and task is closed. So I have an error `AttributeError: 'NoneType' object has no attribute '_report_subprocess_enabled'` that is coming from `clearml/binding/environ_bind.py:89` since the main task is None.

**Comment by jkhenning** [comment]
Hi @razmikmelikbekyan,

We've just pushed a fix for this issue, you can try using clearml from the main branch to see if it works for you. An RC (followed by an official v1.3.1 release) will be released soon 🙂

**Comment by razmikmelikbekyan** [comment]
Maybe it is better to recover fully `os.fork` - doing unpatch actually.

**Comment by jkhenning** [comment]
Hi @razmikmelikbekyan, as v1.3.1 is out, can you please confirm this solves the issue?

**Comment by razmikmelikbekyan** [comment]
It works, the issue can be closed. Thanks.
