### ISSUE TITLE
how to ignore the artifacts (models, etc...)?

### ISSUE THREAD

**Issue by davidenitti** [allegroai/clearml#617]
I load and save models and batches during training and I don't want clearml to log them?
how to make clearml ignore those?
thanks

**Comment by eugen-ajechiloae-clearml** [comment]
Hi @davidenitti. You could use [WeightsFileHandler.add_pre_callback](https://github.com/allegroai/clearml/blob/c58e8a4c6a1294f8acec6ed9cba81c3b91aa2abd/clearml/binding/frameworks/__init__.py#L111) to add a callback on save that would filter the models logged.
As a side-note, in a version we will release soon, you will be able to specify a wildcard string to match the names of the models you want to log to ClearML and filter out those that don't match that string.

**Comment by davidenitti** [comment]
can you make me an example?
thanks!

**Comment by eugen-ajechiloae-clearml** [comment]
@davidenitti Sure. Here is a minimal example you could run:

```py
from clearml import Task
from clearml.binding.frameworks import WeightsFileHandler
import torch


def filter_callback(
    callback_type: WeightsFileHandler.CallbackType,
    model_info: WeightsFileHandler.ModelInfo,
):
    print(model_info.__dict__)
    if (
        callback_type == WeightsFileHandler.CallbackType.save
        and "filter_out.pt" in model_info.local_model_path
    ):
        return None
    return model_info


if __name__ == "__main__":
    Task.init(project_name="example", task_name="filter out")
    WeightsFileHandler.add_pre_callback(filter_callback)
    filter_out_model = torch.nn.Module()
    dont_filter_out_model = torch.nn.Module()
    torch.save(filter_out_model, "filter_out.pt")
    torch.save(dont_filter_out_model, "dont_filter_out_model.pt")
```

**Comment by davidenitti** [comment]
thanks the script works, but my it does not seem to work on my training.
does it work then I use Task.create or Task.get_task?
do I have to use in any python script is imported and which uses torch.save?

**Comment by davidenitti** [comment]
thanks
