### ISSUE TITLE
Pipeline Page: step blocks disappeared

### ISSUE THREAD

**Issue by IlyaMescheryakov1402** [allegroai/clearml#618]
Step blocks disappear after 5 minutes of calculations or after changing the status of the 2nd step
![image](https://user-images.githubusercontent.com/58298387/159688710-a80c00a5-f3de-44ec-bf02-cd584981ad4a.png)

**Comment by oren-allegro** [comment]
Hi @IlyaMescheryakov1402,

Few questions:
- Is this reproducible? i.e. does it happen every time you run the pipeline?
- Does refreshing the browser (F5) resolve this?
- Does anything happen when you press on details?

**Comment by IlyaMescheryakov1402** [comment]
Hi @oren-allegro 

0. Yes. Every pipeline with 2 or more steps crashes
1. No
2. Terminal with pipeline logs appears. It has no effect on pipeline graph - it's still invisible :(

**Comment by oren-allegro** [comment]
@IlyaMescheryakov1402 - my assumption is that something is incorrect in the pipeline configuration - causing the web app to fail displaying it.
Can you please share the configuration of the pipeline?
You can do this by clicking on the "Run Info" (on the right), the choose "Full details" - this should open the controller experiment in a new tab. There go to "Configuration" tab, and select "Pipeline" from the configuration objects on the left. Copy and send it (of course, remove any personal info).

**Comment by IlyaMescheryakov1402** [comment]
@oren-allegro 

Here is my pipeline configuration

[config_pipeline.txt](https://github.com/allegroai/clearml/files/8334194/config_pipeline.txt)

**Comment by IlyaMescheryakov1402** [comment]
Hi @oren-allegro 

This bug was solved by changing the order of steps import if pipeline scrips

**Now, to see your pipeline steps, you need to import step-scripts in right order (i.e. in the order in which scripts are run)**

**Comment by oren-allegro** [comment]
Thanks @IlyaMescheryakov1402  - indeed seems to be a bug in the user interface. Should be fixed for the next version.

**Comment by shyallegro** [comment]
@IlyaMescheryakov1402 - if you need a workaround in the mean time, order the steps from parents to children.
