### ISSUE TITLE
It is impossible to make hyper parameters section in pipeline

### ISSUE THREAD

**Issue by IlyaMescheryakov1402** [allegroai/clearml#629]
How can I add hyper parameter section like "custom_field" on pic below?
![image](https://user-images.githubusercontent.com/58298387/161090497-8217c46f-8683-4b30-b0a0-bdbb2d8e1e21.png)

but for the pipeline on decorators?

I have too much hyper params in pipeline and all of them placed in "Hyperparameters -> Args" section. Task sections (which have been added using task.connect(..., name=<name>)) are not displayed in pipeline ones.

There is no information on my question in docs

Thank you in advance

**Comment by erezalg** [comment]
Hi @IlyaMescheryakov1402,

Great idea! Actually, at the moment we don't have such capability...How many arguments do you have per pipeline?

I think we can add to the pipeline decorator something like:
@PipelineDecorator.pipeline(name='custom pipeline logic', project='examples', argsmap={'sectionA':['paramA'], 'sectionB:['paramB','paramC']}) and if no section is specified we'll put it into args? 

Would that work?

Erez

**Comment by IlyaMescheryakov1402** [comment]
Hi @erezalg 

About 30-40 arguments per pipeline.

Yeah, sure, I think it will work)

Thank you!

Waiting for the new version with this feature :)

ilya

**Comment by erezalg** [comment]
Hi @IlyaMescheryakov1402 ,
Good news! ClearML V1.5.0 is out! (pip install clearml==1.5.0) with support to specifying HP sections :D 
You can do so by calling:
@PipelineDecorator.pipeline(args_map={'SectionA':['paramA'], 'SectionB':['paramB]})

This will map all the values in the list (paramA for instance) to the key (SectionA) which is the Section's name.

Let me know if you have any questions and enjoy :)

**Comment by jkhenning** [comment]
Hi @IlyaMescheryakov1402, closing this. Please re-open if required.
