### ISSUE TITLE
Separate timeseries and non-timeseries scalars

### ISSUE THREAD

**Issue by ibobak** [allegroai/clearml#631]
Dear authors of ClearML, thank you very much for this excellent tool. 

I looked through all functionality of it, and there is one thing which I am really missing:

![image](https://user-images.githubusercontent.com/8807043/161265006-70ce6d7f-8525-4e99-bb46-c8de1c52fa62.png)

**Comment by mralgos** [comment]
https://github.com/allegroai/clearml/issues/400
You may want to keep an eye on this one

**Comment by erezalg** [comment]
Hi @ibobak,
I think mralgos is correct :), we have a live discussion on Issue #[400](https://github.com/allegroai/clearml/issues/400), I'd be happy to receive some feedback on our design.
