### ISSUE TITLE
get non-archived experiments using Task.get_tasks()

### ISSUE THREAD

**Issue by AristoStelar** [allegroai/clearml#636]
Hello, 
I have been trying to get all the experiments that are not archive using 
`
tasks = Task.get_tasks(project_name=self.project_name,task_filter={"status": ["completed"], "order_by": ["-last_update"], "_all_":dict(fields=["system_tags"], pattern="")})`
as per [The docs](https://clear.ml/docs/latest/docs/references/sdk/task/#taskget_tasks) and I do not get any results. I have also tried applying regex to the pattern and that didnt work either. I have noticed that the archived experiments have a `system_tags` list of 2 items `["archived","development"]` and the non-archived ones have an empty `system_tags` 
Can I try anything else in this  regard? Thank you! Have a wonderful day :hugs:

**Comment by jkhenning** [comment]
Hi @AristoStelar ,

You can try:
```python
tasks = Task.get_tasks(
    project_name=self.project_name,
    task_filter={"status": ["completed"], "order_by": ["-last_update"], "system_tags"=["-archived"]}
)
```

**Comment by AristoStelar** [comment]
Hello @jkhenning Thank you for the reply. It worked perfectly. Have a pleasant day and a beautiful week.
