### ISSUE TITLE
Web Pannel Debug sample picture can't show 

### ISSUE THREAD

**Issue by zylprivate** [allegroai/clearml#637]
![image](https://user-images.githubusercontent.com/60844803/162429812-b2347c62-3015-4faf-9dc7-dcfcc3b64013.png)

**Comment by zylprivate** [comment]
clicking open img shows Jwt is expired

**Comment by gabmis** [comment]
+1, I have been having the same problem

**Comment by jkhenning** [comment]
Hi @gabmis, @gabmis,

I assume you're using the ClearML SaaS?

Can you attach the error you're getting? Also, if the error indicated the JWT token is expired, can you try clearing the browser's cookies and logging-in again?

**Comment by zylprivate** [comment]
Thanks， I try to clear cookies and this issue is solved.
