### ISSUE TITLE
How do I delete metrics？

### ISSUE THREAD

**Issue by zylprivate** [allegroai/clearml#638]
![image](https://user-images.githubusercontent.com/60844803/162554707-dcfaa738-ee48-4b83-bd16-0ae2f032f46e.png)
I find that my metrics storage will be running out. I try to delete experiments but it doesn't work. How do I do?

**Comment by jkhenning** [comment]
Hi @zylprivate,

These metrics represent logs, scalars and plots - you clear them by resetting or deleting tasks.

> I try to delete experiments but it doesn't work

They are currently updated daily, can you confirm the value did not change a day after you've deleted the tasks?

**Comment by zylprivate** [comment]
Thanks, I  think it is a live update before.
