### ISSUE TITLE
Task.get_tasks(). Get a certain number of experiments

### ISSUE THREAD

**Issue by AristoStelar** [allegroai/clearml#641]
Hello, 
I would like to make a `Task.get_task()` call in order to get the first N experiments in the list. When I do a call it loads  all the experiments and because of that, the call takes rather long. 
Is there a way you could do that?
Thank you. Have a pleasant day!!

**Comment by jkhenning** [comment]
Hi @AristoStelar,

You can use the `page` and `page_size` arguments to request a specific page of the results (in this case `0`) and number of results in the page.

**Comment by AristoStelar** [comment]
Thank you very much @jkhenning . It worked wonders!
Have a great day!
