### ISSUE TITLE
How to deploy model in ClearML to my production and track its performances

### ISSUE THREAD

**Issue by maulanaakbardj** [allegroai/clearml#643]
Can I take some models from the models that I have uploaded on the ClearML server into my project such as a notebook? and can I track the performance of each model that has been deployed in production, for example a notebook with monitoring on ClearML?

**Comment by erezalg** [comment]
Hello @maulanaakbardj,

If you want to access models in clearml you can:
```
from clearml import Model
m = Model(model_id='my_id')
m.get_local_copy()
```

If you want you can use Model.query_models() to search for models or once you found a model you need you can call get_local_copy() to get the model file.

As for monitoring models, in your inference code, you can add a logger call and report the metrics that interest you.

Makes sense?
