### ISSUE TITLE
Why storage configuration is in the client side ?

### ISSUE THREAD

**Issue by AndolsiZied** [allegroai/clearml#645]
We encounter disk full issues from time to time. For this we are thinking of using S3 as a storage space. However, looking at the [documentation](https://clear.ml/docs/latest/docs/integrations/storage), we find that this configuration is done on the client side. It's not too clear. Can each user have a storage space? Why this configuration is not in the server side ?

**Comment by jkhenning** [comment]
Hi @AndolsiZied,

> Why this configuration is not in the server side ?

The main reasons behind this decision are:
1. The client is the one in charge of uploads
2. Security-wise, not storing access keys and secrets for external services on the server

**Comment by AndolsiZied** [comment]
So, some users can use S3 storage and some athoer can use the default storage ?

**Comment by AndolsiZied** [comment]
This way, we are forced to provide each user access keys for the aws account.

**Comment by jkhenning** [comment]
I think the scale/enterprise version contains a feature that addresses this issue.
