### ISSUE TITLE
Is it possible to let a clearml agent pull a multi-step pipeline as a single job?

### ISSUE THREAD

**Issue by Waerden001** [allegroai/clearml#652]
I use
- the hosted ClearML services with multiple workers/clearml-agents on serveral machines, all agents listen to the ```default``` queue
- a multi-step (DAG style) pipeline
    - steps are locally-dependent, in the sense that, step 1 write/load some data to the shared memory/RAM and step 2 read from the shared memory/RAM. Since the data is huge (several hundreds GBs), it's really not an option to pass it around, meanwhile, the processing and loading-to-RAM step is also expensive, so we also don't want to do it again and again before every step.  

Once I push the pipeline to the ```default``` queue, **steps in the single pipeline are pulled by different workers/machines**, so when step2 tries to read from the shared memory on its machine, it causes an error, since step1 is pulled by another machine. 

Therefore, my question is, is there a mechanism in ClearML so that we can make sure a multi-step pipeline is pulled by a single agent/worker/machine, this way, the pipeline/DAG is in some sense a single job with multiple steps inside, and a(n) worker/agent really pulls a job instead of atomic steps.

**Comment by jkhenning** [comment]
@Waerden001 perhaps you can use a specific queue for each pipeline?

**Comment by Waerden001** [comment]
> @Waerden001 perhaps you can use a specific queue for each pipeline?

Then we still can let only one worker listen to the specific queue, otherwise, the steps in the pipeline will still be pulled by different workers. I end up using the topological order of the steps and put them in one function to work around.  Since  we are allowed to have hierarchical structure when orchestrating pipelines in ClearML,  just thought it would be nice if we can decide which level(e.g. the whole pipeline) should be viewed as a single job, therefore pulled by a single worker, then when the worker gets the job, it executes the steps one by one without being interrupted by steps from other jobs.

**Comment by jkhenning** [comment]
@Waerden001 I think the best solution for your use-case is using a multi-process step with shared memory, WDYT?

**Comment by Waerden001** [comment]
> @Waerden001 I think the best solution for your use-case is using a multi-process step with shared memory, WDYT?

I agree, thanks for the help~
