### ISSUE TITLE
Store models offline

### ISSUE THREAD

**Issue by shaziaakbar** [allegroai/clearml#653]
Hi everyone, 
The "offline mode" feature is great when using HPC environments with no internet connection. Would it be possible to expand this to allows models to be saved (and later uploaded to ClearML)?

---
Good news guys, offline mode is now available 🎊 
With the new release of [trains 0.16](https://github.com/allegroai/trains/releases/tag/0.16.0) you can set [Task.set_offline](https://github.com/allegroai/trains/blob/ffdf2e5c4c547a39120f7abaf5814cec723f7a33/trains/backend_interface/task/task.py#L1795) to True. 
Later you can import your session (either the zip file or folder) with [Task.import_offline_session](https://github.com/allegroai/trains/blob/ffdf2e5c4c547a39120f7abaf5814cec723f7a33/trains/task.py#L1690).

The offline session includes all console output, metric logs & artifacts.
(It does not include stored models, let us know if you would like to see that included as well :)

_Originally posted by @bmartinn in https://github.com/allegroai/clearml/issues/117#issuecomment-672302058_

**Comment by erezalg** [comment]
Hi @shaziaakbar,

Just to make sure I understand correctly, you'd like to store locally the models created in offline mode, and then when importing the offline session to clearml, we will also import the models themselves?

**Comment by shaziaakbar** [comment]
> Hi @shaziaakbar,
> 
> Just to make sure I understand correctly, you'd like to store locally the models created in offline mode, and then when importing the offline session to clearml, we will also import the models themselves?

Yes exactly :)

**Comment by DavidNativ** [comment]
Hello @shaziaakbar 

Please apology for not having answered faster.
Parameters, plots, artefacts and so on are pulled when uploading an offline session ; but you are right, the model is not.

We are currently working on the issue and will soon release a version that will allow to also pull the model.

**Comment by shaziaakbar** [comment]
> Hi @shaziaakbar , this should be in the upcoming release that is pretty close :)

Great! Looking forward to this addition

**Comment by pollfly** [comment]
Hey @shaziaakbar ! Just letting you know that this issue has been resolved in the recently released [v1.10.0](https://github.com/allegroai/clearml/releases/tag/v1.10.0). Let us know if there are any issues :)

**Comment by jkhenning** [comment]
@shaziaakbar closing this, please reopen if required.
