### ISSUE TITLE
[Example Request] Add an example from OpenMMLab in examples/frameworks

### ISSUE THREAD

**Issue by zhouzaida** [allegroai/clearml#654]
Hi, thanks for the work.

MMCV added a `ClearMLLoggerHook` (https://github.com/open-mmlab/mmcv/pull/1906) to support logging to clearml. Could an example be added to `examples/frameworks`?

- example script: https://github.com/open-mmlab/mmcv/blob/master/examples/train.py

**Comment by erezalg** [comment]
hi @zhouzaida,

We'd be happy for a PR if you're up for it :) 
If not, we can also add it ourselves!

**Comment by zhouzaida** [comment]
Thanks for your reply. I will create a PR to add it.
