### ISSUE TITLE
Errors deleting artefacts from Azure storage

### ISSUE THREAD

**Issue by tkupek** [allegroai/clearml#660]
I'm using the [cleanup service](https://github.com/allegroai/clearml/blob/master/examples/services/cleanup/cleanup_service.py) to remove old and archived experiments. The job also deletes artefacts from Azure, which is perfect.

However, when running the job we get hundreds of errors from the Azure connection:

```
2022-04-25 12:41:30,002 - clearml.Task - ERROR - Failed deleting azure://xxx.blob.core.windows.net/xxx/xxx/xxx.jpeg: 'NoneType' object has no attribute 'container'
```

```
2022-04-25 12:42:15,719 - clearml.storage - WARNING - Storage helper problem for xxx/xxx .slash. xxx.jpeg: Operation returned an invalid status 'Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.'
ErrorCode:AuthenticationFailed
```

```
2022-04-25 12:42:36,914 - clearml.Task - ERROR - Failed deleting the following URIs:
azure://xxx.blob.core.windows.net/xxx/xxx.ckpt
```

The Azure connection is the same we use in training and it works for uploading artefacts and debug samples.

It this a problem of slashes in the filename?

**Comment by jkhenning** [comment]
Hi @tkupek ,

I don't think it's related to the filename or file path. Are you sure the credentials are permitted to delete objects as well?

**Comment by jkhenning** [comment]
Do you know which clearml SDK version is installed in the cleanup service?

**Comment by jkhenning** [comment]
Can you see the `clearml` python package version? it will be reported in the task representing the cleanup service

**Comment by tkupek** [comment]
![image](https://user-images.githubusercontent.com/4039384/165113656-7835a695-c7e2-4497-908e-4b5eb3506353.png)

**Comment by jkhenning** [comment]
You should find it in the Execution -> Installed Packages section

**Comment by tkupek** [comment]
Sorry, got it now:

`clearml==1.3.2`

**Comment by jkhenning** [comment]
🙂 👍 
Is this a setup that worked before and stopped for some reason? Or is this a new setup that's not working?

**Comment by tkupek** [comment]
Clearml and trainings are running for a while. I just tried the cleanup job. So the delete did not work before.

**Comment by jkhenning** [comment]
OK, so it's safe to assume something in the configuration is missing - what are you setting in the `clearml.conf` for the Azure settings?

**Comment by tkupek** [comment]
```
azure.storage {
         containers: [
             {
                 account_name: "xxx"
                 account_key: "xxx"
                 container_name: "xxx"
             }
         ]
    }
```

**Comment by tkupek** [comment]
Anything I can try from my side or is this a ClearML issue?

**Comment by jkhenning** [comment]
@tkupek might it be related to the azure python package version? what clearml and azure version do you have installed?

**Comment by tkupek** [comment]
It's `clearml[azure]==1.3.2` and `azure-storage-blob>=12.9.0`

**Comment by eugen-ajechiloae-clearml** [comment]
Hi @tkupek.
I tried cleaning up tasks and it works just fine for me.

Are you able to delete a file directly?
```python
from clearml.storage.helper import StorageHelper

helper = StorageHelper.get("azure://xxx.blob.core.windows.net/xxx")
helper.upload("cat.jpg")
assert "cat.jpg" in helper.list()
helper.delete("azure://xxx.blob.core.windows.net/xxx/cat.jpg")
assert "cat.jpg" not in helper.list()
```

**Comment by tkupek** [comment]
Thanks a lot for the example code. The ClearML code is completely fine, the problem was caused by a misconfigured Azure Key in the ClearML-Service config (`docker-compose`, instead of `clearml.conf`).
Appreciate your support!
