### ISSUE TITLE
Datasets cache folder not shared between users

### ISSUE THREAD

**Issue by mralgos** [allegroai/clearml#671]
Hello, 
a discussion on this issue started on Slack [here](https://clearml.slack.com/archives/CTK20V944/p1651591294515349).

I have a ClearML server hosted on AWS with web authentication enabled. Each ML person has:
 - its own user/pass used to log in to the ClearML server
 - its own set of ClearML API credentials
 - its own set of AWS credentials
 - its own clearml.conf file in the home

The config file defines the path to the cache folder via:
```
storage {
        cache {
            # Defaults to system temp folder / cache
            default_base_dir: "/scratch/clearml-cache"
        }
```

We have some datasets registered by the ClearML server and the codebase uses `get_local_copy()` to download the data into the machine. The problem manifests when two or more people wants to access (read, i.e. the cache exists already and isn't corrupted) the dataset. 

The execution fails with this error:

```
Traceback (most recent call last):
...
    path = Dataset.get(dataset_name=dataset_name,
  File "/scratch/people/gf/miniconda3/envs/py38-torch/lib/python3.8/site-packages/clearml/datasets/dataset.py", line 567, in get_local_copy
    target_folder = self._merge_datasets(
  File "/scratch/people/gf/miniconda3/envs/py38-torch/lib/python3.8/site-packages/clearml/datasets/dataset.py", line 1387, in _merge_datasets
    target_base_folder = self._create_ds_target_folder(
  File "/scratch/people/gf/miniconda3/envs/py38-torch/lib/python3.8/site-packages/clearml/datasets/dataset.py", line 1336, in _create_ds_target_folder
    cache.lock_cache_folder(local_folder)
  File "/scratch/people/gf/miniconda3/envs/py38-torch/lib/python3.8/site-packages/clearml/storage/cache.py", line 273, in lock_cache_folder
    lock.acquire(timeout=0)
  File "/scratch/people/gf/miniconda3/envs/py38-torch/lib/python3.8/site-packages/clearml/utilities/locks/utils.py", line 130, in acquire
    fh = self._get_fh()
  File "/scratch/people/gf/miniconda3/envs/py38-torch/lib/python3.8/site-packages/clearml/utilities/locks/utils.py", line 205, in _get_fh
    return open(self.filename, self.mode, **self.file_open_kwargs)
PermissionError: [Errno 13] Permission denied: '/scratch/clearml-cache/storage_manager/datasets/.lock.000.ds_5f1f42f430b042cfb213e8099cda00b4.clearml'
```

**Comment by jkhenning** [comment]
@mralgos do I understand it correctly that more than one user is trying to access this dataset from the same workstation?

**Comment by mralgos** [comment]
@jkhenning yes, correct. It is possible that multiple users need to read the dataset cached in the same workstation

**Comment by jkhenning** [comment]
@mralgos in that case it would seem to be a Linux permissions that might be outside of the scope of ClearML code - how would you expect it to work? As far as I know the lock is required to make sure multiple writers don't compete on the same file

**Comment by mralgos** [comment]
I'd expect that if someone is writing the dataset, the lock folder must be created in order to prevent other writing ops of the same dataset. However, if the dataset exists already, multiple users should be able to read it (hence the lock wouldn't be necessary). 

I'm going to check the permission and the umask settings in the meantime.

**Comment by mralgos** [comment]
@jkhenning I've put together a change that would potentially fix the issue (assuming I'm not missing something in the overall design). 

Basically, two main changes:

1. once the download of a dataset is completed, the lock is released immediately
2. while a process is downloading a dataset i.e. holding the lock, other processes will wait until the lock is released (in the current fix, after 5 min of wait there's a timeout error raise. But this can be changed)

Hope this helps. Let me know what you think.

**Comment by jkhenning** [comment]
Hi @mralgos, thanks for the contribution! Closing this issue 🙂
