### ISSUE TITLE
Access to dynamically created pipeline steps

### ISSUE THREAD

**Issue by lpogo** [allegroai/clearml#676]
Hi,

I am creating pipeline steps from function dynamically, based on pipeline parameters.
The pipeline looks like:

```# Initialize pipeline
pipe = PipelineController(..)

# Add parameters
pipe.add_parameter(
        name='model_params',
        description='Model params list', 
        default='param1, param2'
 )

# Get pipeline parameters
pipe_parameters = pipe.get_parameters()

# Define steps
pipe.add_function_step(
    name='step1',
    function=step1,
    function_return=['data_frame'],
    cache_executed_step=True,
)

# Create step dynamically based on number of parameters on the list
param_list = pipe_parameters['model_params'].split(',')
counter=1
for item in param_list :
    pipe.add_function_step(
        name=f'step_training_{counter}',
        parents=['step1'],  
        function=step_training,
        function_kwargs=dict(dataset='${step1.data_frame}',  model_param=item),
        function_return=['model'],
        cache_executed_step=True,
    )
    counter = counter+ 1
```

Now, I want to finalise my pipeline and pass all created "step_training_X" ids to the last step.
How can I do that, if number of steps may be different each time?
```# Finalise pipeline
pipe.add_function_step(
    name='step_finalise',
    # parents -> the pipeline will automatically detect the dependencies based on the kwargs inputs
    function=step_finalise,
    function_kwargs=dict(tasks=['${step_training_X.id}']),
    function_return=['best_model'],
    cache_executed_step=True,
)
```

I have no idea how to pass step_training_1, step_training_2, ..., step_training_X ids to the step_finalise.
Is there a way to use a variable inside `'${step_training_X.id}'` ?

Thanks!

**Comment by bmartinn** [comment]
Sorry @lpogo , I just noticed this one.

From the sample code you provided is seems like an easier (and way more intuitive) usage of pipeline would be to use function pipeline decorators, you can see an example [here](https://github.com/allegroai/clearml/blob/master/examples/pipeline/pipeline_from_decorator.py), no? Am I missing something?

> Now, I want to finalise my pipeline and pass all created "step_training_X" ids to the last step.

I think the main issue is that a list of strings is not being "resolved" (as opposed to a single string), I guess this is a good feature to add 😄  

You can however "hack" it with:
```python
final_function_kwargs = {}
for i in range(len(param_list)):
    final_function_kwargs[f"step_training_{i}"] = f'${{step_training_{i}.id}}'

pipe.add_function_step(..., function_kwargs=final_function_kwargs)
```

wdyt?

BTW: If resolving a list of strings (e.g. supporting `['${step_one.id}', '${step_two.id}', ]`) seems important, how about a separate issue with a feature request ?

**Comment by lpogo** [comment]
Hi @bmartinn,
Your "hack" solve my headache :) it is exactly what I needed in my source code. 
If list of strings could be supported natively it would you really nice.
But for now, I can live without it. When I use your "hack" ClearML is smartly detecting list of parent tasks.
Really good job 👍 

Thanks for help!
