### ISSUE TITLE
Image view options in Results|Debug Images

### ISSUE THREAD

**Issue by motikadosh** [allegroai/clearml#68]
Hi,
I am uploading very large images to Trains each epoch to view intermediate results.
Their thumbnails look very well, but when I open an image its too big to fit in screen.
1. Is it possible  to add zoom in-out/resize/fit-screen option?

2. As it possible to show x,y,value at mouse cursor?

Taking this idea further (less in my use-case), I assume there can be more image tools. Perhaps download image, change intensities track bar or auto-scale intensities.

Thanks!

**Comment by JDennisJ** [comment]
Hi @motikadosh 

Thank you for this suggestion, I think image tools such as you suggested are a great idea!

We will add those features to the UI soon. I will update this issue with the progress :)

**Comment by jkhenning** [comment]
Closing this as these features already exist in the latest ClearML Server versions.
