### ISSUE TITLE
"Series" name showing in WebUI (Debug Samples) for text files

### ISSUE THREAD

**Issue by skinan** [allegroai/clearml#685]
**Code:**
![Screenshot from 2022-05-18 12-51-03](https://user-images.githubusercontent.com/46783803/168975857-5783a903-9c9b-404e-923f-a77d7d513cef.png)

**Output:**
![Screenshot from 2022-05-18 12-50-34](https://user-images.githubusercontent.com/46783803/168975759-c1372595-180b-4a23-85b3-a09a2bb6b217.png)

**Code Link:**
https://github.com/skinan/ParlAI/blob/main/parlai/scripts/train_model.py

**Comment by DavidNativ** [comment]
hello @skinan 
we are working on reproducing that, will keep you updated

**Comment by DavidNativ** [comment]
hello @skinan
we are working on reproducing that, will keep you updated

**Comment by pollfly** [comment]
Hey @skinan! Just letting you know that this issue has been resolved in the recently released [ClearML Server v1.11.0](https://github.com/allegroai/clearml-server/releases/tag/v1.11.0). Let us know if there are any issues :)

**Comment by jkhenning** [comment]
@skinan closing this. Please reopen if required.
