### ISSUE TITLE
Working with PyTorch Lightning Distributed

### ISSUE THREAD

**Issue by marcmk6** [allegroai/clearml#687]
Hi,

There is an example on how to use `clearml` with native PyTorch distributed implementation. I'm wondering what should I do while working with PyTorch Lightning on multi-GPUs with DDP for instance.

Is something like the following sufficient?
```python
import pytorch_lightning as pl

...

if __name__ == '__main__':
    curr_task = Task.current_task()
    if not curr_task:
        task = Task.init(project_name="examples", task_name="PL_distributed_test")
    else:
        task = curr_task

    trainer = pl.Trainer(devices=4, accelerator="gpu")
    trainer.fit(model, train_loader, val_loader)
```

Thanks

**Comment by DavidNativ** [comment]
Hi 
Yes it should be sufficient ! It is amazingly simple and that what is good

**Comment by marcmk6** [comment]
Got it. thanks!
