### ISSUE TITLE
Upload artifacts which contain lambdas

### ISSUE THREAD

**Issue by schiegl** [allegroai/clearml#689]
As I understand, the `Task.upload_artifact` function in ClearML is limited by what Python's `pickle.dump` can do. As of now `pickle.dump` cannot deal with objects that contain `lambda` functions.

Is there a way to upload these objects without resorting to storing the object on disk with e.g. [dill](https://github.com/uqfoundation/dill) and then uploading the file?

**Comment by DavidNativ** [comment]
The default fallback is pickle, because dill (which is  a great package) is not a built in package. Relying on "dill" for serialization means we will always need to add it to the requirements.
You can of course manually dill the object and use it.
We did add the ability to add custom serialization function, maybe we should extend it to support dill

**Comment by schiegl** [comment]
> We did add the ability to add custom serialization function, maybe we should extend it to support dill
There is no way to specify the custom serialization as a user of ClearML e.g. when instantiating a new task?

**Comment by schiegl** [comment]
In my case both would work fine. If you do it at the task level there might be some kind of matching necessary on the users side.

**Comment by DavidNativ** [comment]
Hi @schiegl 
FYI I am creating a feature request. Thanks for your contribution

**Comment by gbartyzel** [comment]
@DavidNativ Hello, I'm also interest in this feature. What's the status of it?

**Comment by erezalg** [comment]
Hi @schiegl and @gbartyzel ,

My apologies for not answering earlier, install the latest clearml version and in the upload_artifact() method you'll find a possibility to specify the serialization_function

**Comment by gbartyzel** [comment]
@erezalg Well, but I'm currently playing with pipelines and I want to pass Pytorch model from one step to another. It's not a pure Pytorch model, it's customized by our framework. Is this option also available in the pipeline decorator?

**Comment by erezalg** [comment]
@gbartyzel you mean to replace the default serializer from pickle to dill? Or specifically in an experiment \ pipeline?

**Comment by gbartyzel** [comment]
@erezalg I mean by replacing the default pickle serializer. As I found, dill is more advanced then default pickle (lambda serializing etc.). But well, it's just a suggestion ;)

**Comment by erezalg** [comment]
@gbartyzel We thought the same thing, but as much as we love dill (and we do :) ), it's yet another dependency that users might not use (As far as we know, it's less commonly used than pickle) and adding dependencies that our users might not already have is something we try to avoid as we found out it's not well accepted.

Anyway, we've tested this with dill and it works, as soon as we can get you a nice interface to use on pipelines

**Comment by gbartyzel** [comment]
@erezalg Ok, a strong argument. So it would be awesome to choose manually the serializer engine.

**Comment by erezalg** [comment]
@gbartyzel 
That is the plan :) Will update here once it's out!

**Comment by pollfly** [comment]
Hey @schiegl and @gbartyzel! [v1.10.0](https://github.com/allegroai/clearml/releases/tag/v1.10.0) is now out, supporting custom artifact serialization for pipelines

**Comment by jkhenning** [comment]
@schiegl, @gbartyzel, closing this, please reopen if required.
