### ISSUE TITLE
Feature request: Fixed epoch in compare experiments / debug samples

### ISSUE THREAD

**Issue by dvirnimrod** [allegroai/clearml#691]
Hi!
When comparing between experiments, many times you (or at least me) want to compare debug samples of the same epoch.
Currently, you need to search in each experiment for the specific epoch. It would be nice if there was an option to "fix" all the experiments to the same epoch and then search once.
think about it :)
Thanks!
Nimrod
Hourone.ai

**Comment by ainoam** [comment]
Thanks for the feedback @dvirnimrod.
Can definitely see the value in it. For your use case would you say the same applies to the metric filter?

**Comment by dvirnimrod** [comment]
Absolutely :)

**Comment by pollfly** [comment]
Hey @dvirnimrod! [v1.7.0](https://github.com/allegroai/clearml-server/releases/tag/v1.7.0) is now out supporting synchronizing debug sample iteration and metric selection in experiment comparison.

**Comment by jkhenning** [comment]
Closing this issue. Please reopen if it's still relevant.
