### ISSUE TITLE
Feature request: Make pipeline projects visible in UI

### ISSUE THREAD

**Issue by milongo** [allegroai/clearml#694]
Hi,

Currently, to view all the steps that were launched by a controller (with decorators) in the server UI, one has to go into the Pipelines tab, select details for the controller, and then click the last "subproject" for the controller. This is not really straightforward. Can you please "unhide" the pipeline controller subprojects so they are visible and accessible from the Projects view tab?

Thanks!

**Comment by milongo** [comment]
@ainoam is there an ETA on this?

**Comment by ainoam** [comment]
@milongo It's in the oven... Hope to have it out within a month.

**Comment by pollfly** [comment]
Hey @milongo! [v1.6.0](https://github.com/allegroai/clearml-server/releases/tag/v1.6.0) is now out, supporting "show hidden projects" setting control.

**Comment by jkhenning** [comment]
Closing this issue. Please reopen if it's still relevant.
