### ISSUE TITLE
Bug: webUI not showing hyperparameters consistently when scrolling is needed

### ISSUE THREAD

**Issue by alekpikl** [allegroai/clearml#705]
In the `configuration view,` the hyperparameters are not shown when hyperparameters are very long (e.g., long strings). 

When scrolling up/down, some hyperparameters are shown only briefly but then disappear. 

I noticed this when the window (_window_ is for me where the part of the tab where ClearML shows hyperparameters) size changes.

At a certain point, the left/right scroller changes size (because of the long strings) and the mess begins. 

Unfortunately, I cannot share screenshots at this point, but I'm sure you can reproduce this if you connect many (so that you must scroll up/down/left/right) differently long hyperparameters.

**Comment by ainoam** [comment]
Thanks for the report @alekpikl.
In lieu of screenshots, can you share some specifics: how many parameters, approximate length, long parameter names/values?

**Comment by alekpikl** [comment]
- ~100 hyperparameters
- Longest value is ~20k characters (basically a string config of some modules)
- There are other long values 
- Most other values are boolean/ints

It seems that you centre the hyperparameter values and depending on the longest value in the current screen, all the values are _moved_ to the centre giving me the feeling that they disappeared. 

Could you maybe add an option to limit the width of the hyperparameters and only extend it if clicked on, similar to the experiments tabular view where long fields are _cut_. 

And maybe left-centre the hyperparams.

**Comment by alekpikl** [comment]
Could you reproduce this?

**Comment by ainoam** [comment]
@alekpikl Yes indeed. A fix should be coming in the next server release.

**Comment by alekpikl** [comment]
Thank you very much!

**Comment by pollfly** [comment]
Hey @alekpikl!  Just letting you know that this issue has been resolved in the recently released [v1.7.0](https://github.com/allegroai/clearml-server/releases/tag/v1.7.0). Let us know if there are any issues :)

**Comment by alekpikl** [comment]
This fixes it. Thank you!
