### ISSUE TITLE
How to access ClearML Datasets from self-hosted server

### ISSUE THREAD

**Issue by AH-Merii** [allegroai/clearml#719]
Hi,

Is there a way to use the Datasets Feature on the self-hosted version of ClearML as shown in the image below? If so, can you point me to the documentation used to do so? 
![image](https://user-images.githubusercontent.com/43741215/178482215-34501d2c-bcb4-410c-b6c4-8fd0d53093a8.png)

Currently, my UI looks like the image below, with no option to access the Datasets panel.
<img width="423" alt="image" src="https://user-images.githubusercontent.com/43741215/178482643-20729714-e81b-4dd4-9258-9908426fac4f.png">

**Comment by DavidNativ** [comment]
Hi @AH-Merii 
can you please provide me your ClearML packages versions ? Especially the SDK (clearml) and the server (clearml-server)

**Comment by AH-Merii** [comment]
> Hi @AH-Merii can you please provide me your ClearML packages versions ? Especially the SDK (clearml) and the server (clearml-server)

I just checked the clearml server version, and it is version `1.5.0`. I upgraded the docker image and I now have access to the Datasets Panel. 

Thanks for your help!
