### ISSUE TITLE
Incorrect tensorboard plots in ClearML web UI 

### ISSUE THREAD

**Issue by skprot** [allegroai/clearml#721]
Hello! I've run into a problem with the tensorboard not displaying correctly in the ClearML web interface. I'm using the mmdetection3d repository and it uses tensorboard as its logging tool. The tensorboard logger has multiple tabs with multiple graphs, but clearml merges these graphs under tabs and the graphs become unreadable due to different scale. What can I do about it?

![tensorboard](https://user-images.githubusercontent.com/56299944/178723456-6d617ac4-673d-43a1-acdb-22d6fbc62a64.png)

![clearml](https://user-images.githubusercontent.com/56299944/178726471-12828f3d-6582-417c-8869-f75a3439aade.png)

**Comment by shyallegro** [comment]
did you try Group By "None"?
![image](https://user-images.githubusercontent.com/52773084/179006773-b2937cd2-c2ad-4b4b-bfed-8946a7d222ef.png)

**Comment by skprot** [comment]
Thank you!
