### ISSUE TITLE
Hierarchical View for Datasets UI to match Projects View (Feature Request)

### ISSUE THREAD

**Issue by AH-Merii** [allegroai/clearml#724]
I recently updated to the newest version of ClearML Server `1.6.0` to try out the new Datasets panel feature. 

**Expected Behaviour:**
Subfolders work as expected when creating them inside of projects containing tasks, see screenshot below using the Urbansounds example:
<img width="949" alt="image" src="https://user-images.githubusercontent.com/43741215/179463406-7b18e098-7471-4734-ae35-0143ad54a969.png">

**Actual Behaviour:**
When trying to create sub-dataset called raw_dataset for Datasets within the same project, I get the following behaviour instead:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/43741215/179463647-1b686fa8-b0c2-4dff-89da-77b67c9be197.png">
<img width="417" alt="image" src="https://user-images.githubusercontent.com/43741215/179463799-92e4f2c8-47e7-459c-abb9-bd535205102f.png">
<img width="423" alt="image" src="https://user-images.githubusercontent.com/43741215/179463835-96d14f7c-14f7-47dd-8879-4e998d89f913.png">

Dataset are also not separated by projects, so the deepest sub-datasets are all displayed on the same level as shown below:
<img width="1827" alt="image" src="https://user-images.githubusercontent.com/43741215/179464299-bc984dd0-b4c3-4e06-a105-49cc309fc3ed.png">

What I expected as a user is to have the project name as the root directory in the Datasets panel, and then have the sub-datasets within the project.

Is this the intended behaviour?

**Comment by ainoam** [comment]
@AH-Merii This is indeed the intended behaviour, the rational being to provide a data-centric view i.e. put all of the available data in front of the user regardless of how their experiments are organized.

Does this make sense?

**Comment by AH-Merii** [comment]
@ainoam so the subfolders view when it comes to projects and tasks, is meant to behave differently than the datasets view? I find it harder to find the datasets and differentiating them without any parent label. The only way for me to differentiate them is by hovering over them as shown in the screenshots above.

**Comment by AH-Merii** [comment]
Also, currently the search only captures the dataset names and not the parent project/dataset when using the search bar:

<img width="1779" alt="image" src="https://user-images.githubusercontent.com/43741215/179474538-4f9c3b1c-dcfa-4a9b-beac-8b5aaeaaaf88.png">

Even though the dataset below is part of that project as shown in the screenshot below:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/43741215/179474630-cffb76f3-97ba-4c63-9009-0f63b05b9dee.png">

**Comment by ainoam** [comment]
@AH-Merii 

> Also, currently the search only captures the dataset names and not the parent project/dataset when using the search bar

This is in-line with the aforementioned rational: This view is disconnected from any project hierarchy  (though the information is  provided, as additional details).

>  I find it harder to find the datasets and differentiating them without any parent label

Note that you can indeed tag your datasets
![image](https://user-images.githubusercontent.com/51905810/179507134-9dad1187-d30a-419b-84ab-fdd790f42b57.png)

If I understand correctly, what you're saying is that it would be helpful if the datasets page would provide to additionally be able to organize the datasets by their project?

**Comment by AH-Merii** [comment]
**Initial Code without subfolder:**
```
    dataset = Dataset.create(
        dataset_name='UrbanSounds example',
        dataset_project='ClearML examples/Urbansounds',
    )
```

**Code with Subfolder:**
```
    dataset = Dataset.create(
        dataset_name='UrbanSounds example/raw_data',
        dataset_project='ClearML examples/Urbansounds',
    )
```

So in short the same way you create sub-projects, except applied on `Dataset.create()`

**Comment by AH-Merii** [comment]
@ainoam, were you able to reproduce it, and if so, is this behaviour intended?

**Comment by AH-Merii** [comment]
@ainoam, Thanks for the reply will update it now, can you please label this issue as an feature request, as I am unable to do so.

**Comment by AH-Merii** [comment]
> Let's have a look at the example below: In the example below, I am attempting to delete the UrbanSounds example dataset, but I am unable to do so. <img alt="image" width="355" src="https://user-images.githubusercontent.com/43741215/179510536-2282e465-0f8a-4686-ab9e-a53d9d2ee401.png"> <img alt="image" width="536" src="https://user-images.githubusercontent.com/43741215/179510653-98042531-39a0-4c1b-8c54-56d45033dbde.png"> This is because we have a sub-dataset called `UrbanSounds/raw_data`, however it does not show that unless I manually hover over each and every one of my of the other datasets to find the one that is related to UrbanSounds. <img alt="image" width="1040" src="https://user-images.githubusercontent.com/43741215/179510810-e1d03a81-8311-468a-b3ea-c97b34da6e9d.png"> Then I can proceed and delete the dataset.

@ainoam What about the issue shown above, shall I write up a new issue specifically for deleting the sub-datasets?

**Comment by ainoam** [comment]
@AH-Merii Apologies for the slight lag :)

Am I understanding correctly that the counters for the datasets are wrong? For order's sake a new issue would be best.

**Comment by pollfly** [comment]
Hey @AH-Merii! [clearml-server v1.10](https://github.com/allegroai/clearml-server/releases/tag/v1.10) is now out supporting a project hierarchy view for ClearML resources (pipelines, datasets, reports)

**Comment by AH-Merii** [comment]
> Hey @AH-Merii! [clearml-server v1.10](https://github.com/allegroai/clearml-server/releases/tag/v1.10) is now out supporting a project hierarchy view for ClearML resources (pipelines, datasets, reports)

Congratulations on the release, I look forward to testing it and rolling it out to the rest of the team! 

Thank you for being responsive to the feedback!
