### ISSUE TITLE
Cannot change command line arguments in optimisation

### ISSUE THREAD

**Issue by MoPl90** [allegroai/clearml#730]
Hi,

it appears that the hyper parameter optimisation is limited to "General" hyper parameters, i.e. those passes via ```task.connect(...)```. Is it possible to optimise over the automatically detected command line arguments, too?

**Comment by erezalg** [comment]
@MoPl90,
There shouldn't be any limitation, at least not intentional :) 
Can you let me know what are yoyu trying to do and what's not working?

**Comment by MoPl90** [comment]
Hi again,

I am training a pytorch model for which I pass certain configurations as command line arguments. The agent detects them correctly and displays them in the UI. However, adapting the hyper parameter optimisation template script to my use case, these parameters **are not** detected. If instead I put them in a dictionary and attach them to the task, they are detected and can be optimised as expected.

**Comment by MoPl90** [comment]
Hey,
sorry for the delay. Below is a super minimal example to reproduce this behaviour. If you run this and use it as a base experiment for hyper parameter optimization (I used [this script](https://github.com/allegroai/clearml/blob/0397f2b41e41325db2a191070e01b218251bc8b2/examples/optimization/hyper-parameter-optimization/hyper_parameter_optimizer.py) with appropriate changes), then you will see two types of "Hyperparameters" in the UI's "Configuration" dash board: Args and General. Args will always be the value you passed to the base experiment, while General will change. The result will always be the value you set originally.



```
from clearml import Task, Logger
import argparse


def main(args):

    Task.init(project_name="Examples", task_name="dummy task")

    print(args.value)

    logger = Logger.current_logger()

    logger.report_scalar(
        title="Loss", series=f"loss", value=args.value, iteration=1,
    )


if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("--value")
    args = parser.parse_args()

    main(args)

```

**Comment by erezalg** [comment]
Hi @MoPl90
Now I think I understand! 
You'll have to enter the full path, including section, so in your example you'll have to add parameter:
 hyper_parameters=[
        DiscreteParameterRange('Args/value', values=[30]),
    ],

This will work

**Comment by MoPl90** [comment]
Ah, I see. This works, thanks!
