### ISSUE TITLE
Failed uploading: 'latin-1' codec can't encode characters 

### ISSUE THREAD

**Issue by sephib** [allegroai/clearml#733]
Hi,
Trying to upload a `csv` into GSC using `dataset.add_files` we are getting the following error:
>2022-07-27 14:39:16,405 - clearml.storage - ERROR - Failed uploading: 'latin-1' codec can't encode characters in position 80-81: Body (`HEBREW WORD`) is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

Looking at the [upload_file](https://github.com/allegroai/clearml/blob/master/clearml/storage/manager.py#L56) function I was not able to find where we can add the `body.encode('utf-8') `

I tried to convert the file  into `parquet` and still got the same error.

Any suggestions?

**Comment by eugen-ajechiloae-clearml** [comment]
Hi @sephib! Can you please attach a sample file that would help us reproduce this issue? 
Also, what does the following snippet print:
```
import sys
import locale

print(sys.getfilesystemencoding())
print(locale.getpreferredencoding())
```
If you see `latin-1`, you could try setting `PYTHONUTF8=1` env var before running your program or try running Python with `-X utf-8` command line argument.

**Comment by sephib** [comment]
Unfortunately - I don't have the configuration to reproduce the issue.
I'll close it for now - and will reopen it if we encounter it again.
