### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by David-Taub** [allegroai/clearml#744]
I have a few UI suggestions related to the PLOTS tab:
1. I would like to be able to see plots with a longer name, but the left-side file list pane width is fixed. I would love it if the width was changeable (see image below).
2. I would like to be able to download all plots from the PLOTS tab of a specific task
3. The selection of the visibility of the plots is counter-intuitive, the "Hide all" and "Show all" work on all plots, not only those shown after the filter text. I would like to be able to show only plots with a certain word in it, e.g. search a keyword "validation" and press "show all" and in that way I could see only plots with the word "validation" in it.
![image](https://user-images.githubusercontent.com/8448791/184076129-3a38e636-910e-40b3-9e2d-1afdcbcfb0cc.png)
4. I would like to be able to remove projects from my workspace through the UI, especially the example projects.

Thanks!

--EDIT--
added point 4 and clarified point 2

**Comment by ainoam** [comment]
Thanks for the great feedback @David-Taub.

To clarify your point (2) - Do you mean you're missing a single control to download all plots in the current task?

We'll see

**Comment by David-Taub** [comment]
yes

**Comment by ainoam** [comment]
@David-Taub Regarding your point (2), this could be achieved by exporting all plots to CSV and providing an archive of said CSVs - Does that match your use case?
Regarding point (4), with the exception of the examples project, this is already available through the [UI project actions](https://clear.ml/docs/latest/docs/webapp/webapp_projects_page#project-actions). For the example projects. as your work progresses, the example projects will be pushed back to the end of the project list - What drives the need to completely remove them?

**Comment by David-Taub** [comment]
(2) I guess you mean zip and not csv, as these are images not numbers. This is actually what we are doing as a workaround, thought you'd like to add this as a feature since it seems like a common use-case, as searching & browsing 100+ plots images is currently not super fiendly via the web app (see point 1, 3).
(4) maybe it's my OCD, but it seems weird when I demo ClearML to others, that 50% or the presented projects on the main screen are permanent demo projects. We don't plan on setting other ClearML projects in the foreseable future, BTW.

**Comment by ainoam** [comment]
@David-Taub 
(1) and (3) seem very sensible, and hopefully can make it into a near release of the ClearML server.
For (2), CSV was indeed intended, as you'll note that for most plots you can already export each specific plot as a CSV file (hence the suggestion for aggregating all these actions into a batch archive). Can you provide some more details on the type of plots you are storing, and the use case that triggers downloading all plots of a task? What is the intended use of the downloaded plots?
For (4), is this specific to the main home (dashboard) page, or to other pages (e.g. projects page) as well?

**Comment by David-Taub** [comment]
(2) Thanks for the clarification, though I'm afraid your suggestion does not solve my issue. I need to create multiple plots per epoch, meaning I end up with 100+ plots per train. The plots have no "export as CSV" option (I plot via imshow), which I don't need anyway. Currently, I would need to press 100+ times on the small camera button to get the plots downloaded. As for the  reason I want to download the plots, it is for presentations and analysis - as these plots, in my case, are the "proof" for a successful training process.
(4) not specific to the home page. I want the option to remove projects, resulting in them disappearing from **all** pages that show projects.

**Comment by pollfly** [comment]
Hey @David-Taub! [clearml-server v2.4.0](https://github.com/clearml/clearml-server/releases/tag/v2.4.0) is now out with "show/hide matching filter" control in UI Task scalars and plots, which implements suggestion (3).
