### ISSUE TITLE
ClearML dataset versioning/management performance

### ISSUE THREAD

**Issue by senysenyseny16** [allegroai/clearml#750]
hi!

At this moment in our company we use DVC for dataset versioning/management and we want to integrate in our workflow ClearML, so there are two options:
1. Leave DVC for dataset versioning and use ClearML for tracking
2. Set up ClearML for both

The second options looks better, but we couldn't find any information about ClearML dataset versioning performance in comparison to DVC (for example caching speed, support for large datasets, is it based on git?).

Could you clarify this?

Thanks in advance.

**Comment by bmartinn** [comment]
Hi @senysenyseny16 

> ClearML dataset versioning performance in comparison to DVC 

Not sure by what you mean with performance comparison ? This is mostly limited by your d/l bandwidth and I/O, am I missing something ?

> Caching speed

As clearml-data is using differentiable storage caching supports per version caching meaning new dataset is using cached parent version, with the additional change set deployed on top. Implemented with soft-link if the filesystem supports it (this eliminates any redundant copy I/O while reproducing full directory trees)

Multi client caching is also supported, meaning you can set a shared folder as a cache for multiple nodes, speeding up the process of accessing frequently used datasets

> support for large datasets

Of course it does, it also splits large datasets into multiple stored files for faster and easier storafe, as well as parallel downloads for the best network performance

> is it based on git

No, it is based on clearml's ability to store large metadata artifacts as well as leverage object storage for both raw data and meta data storage

> Meta-data catalogues 

Clearml-data also supports dataset version and catalogue, this means you can add descriptions per dataset or version, add tags and search based on any version/name/comment/tag). This means not only you have a visual representation of the dataset lineage you can also get specific version based on any query parameter (i.e. not just based on unique ID)

> Visualization

With the latest version of clearml-data users can add any visualization to their datasets, helping with visibility and quick understanding of the type of content you have in every dataset / version

> Comparison

Comparing datasets is as easy as comparing experiments, you can quickly understand the files that were changed as well as the code base that created a specific dataset (image preprocessing code creating the dataset itslef)

> Lineage

Every clearml Task using a dataset will automatically list the UID of the dataset, meaning tracing back model training and data connection is as easy as it gets.

**Comment by senysenyseny16** [comment]
@bmartinn thanks for your reply.

> Not sure by what you mean with performance comparison ? This is mostly limited by your d/l bandwidth and I/O, am I missing something ?

For example caching performance.
I tested `clearml-data add` command on COCO validation part vs `dvc add` command, but I think dvc makes additional work and times listed below it is not comparable.

```
time clearml-data add --files /path/to/datasets/coco/val2017
clearml-data - Dataset Management & Versioning CLI
Adding files/folder/links to dataset id 9d882e7837bc48c2be443aad8399549c
Generating SHA2 hash for 5000 files
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 5000/5000 [00:09<00:00, 517.15it/s]
Hash generation completed
5000 files added

clearml-data add --files /path/to/datasets/coco/val2017  2.94s user 3.90s system 60% cpu 11.252 total
```

```
time dvc add /path/to/datasets/coco/val2017
100% Adding...|███████████████████████████████████████████████████████████████████████████████████|1/1 [00:29, 29.34s/file]

real    0m31.603s
user    0m17.674s
sys     0m4.816s
```

>Visualization. With the latest version of clearml-data users can add any visualization to their datasets, helping with visibility and quick understanding of the type of content you have in every dataset / version

Where can I find documentation about this feature?

**Comment by erezalg** [comment]
@senysenyseny16,

You can find info regarding dataset visualization [here](https://clear.ml/docs/latest/docs/webapp/datasets/webapp_dataset_viewing)

**Comment by senysenyseny16** [comment]
@erezalg thanks!
