### ISSUE TITLE
clearML>1.4.1 overrides UI config.yaml

### ISSUE THREAD

**Issue by guatavita** [allegroai/clearml#751]
Hello,

## Describe the bug
clearML>1.4.1 systematically overrides the config.yaml provided in the UI with the one from the repository branch/commit ID, even with _allow_omegaconf_edit_ = True

## Expected behaviour
clearML==1.4.1 works as expected (i.e. does not override the UI values), 1.6.4 systematically overrides the UI config.yaml which necessitate a specific commit ID per run (using Kubernetes workflow).

If you need more information, let me know.

Thanks,

**Comment by jkhenning** [comment]
Hi @guatavita ,

I'm not sure I understand the issue - can you explain the use-case and exact flow?

**Comment by guatavita** [comment]
Hello @jkhenning,

One use case would be to clone an experiment in the clearML UI and modify the config.yaml to change some model hyperparameters. However, when using clearML>1.4.1, this config.yaml is reset to what it is defined in the github repo (from which clearml is pulling the source codes) everytime we run the experiment. 

When using clearML==1.4.1 we don't have any issue and we can have experiment-specific config.yaml that were manually modified in the UI.

Hope this is a bit clearer.

![image](https://user-images.githubusercontent.com/17003129/186590238-278886c9-9955-4736-9acb-72fec5a8c101.png)

![image](https://user-images.githubusercontent.com/17003129/186590133-8da61c68-7a00-40bc-b8eb-e0e78dbcda2a.png)

**Comment by erezalg** [comment]
Hi @guatavita,

Let me see if I got it right.
You use Hydra to manage your configuration, and you save it in a repository.
Your script loads it and reads values from it, and ClearML automagically fetches it.

Now you clone the experiment, modify the script, and send it for execution on a worker, but the values you get are not the ones that should have been overriden from the UI, but the original ones stored in the git repo file.

Did I get this right? 

If so this is indeed strange and shouldn't happen :) I'll try to reproduce

**Comment by guatavita** [comment]
Yes that's it ! A bit of a specific workflow we use but it is working well for us right now.

Not sure if it is a clearml-agent issue though.

Thanks for looking into it.

**Comment by erezalg** [comment]
@guatavita,

Thanks :) I was able to reproduce the issue. Will work on a fix!

**Comment by guatavita** [comment]
Hello @erezalg,

Friendly reminder if you have any update? This prevent us from updating our clearml version to enjoy some other soved issues :)

Best!

**Comment by erezalg** [comment]
Hi @guatavita,

Unfortunately this did not make it into the version that's about the be released.
I will check if we can release an RC on that

**Comment by guatavita** [comment]
Hello @erezalg 

Any update on this? 

Best,

**Comment by erezalg** [comment]
Hi @guatavita,

The plan is to have this issue fixed in our next release!

I'll update here once it's out.

**Comment by qwaxys** [comment]
@guatavita this should now be fixed in the new release 1.8.1. 
If you have any questions or feedback, feel free to let us know!

**Comment by guatavita** [comment]
Thanks guys, it works fine so far, I'll reopen if needed!
