### ISSUE TITLE
How to specify local directories for the databases and storage, other than the default, in self-hosted ClearML-server

### ISSUE THREAD

**Issue by mikel-brostrom** [allegroai/clearml#764]
## Describe the bug
I have a 32GB disk (/dev/sdb1) only meant for the OS. The default self-hosted ClearML-server behavior is that it stores the data under this disk (`/`) which makes the server crash, as it quickly becomes full. Is there any good way of changing the experiment data destination to for example another attached disk (`/datadrive`)?

I tried to create the DB related paths on another disk:

```bash
➜  ~ sudo mkdir -p /datadrive/clearml/data/elastic_7
sudo mkdir -p /datadrive/clearml/data/mongo_4/db      
sudo mkdir -p /datadrive/clearml/data/mongo_4/configdb
sudo mkdir -p /datadrive/clearml/data/redis     
sudo mkdir -p /datadrive/clearml/logs           
sudo mkdir -p /datadrive/clearml/config         
sudo mkdir -p /datadrive/clearml/data/fileserver
```

and set the DB path accordingly under my `docker-compose.yml` file:

```bash
volumes:
    - /datadrive/clearml/logs:/var/log/clearml
    - /datadrive/clearml/config:/opt/clearml/config
    - /datadrive/clearml/data/fileserver:/mnt/fileserver
```

But when I try to access the server I get the following message:

```bash
Server Unavailable
The ClearML server is currently unavailable.
Please try to reload this page in a little while.
If the problem persists, verify your network connection is working and check the ClearML server logs for possible errors
```

**Comment by jkhenning** [comment]
Hi @mikel-brostrom, did you change all the volumes in the docker-compose file? Can you share it?

**Comment by mikel-brostrom** [comment]
I found the issue. When checking 

```bash
docker ps
```

the mongodb container was restarting continuously. After checking 

```bash
docker logs  clearml-mongo
``` 

I could see an `Operation not permitted error`. Then I checked the permissions my folders

```bash
➜  ~ sudo mkdir -p /datadrive/clearml/data/elastic_7
sudo mkdir -p /datadrive/clearml/data/mongo_4/db      
sudo mkdir -p /datadrive/clearml/data/mongo_4/configdb
sudo mkdir -p /datadrive/clearml/data/redis     
sudo mkdir -p /datadrive/clearml/logs           
sudo mkdir -p /datadrive/clearml/config         
sudo mkdir -p /datadrive/clearml/data/fileserver
```

 and saw that 

```
sudo chown -R 1000:1000 /mnt/clearml
```

had no effect on the permissions due to some disk configuration. I ended up setting up a ClearML-exclusive disk on my VM and everything got solved
