### ISSUE TITLE
clearml versions >= 1.6.3 only allow semantic versioning for Datasets

### ISSUE THREAD

**Issue by HeleneFabia** [allegroai/clearml#776]
I observed that when I try to get a dataset, clearml >= 1.6.3 doesn’t allow YYYY-MM-DD format for the version argument anymore. For example, when running `Dataset.get("DatasetProject", "DatasetName", version="2022-09-07")`, I get the following error: `clearml.utilities.version.InvalidVersion: Invalid version: '2022-09-07'`. Apparently, it's only allowed to use semantic versions for Datasets anymore. However, this would mean that now every dataset that doesn’t have a semantic version cannot be loaded any longer. I would have to re-upload every dataset with a reformatted version.

**Comment by erezalg** [comment]
Hi @HeleneFabia,

thanks :smile:, we saw that too. an RC is in the works!

**Comment by pollfly** [comment]
Hey @HeleneFabia! Just letting you know that this issue has been resolved in the recently released [v1.7.0](https://github.com/allegroai/clearml/releases/tag/v1.7.0). Let us know if there are any issues :)

**Comment by jkhenning** [comment]
Closing this issue. Please reopen if it's still relevant.
