### ISSUE TITLE
Remove Dataset on UI does not auto removing object on s3 MinIO storage too?

### ISSUE THREAD

**Issue by muhammadAgfian96** [allegroai/clearml#784]
Hi, 
i am using:
Server : self hosted
ClearML SDK Version 1.7.1rc0
ClearML Server Version: WebApp: 1.6.0-213 • Server: 1.6.0-213 • API: 2.20
Python Version 3.10.4
OS Linux

When we do successfully remove dataset in UI/Web Clearml, i check my MinIO s3, the dataset still there and consume some space.is that expected? how i can remove dataset but also remove in s3 storage too.

Thanks.

**Comment by muhammadAgfian96** [comment]
https://clearml.slack.com/archives/C028LNAAR5H/p1663754915034069

**Comment by erezalg** [comment]
Hi @muhammadAgfian96,

At the moment, ClearML does not remove the data stored on S3 (only on files server).
We already have a plan to add such feature and it should be released in one of the coming releases.

We'll update here when it is out!
