### ISSUE TITLE
ClearML stuck in a loop detecting Models

### ISSUE THREAD

**Issue by ilisparrow** [allegroai/clearml#788]
Thank you for helping us making ClearML better!

## Describe the bug

For some reason clearML detects many models. That are not models, and id doesn't execute the script

## To reproduce
I have a training code for a neural network that I tried to add ClearML to. 
I just have a basic task setup

## Expected behaviour
![image](https://user-images.githubusercontent.com/4880273/192530424-fc16af54-5d02-4a40-8156-a15da909dcce.png)

It should not get stuck in this loop. 
I would like to deactivate the automatic model detections and only manually add one

## Environment
* self hosted 
* clearml==1.7.0
*  WebApp: 1.7.0-229 • Server: 1.7.0-229 • API: 2.21 
* Python Version 3.7.11
*  Ubuntu 22.04
## Related Discussion
If this continues a slack thread, please provide a link to the original slack thread.

**Comment by ilisparrow** [comment]
In the current project I am generating it caches the picture in *.pt format to train faster. 
But the directory is outside of the one where the training code is, and also outside of the git repository.

**Comment by eugen-ajechiloae-clearml** [comment]
Hi @ilisparrow! Please see the `auto_connect_frameworks` parameters in `Task.init`: https://clear.ml/docs/latest/docs/references/sdk/task/#taskinit. Basically, you can control which models are logged by ClearML by specifying a wildcard. For example:

```py
Task.init(auto_connect_frameworks={"pytorch": ["/path/to/your/model/dir/*.pt"]})
```

Or to disable the model logging, just pass an empty string:

 ```py
Task.init(auto_connect_frameworks={"pytorch": [""]})
```

**Comment by ilisparrow** [comment]
Hello, 
That's exactly what I was looking for, thanks. 
THank you for the framework !
I am closing this :)
