### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe - When working with torch dataloader

### ISSUE THREAD

**Issue by Louis-Dupont** [allegroai/clearml#790]
## Describe the bug
Instantiating clearml.Task along with a torch dataloader setup to load data in parallel (num_worker=8) makes one of my subprocess to crash at the end of every training epoch:
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/35190946/193457814-64530b36-1ce4-4667-a8a8-5d1b01f08d6e.png">

How I instantiate clearml.Task:
```python
task = Task.init(
            project_name=project_name,
            task_name=experiment_name,
            continue_last_task=0,           
            auto_connect_arg_parser=False,
            auto_connect_frameworks=False,
            auto_resource_monitoring=False,
            auto_connect_streams=False,
)
```

Note that:
- My code works all fine if I just don't instantiate clearml.Task
- When I work with a lower number of worker (num_worker<=1) it seems to work fine
- I have this crash with only one of my dataset, it seems to work perfectly on all my other datasets

## Investigation
I found out that clearml overwrites both os.fork and BaseProcess.run, which made me come up with a dirty workaround for my code:
```python
...
import os
from multiprocessing.process import BaseProcess

default_fork, default_run = os.fork, BaseProcess.run
task = Task.init(...)
os.fork, BaseProcess.run = default_fork, default_run
```

With this code I don't have the broken pipe error, and it seems that I still manage to upload everything I want on the clearml server.
That being said, I guess there must be a cleaner way to avoid this bug, and I am also afraid of side effects that this workaround might have.

## Environment
* Server type: self hosted
* ClearML SDK Version: 1.7.1
* Python Version: 3.8.13
* OS: Linux

**Comment by jkhenning** [comment]
Hi @Louis-Dupont,

Thanks for reporting this - I'm assuming that for some reason the background process of the Logger died.

Is the crash happening at the end of the entire training process? meaning are you trying to stop it and then one of the dataloader subprocesses dies after the logger-subprocess and hence the crash?

We will work on reproducing and resolving it and update you when we have an RC (if you have any more insight on how to reproduce it we will appreciate any hint 🙂)

If you'd like a workaround meanwhile, you can use threads for logger reporting:
```python
Task._report_subprocess_enabled = False
task = Task.init(...)
```

**Comment by pollfly** [comment]
Hey @Louis-Dupont! Just letting you know that this issue has been resolved in the recently released [v.1.7.2](https://github.com/allegroai/clearml/releases/tag/v1.7.2). Let us know if there are any issues :)

**Comment by Louis-Dupont** [comment]
Hi, thanks for your answers! I tried both solutions but I still got the same error message.
I don't manage to isolate the error and to reproduce it with a simple example, so for now I am just working with my workaround and it seems to not give me issues, even though I guess it might lead to unexpected behaviors.

**Comment by eugen-ajechiloae-clearml** [comment]
Hi @Louis-Dupont ! I tried reproducing by running the code below, but no luck :(.
Can you please provide a script that would reproduce your issue?
```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
from torchvision.datasets import CIFAR10

from mmcv.parallel import MMDataParallel
from mmcv.runner import EpochBasedRunner
from mmcv.utils import get_logger
from clearml import Task


class Model(nn.Module):

    def __init__(self):
        super(Model, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        self.loss_fn = nn.CrossEntropyLoss()

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def train_step(self, data, optimizer):
        images, labels = data
        predicts = self(images)  # -> self.__call__() -> self.forward()
        loss = self.loss_fn(predicts, labels)
        return {'loss': loss}


if __name__ == '__main__':
    task = Task.init(
                project_name="test_name",
                task_name="test_name",
                continue_last_task=0,           
                auto_connect_arg_parser=False,
                auto_connect_frameworks=False,
                auto_resource_monitoring=False,
                auto_connect_streams=False,
    )
    model = Model()
    if torch.cuda.is_available():
        model = MMDataParallel(model.cuda(), device_ids=[0])

    # dataset and dataloader
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
    ])
    trainset = CIFAR10(
        root='data', train=True, download=True, transform=transform)
    trainloader = DataLoader(
        trainset, batch_size=128, shuffle=True, num_workers=8)

    optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)
    logger = get_logger('mmcv')
    # runner is a scheduler to manage the training
    runner = EpochBasedRunner(
        model,
        optimizer=optimizer,
        work_dir='./work_dir',
        logger=logger,
        max_epochs=4)

    # learning rate scheduler config
    lr_config = dict(policy='step', step=[2, 3])
    # configuration of optimizer
    optimizer_config = dict(grad_clip=None)
    # configuration of saving checkpoints periodically
    checkpoint_config = dict(interval=1)
    # register hooks to runner and those hooks will be invoked automatically
    runner.register_training_hooks(
        lr_config=lr_config,
        optimizer_config=optimizer_config,
        checkpoint_config=checkpoint_config)

    runner.run([trainloader], [('train', 1)])
```

**Comment by paul-ang** [comment]
I am having the same error as OP. I am using PyTorch Lightning.

**Environment**
Python Version: 3.9.5
OS: Linux
clearml==1.11.1
torch==2.0.1
pytorch-lightning==2.0.4
