### ISSUE TITLE
Pyplot/Matplotlib incorrect line labels and colors

### ISSUE THREAD

**Issue by vultix** [allegroai/clearml#791]
## Describe the bug
Lines are incorrectly labeled and colored when created via matplotlib/plotly and reported to clearml.

## To reproduce
```python
from matplotlib import pyplot as plt
from clearml import Task

task = Task.init(project_name='examples', task_name='missing-pyplot-colors')

fig = plt.figure()
plt.plot([1, 2, 3, 4], color="red", label="red")
plt.plot([4, 3, 2, 1], color="blue", label="blue")
plt.title("Example Plot")
plt.legend()
fig.show()
```

## Expected behaviour
The output chart should have a correct legend and be correctly colored:
<img width="629" alt="image" src="https://user-images.githubusercontent.com/5114062/193462819-5ead0198-6fe5-4e56-bc58-7d9aadcac34c.png">

Instead, this is what shows up in clearml:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/5114062/193462831-a5aa6b4e-8c92-4a00-99ef-65cc04de92d6.png">

Note that both lines are labeled 'blue', and neither are colored.

## Environment
* Server type app.clear.ml
* ClearML SDK Version 1.7.1
* Python Version 3.9.12
* OS Macos

**Comment by erezalg** [comment]
Hi @vultix,

Thanks for reporting this!
We've released an RC version that should solve this issue, You can install it by running: 
pip install clearml==1.7.2rc0

**Comment by jkhenning** [comment]
Closing this issue. Please reopen if it's still relevant.
