### ISSUE TITLE
Cloud you give more details about Task.init

### ISSUE THREAD

**Issue by edenbuaa** [allegroai/clearml#799]
ClearML is a great and new project to me.  I try to find more detail about "from here on everything is logged automatically" in the examples's `Task.init(...)` function, but still got confused.

I want to learn the essence of the working mechanism about the task.init function.  Cloud anyone explain it or a document provided?

thanks.

**Comment by jkhenning** [comment]
Hi @edenbuaa,

In short, the code behind `Task.init()` patches into all available supported packages (such as tensorboard, matplotlib and others) and intercepts all logged information that can be reported to the ClearML server for visualization.

**Comment by edenbuaa** [comment]
@jkhenning thanks for reply.

Was this function implemented by some library, like Mock?

**Comment by jkhenning** [comment]
> Was this function implemented by some library, like Mock?

No, since we need to maintain the behavior of the supported packages (i.e. we do not interrupt saving to file etc., we just extend the behavior), actual patching and no mocking is required.
