### ISSUE TITLE
Configuring s3 credentials from IAM role

### ISSUE THREAD

**Issue by davidas1** [allegroai/clearml#80]
Hi,

We are trying to use trains on AWS instances, and we use IAM roles to control the permissions of the instance (i.e. writing/reading to and from s3 buckets).
How can we configure trains to use these type of credentials?

**Comment by bmartinn** [comment]
Hi @davidas1 ,
Unfortunately *Trains*  currently supports only key/secret for storage access (including S3).
You can however generate key/secret for a specific user and have *Trains* use that.

See AWS documentation [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey)

Or simply run:
`$ aws iam create-access-key --user-name Bob`

And configure *Trains* with the returned credentials `AccessKeyId` / `SecretAccessKey`

**Comment by manojlds** [comment]
Is it not possible to support the credentials chain from Boto? This is a blocker for me as I can't use keys as per infosec policy.

**Comment by bmartinn** [comment]
@manojlds 
would this kind of implementation work in your scenario ?
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-api.html
