### ISSUE TITLE
Freezing on connection break

### ISSUE THREAD

**Issue by frolovconst** [allegroai/clearml#805]
## Description
In case of a broken connection to the API server, the function [Task._delete_artifacts()](https://github.com/allegroai/clearml/blob/25df5efe74972624671df2ae97a3c629eb0c5322/clearml/backend_interface/task/task.py#L1360) freezes the main thread. If you try to delete an artifact using the function and the connection happens to be broken at the time, the code enters an [infinite loop](https://github.com/allegroai/clearml/blob/b598ee58666675d5b6ac775f30c682dd3fa6ec62/clearml/backend_interface/base.py#L57). The number of retries settings in the `api.http.retries` config section have no effect. And the [`raise_on_errors=False`](https://github.com/allegroai/clearml/blob/b598ee58666675d5b6ac775f30c682dd3fa6ec62/clearml/backend_interface/task/task.py#L1377) flag prevents the code from throwing an exception and moving on.

## To reproduce
```
task = Task.init(reuse_last_task_id=task_id, continue_last_task=0)
```
_Connection to the API server breaks_
```
delete_artifact(task, 'artifact_name')
task.close()
```

## Expected behaviour
I'm expecting that after a certain number of retries I get informed (e.g., in the form of an exception) about the failed artifact deletion attempt and my ML process can resume.  
To add some context, I need to implement a "keep N best" checkpoints logic. On top of that I need to be able to have different N-numbers for the local and remote storages. See the Slack discussion [here](https://clearml.slack.com/archives/CTK20V944/p1666110774455869).

## Environment
* Server type: self hosted
* ClearML SDK Version 1.7.2
* ClearML Server Version (Only for self hosted): 1.3.0-165
* Python Version 3.9.1
* OS Debian 10
## Related Discussion
[If this continues a slack thread, please provide a link to the original slack thread. ](https://clearml.slack.com/archives/CTK20V944/p1666110774455869)

**Comment by pollfly** [comment]
Hey @frolovconst! [v1.8.0](https://github.com/allegroai/clearml/releases/tag/v1.8.0) is now out with the `raise_on_errors` argument of the `Task.delete_artifacts()` method
