### ISSUE TITLE
clearml.Repository Detection - WARNING - Failed auto-generating package requirements: _PyErr_SetObject: exception SystemExit() is not a BaseException subclass

### ISSUE THREAD

**Issue by garymm** [allegroai/clearml#808]
## Describe the bug

At the end of my task I see this in the console:
```
clearml.Task - INFO - Waiting for repository detection and full package requirement analysis
clearml.Task - INFO - Repository and package analysis timed out (10.0 sec), giving up
clearml.Repository Detection - WARNING - Failed auto-generating package requirements: _PyErr_SetObject: exception SystemExit() is not a BaseException subclass
```

## To reproduce
Just running a simple task inside my repo seems to trigger this. I can't share the repo as it's closed source.

## Expected behaviour
No warning messages at the end.

## Environment
* Server type (self hosted \ app.clear.ml): app.clear.ml
* ClearML SDK Version: 1.7.2
* ClearML Server Version (Only for self hosted). Can be found on the bottom right corner of the settings screen.
* Python Version: 3.9.13
* OS (Windows \ Linux \ Macos): macOS

**Comment by garymm** [comment]
The `_PyErr_SetObject` warning doesn't happen consistently but it does seem like it's probably due to a real bug.

The timing out after 10 seconds does happen consistently in my repo.
I tried `vcs_repo_detect_async: false` in `clearml.conf` and task.Init takes an extra 4 minutes.
So whatever it's doing is just very very slow on my repo, which is not a huge repo (12k lines of python). Could it be trying to analyze code that's behind symlinks that are created by [Bazel](https://bazel.build)?
If so that might explain it. But those links are in `.gitignore`, so if this is the case, perhaps the repo detection should ignore anything in .gitignore?

Shall I open a separate bug about the performance so as to keep this one focused on the `_PyErr_SetObject` warning?

**Comment by erezalg** [comment]
Hi @garymm,

Yes, that indeed may be a result of the links.
We're going to fix the error so it does not stop you from working and just output an error.

I'll update here once it's out.
As for the slowness, we're still considering whether it's an issue in our mind or not as we intentionally analyze links and are not sure we have a good strategy of when to do it and when not.

**Comment by garymm** [comment]
If `vcs_repo_detect_async: true`, then the task runs but:
* prints the error messages shown above, and
* doesn't have the repository and package information

**Comment by erezalg** [comment]
@garymm,

I'll check regarding the missing repository information, but since, ATM, we are looking through the links, the package information might be empty as the thread that collects the requirements times out.

We'll look into the best method to not go through the links, but this may take additional time

**Comment by erezalg** [comment]
Hi @garymm,

Is it ok, if the vcs detection process times out, it will just prints an error and leave the environment field empty?

also, do you have any example code that creates links to external repos that times out the detection process? We'd like to reproduce this issue and make sure our solution behaves nicely :)

**Comment by garymm** [comment]
I think this should produce an example of the sym-links containing external code:
1. install bazel, follow instructions here https://bazel.build/install
2. 
```sh
git clone git@github.com:bazelbuild/rules_python.git
cd rules_python/examples/pip_parse
bazel build //...
```
That should set up several sym-links in the CWD starting with `bazel-`.
