### ISSUE TITLE
How to clear metric storage.

### ISSUE THREAD

**Issue by enessinanparildi** [allegroai/clearml#809]
Is there a way to free up the metric storage by deleting unnecessary metrics? I tried deleting tasks that I do not want to keep through the UI. But, this did not make any difference.

**Comment by erezalg** [comment]
Hi @enessinanparildi,

The metric usage is computed once a day, we suggest to wait 24h and then trying. Let us know if this doesn't work.

**Comment by enessinanparildi** [comment]
I deleted a bunch of experiments and then waited for more than 24h. The metric storage number is the same as before. So, this did not work.

**Comment by oren-allegro** [comment]
Hi @enessinanparildi,

Can you share your used_id or workspace_id (or email)?
Also, please note that there is a slack channel [slack channel](https://join.slack.com/t/clearml/shared_invite/zt-1j05dekn6-jVtbaGzFjckhd3IjCEmqJw) for supporting issues in clearml saas

**Comment by enessinanparildi** [comment]
I believe this is the workspace_id 81a4053f33274ebeb8016860bd1ee713.

**Comment by oren-allegro** [comment]
Hi @enessinanparildi,

It seems that your metrics usage is still high. This is usually due to large logs or plots. I will try to check if there are experiments that were deleted without freeing up their metrics. I'll update you if I find anything.
In the meantime - please see if there are any other experiments with large logs or plots that you can delete.

**Comment by oren-allegro** [comment]
Hi @enessinanparildi,

I checked - and the tasks that are left still contain a lot of events. These are the ids of tasks that use the most metrics:
e797fdaed39347d8b8f06fd4657e388b
1c9abffdf31344249ed2c167432884f7
8bd64c579ea940a88cefccd04879f1f2
eab6c57ec81e46b69366d84e3008b9ff
f23c1d782e044fd7928e5565d408d158
74ba5107efa74cd395d6f1368c05beef
25f8fbce2f874ae2a557c66e9a245e50
a9d6690397154dae9b755b30fe17cade
82beb9ae3b074346a02f2bbcb55753c1

I would advise you to delete some of those, and check if you can make your code save fewer events (mainly logs and plots). Alternatively, your can upgrade to a pro tier (this is not free) to get more space.

**Comment by jkhenning** [comment]
@enessinanparildi closing this. please reopen if still relevant.
