### ISSUE TITLE
Dataset: Enable access to the same s3 bucket under different hosts

### ISSUE THREAD

**Issue by john-zielke-snkeos** [allegroai/clearml#818]
## Proposal Summary
In order to use ClearML for the management of datasets, an option is missing to specify the host under which a bucket can be accessed in the config without having to specify this host in the path to the object, for example when using `dataset.add_external_files(...)`.
E.g. I need to be able to call `my_dataset.add_external_files(source_url="s3://training_data/cifar/image1.jpg")` instead of `my_dataset.add_external_files(source_url="s3://miniohost:9000/training_data/cifar/image1.jpg")`.

#### Possible solution
This could be achieved by either a new parameter on a per-bucket level (e.g. sdk.aws.s3.credentials.require_explicit_hostname with a default of true) or by setting the hostname for all buckets (e.g. sdk.aws.s3.host).

## Motivation
Experiments need to run transparently on different agent setups. When there are agents in different environments where the same data is cached closer to the agents or only available at special endpoints which differ from environment to environment, I need to be able to control the host that is requested in each config of the agent and not have it hardcoded in the dataset. 

## Related Discussion
This (or a similar) feature was already [requested  previously](https://github.com/allegroai/clearml/issues/391), but closed because this would prevent a bucket with the same name to exist on e.g. AWS and a local minio server. This I guess would be a problem if you had different contents in those buckets. While this is true, the explicit requirement for this in certain situations as explained before is crucial for the transparent execution of experiments on different agents. I would recommend not to introduce this as a breaking change, but instead make this opt-in.

**Comment by erezalg** [comment]
Thanks @john-zielke-snkeos for the suggestion.

This indeed can be done.
Basically, what you want is a path substitution, on the clearml.conf level, correct?
So when you specify s3://training_data/more/more/more.jpg, you'll add before training_data a different path, based on the system.

We can add a parameter that when its set to "training_data: my_host" it will add my_host to calls fetching data from trainin_data bucket.

Does that seem to cover your need?

**Comment by john-zielke-snkeos** [comment]
Thanks for the reply! Yes that would be great! As a suggestion, maybe even with a wildcard, so buckets can be named sth like "clearmldata-mnist", enabling usage of a generic configuration. But this would just be the cherry on top. If there is a good place to put this, documentation for this approach would be great so it's easier to find while setting it up (I only came across the path substitutions while looking into the code)

**Comment by erezalg** [comment]
Hi @john-zielke-snkeos,
Can you maybe give a fuller explanation of what you had in mind regarding wildcards? 
And what path substitution feature are you referring to, when you say you stumbled upon the code? :smile: want to make sure we're talking about the same thing

**Comment by john-zielke-snkeos** [comment]
I figured out you can use sdk->storage->path_substitution already to add a substitution. This option is not documented anywhere though (apart from the code at/after clearml/storage/helper.py:~128 `path_substitution_config = 'storage.path_substitution'`).

I am not sure if this is good enough enough, especially since the current implementation (the prefix) does not support wildcards or regex. And even if it is, it would be good to mention this possibility somewhere in relation to using it for defining endpoints to access S3 buckets.
Feel free to ask if this doesn't fully answer your question.

**Comment by erezalg** [comment]
@john-zielke-snkeos, so does path_substition work for your use-case? I mean, can you specify the URL to be something generic, and substitute it on each machine?

Anyways, you're right and we should definitely document it

**Comment by john-zielke-snkeos** [comment]
Exactly, so far looks like it should work for the use case. Thank you!
