### ISSUE TITLE
Bug: StorageHelper.delete fails when used with Path substitutions

### ISSUE THREAD

**Issue by john-zielke-snkeos** [allegroai/clearml#825]
## Describe the bug
The function `clearml.storage.helper.StorageHelper.delete` does not honor the path substitution rules. While all upload/download functions call ```self._canonize_url(remote_path)``` first, delete does not. This leads to an error when uploading files using `Dataset.add_external_files(...)`, as it calls `clearml.storage.helper.StorageHelper.check_write_permissions(...)` which calls `clearml.storage.helper.StorageHelper.delete`. The previous call to `StorageHelper.upload_from_stream(...)` succeeds with the path substitution.

## To reproduce
Not working code, as I cannot reproduce internal paths etc on other setups
```
from clearml import Dataset
from clearml.storage.helper import StorageHelper

StorageHelper.add_path_substitution("s3://minio.server:8000","s3://minio-instance.myintranet.net:8000")

# Preprocessing code here
output_uri = "s3://minio.server:8000/data/clearml"
dataset = Dataset.create(
    dataset_name="test-dataset",
    dataset_project="test-project",
    dataset_version="1.1",
    output_uri=output_uri,
    description="Test dataset",
)

dataset.add_external_files(
            source_url="s3://minio.server:8000/data/my-file.txt",verbose=True
        )
dataset.upload()
dataset.finalize()
```

## Expected behaviour
The path is also rewritten for delete and check access succeeds.

## Environment
* Server type: self hosted
* ClearML SDK Version: 1.7.2
* ClearML Server Version: 1.7.0-232
* Python Version: 3.8.3
* OS: Windows

**Comment by erezalg** [comment]
Hi @john-zielke-snkeos ,

Thanks for investigating this! this makes sense. 
Would you care to open a [PR](https://github.com/allegroai/clearml/blob/master/docs/contributing.md)? we always value community contribution :smile:

**Comment by john-zielke-snkeos** [comment]
Thank you! I will try to do so, just want to make sure that I didn't get something wrong and that it might be intended behavior.
