### ISSUE TITLE
Migrate/upgrade ClearML to new deployment in another namespace k8s

### ISSUE THREAD

**Issue by schoenfbe** [allegroai/clearml#827]
## Proposal Summary
Hi, I don't know if a solution to this problem already exists, I at least was unable to find one:

We currently have ClearML deployed in kubernetes, but apparently everything done manually some time ago, which means it's neither properly managed nor could we restore it if it for some reason went down.

Now I've deployed a "clean" config that is managed by ArgoCD, and runs in another namespace (has to).

Can I migrate the data and configuration of the old deployment to the new one?

Old one is ClearML 3.0.4, new one is 4.2.0 (newest that our k8s supports)

I cannot use "helm upgrade", since it's not managed by helm, and the new deployment has to be in another namespace, so I'd be basicylla looking for a way to backup the whole old deployment and load it into the new one, alternatively deploying the same version (3.0.4) again, mirroring data to that, and then upgrading to 4.2.0.

Is that possible?

## Motivation
Want/need to deploy new ClearML deployment in another namespace in kubernetes, but keep configuration and more importantly old experiment data from existing deployment.

## Related Discussion

**Comment by jkhenning** [comment]
@valeriano-manassero do you have a tip?

**Comment by valeriano-manassero** [comment]
The first issue to address is the pvc backups. How to backup them depends on the storage provider but usually can be done by Velero.
When you have your backups you can:
* deploy a brand new ClearML chart
* scale every deploy,ment/statefulset to replicas=0 (this will not remove new pvc/pv)
* restore file in new pvc
* scale back everything to replicas=1

I'm not 100% sure this will work but you can give a try.
