### ISSUE TITLE
Show numerical values for matrix

### ISSUE THREAD

**Issue by buti1021** [allegroai/clearml#832]
## Proposal Summary
Show numerical values for matrices uploaded with report_matrix()

## Motivation
Colors are nice, but numerical values help getting a deeper understanding, the values are available but one needs to hover and can the only see one value

Change this:
![image](https://user-images.githubusercontent.com/49496963/203420852-61ba58a3-ef9a-47c8-8b6c-8b2cff4070fb.png)

To something similar to this
![image](https://user-images.githubusercontent.com/49496963/203421020-7132f959-5bf5-40b2-b09c-d9642861995f.png)

**Comment by ainoam** [comment]
@buti1021 You can control the plot display parameters via the `extra_layout` parameter to report_matrix (see [here](https://github.com/allegroai/clearml/blob/master/clearml/logger.py#L706)).  
Specifically in this case, using the texttemplate parameter e.g. `logger.report_matrix(..., extra_layout = {'texttemplate': 'z: %{z}'})`

Is this what you need?

**Comment by buti1021** [comment]
Thats awesome, I missed that!

Have you thought about making that the default? When I read logger.report_matrix() I kinda expected to see the values of the matrix in the GUI and not some colorfication of it

**Comment by ainoam** [comment]
@buti1021 report_matrix/report_confusion_matrix specifically ["plot a heat-map matrix"](https://github.com/allegroai/clearml/blob/master/clearml/logger.py#L632). For printing a value table you should be using logger.report_table.
We're basically maintaining the default behaviour of plotly in this regard (i.e. values printed on explicit specification), which probably accommodates the majority of use cases.

**Comment by buti1021** [comment]
Alright
