### ISSUE TITLE
Raw String needed for re.match to Suppress Warning

### ISSUE THREAD

**Issue by daugihao** [allegroai/clearml#834]
## Describe the bug
There is a re.match regular expression which is not being specified as a raw string, leading to a warning being raised: https://github.com/allegroai/clearml/blob/762bc5325f790b0ba0614f4aefddc1f881a2644c/clearml/backend_api/session/jsonmodels/fields.py#L137

```
../.pyenv/versions/3.9.7/lib/python3.9/site-packages/clearml/backend_api/session/jsonmodels/fields.py:137
  /home/circleci/.pyenv/versions/3.9.7/lib/python3.9/site-packages/clearml/backend_api/session/jsonmodels/fields.py:137: DeprecationWarning: invalid escape sequence \w
    if not re.match('^[A-Za-z_](([\w\-]*)?\w+)?$', self.name):  # noqa: W605
```

## Expected behaviour
By prefixing the string with `r`, this warning would no longer be raised.

## Environment
MacOS Python 3.9.12

**Comment by erezalg** [comment]
Hi @daugihao,

Thanks a lot! Would you care to open a PR? :) We always appreciate community contribution!

**Comment by daugihao** [comment]
Hi @erezalg, I would be very happy to do so, but it looks like I don't have permission to create a branch. How should I create a PR?

**Comment by erezalg** [comment]
@daugihao,

What you can do is create a fork of the repository, commit your changes, and then open a PR merging your fork to ClearML.

**Comment by daugihao** [comment]
Great. I'll do that tomorrow morning when I'm at my laptop. Thanks for your help

**Comment by erezalg** [comment]
@daugihao 
You can also refer to our contribution guidelines which should help make the PR easier to merge :smile:
https://github.com/allegroai/clearml/blob/master/docs/contributing.md

**Comment by qwaxys** [comment]
#837 is merged so I'm closing this. Thanks for the contribution!
