### ISSUE TITLE
Cannot download Pytorch-Lightning checkpoints stored in ClearML

### ISSUE THREAD

**Issue by Bunoviske** [allegroai/clearml#850]
Hello,

After training my model using this framework, i cannot download the checkpoints stored as artifacts. In the UI, the download button is not enabled and when I try to get a local copy of the model, I receive this error without further explanation.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/mnt/c/Users/bruno/Documents/humanize/Cho.Ai/torchLightning/Pytorch-InstanceSegmentation.ipynb Cell 3 in <cell line: 1>()
----> [1](vscode-notebook-cell://wsl%2Bubuntu-20.04/mnt/c/Users/bruno/Documents/humanize/Cho.Ai/torchLightning/Pytorch-InstanceSegmentation.ipynb#Y121sdnNjb2RlLXJlbW90ZQ%3D%3D?line=0) model.get_local_copy(raise_on_error=True)

File ~/miniconda3/lib/python3.8/site-packages/clearml/model.py:489, in Model.get_local_copy(self, extract_archive, raise_on_error)
    487 if extract_archive and self._is_package():
    488     return self.get_weights_package(return_path=True, raise_on_error=raise_on_error)
--> 489 return self.get_weights(raise_on_error=raise_on_error)

File ~/miniconda3/lib/python3.8/site-packages/clearml/model.py:343, in BaseModel.get_weights(self, raise_on_error)
    334 """
    335 Download the base model and return the locally stored filename.
    336 
   (...)
    340 :return: The locally stored file.
    341 """
    342 # download model (synchronously) and return local file
--> 343 return self._get_base_model().download_model_weights(raise_on_error=raise_on_error)

File ~/miniconda3/lib/python3.8/site-packages/clearml/backend_interface/model.py:417, in Model.download_model_weights(self, raise_on_error)
    415     Model._local_model_to_id_uri[str(local_download)] = (self.model_id, uri)
    416 elif raise_on_error:
--> 417     raise ValueError("Could not retrieve a local copy of model weights {}, "
    418                      "failed downloading {}".format(self.model_id, uri))
    420 return local_download

ValueError: Could not retrieve a local copy of model weights ac36a0ff3db042e0a4026687ca5601f9, failed downloading file:///content/models/stage2-epoch=14-map=0.18.ckpt
```

If I check pytorch-lightning examples from ClearML, the checkpoints are downloadable. Is this a bug in the library? How to fix this? I lost some trained models, since I cannot download them :(

I am using linux, python 3.8, pytorch-lightning==1.7.7, clearml==1.8.3 and app.clear.ml.

Many thanks!

**Comment by jkhenning** [comment]
Hi @Bunoviske,

I think the issue is your models were simply not uploaded anywhere - by default they are stored locally. If you wish to upload them somewhere (so that they will later be downloadable and accessible from other places), you need to either set the `default_output_uri` setting in the clearml.conf file ([here](https://github.com/allegroai/clearml/blob/90f30e8d9a5ca9a1afa6b2e5ffccb96b0afe9c78/docs/clearml.conf#L181)), or pass an `upload_uri` argument to `Task.init()`. The value you should use is either the ClearML fileserver address (as it appears in the `api.files_server` setting), or a path to some remote object storage bucket (such as `s3://my-bucket-name`), assuming you have this bucket set up and you've set the proper credentials in your clearml.conf file.

**Comment by Bunoviske** [comment]
Hello @jkhenning,

thank you so much for the quick response, indeed this was the case. But I admit it is quite confusing, because in the framework example, the `Task.init()` does not have `output_uri=True` and the models are actually downloadable, which made me confused.  And many times in the ClearML documentation and examples, you say: 
    
    _Connecting ClearML with the current process, from here on everything is logged automatically_

This makes me understand that everything is logged automatically to ClearML server, specially because I see the models paths in the website. My feedback is to either make more explicit in the documentation that the models are stored locally by default, or change the default to `output_uri=True`. But since in ClearML everything is done automatically, I think setting `output_uri=True` could be a good idea.
