### ISSUE TITLE
Can not create Dataset offline

### ISSUE THREAD

**Issue by Vadim2S** [allegroai/clearml#854]
## Describe the bug

Can not create Dataset in offline mode

## To reproduce

Code:
```
Task.set_offline(offline_mode=True)
Task.init(project_name='project', task_name="upload", task_type=TaskTypes.custom, output_uri=True)
...
def main(args):
    dataset = Dataset.create(    # Error Here
        dataset_name=args.corpus_name,
        dataset_project=args.project_name,
        description=args.corpus_description,
        use_current_task=True
    )
    dataset.add_files(path=args.corpus_dir)
    dataset.upload()
    dataset.finalize()
```

## Expected behaviour

Dataset in local offline folder or "not implemented yet" error.

## Actual behaviour

Error:
```
  File "...\clearml\backend_interface\task\hyperparams.py", line 129, in edit_hyper_params
    if res.ok():
AttributeError: 'NoneType' object has no attribute 'ok'
```

## Comment
This is really error. Clearml expected res.ok() as result in any case (good or bad) but got None :
```
        res = self.task.session.send(
            tasks.EditHyperParamsRequest(
                task=self.task.task_id,
                hyperparams=props.values(),
                replace_hyperparams=replace,
            ),
        )
        if res.ok():
            self.task.reload()
            return True
        return False
```

## Environment
* Server type:  none - offline mode
* ClearML SDK Version: latest, clearml 1.8.3 
* Python Version: 3.9
* OS: Windows 10

**Comment by erezalg** [comment]
Thanks @Vadim2S for reporting this!

This indeed seem to not be supported, but there isn't a good reason why it shouldn't :)
We'll update here once a fix is out.

**Comment by pollfly** [comment]
Hey @Vadim2S! [v1.11.0](https://github.com/allegroai/clearml/releases/tag/v1.11.0) is now out, supporting offline mode for ClearML Datasets.

**Comment by jkhenning** [comment]
@Vadim2S closing this. Please reopen if required.
