### ISSUE TITLE
matplotlib image plot using imshow() doesn't result in an image upload

### ISSUE THREAD

**Issue by iryek219** [allegroai/clearml#870]
## Describe the bug
I'm following ClearML documentation at https://github.com/allegroai/clearml/blob/master/examples/frameworks/matplotlib/jupyter_matplotlib_example.ipynb

I found all three image plots in the notebook didn't appear on clearml web app. 

## To reproduce
Exact steps to reproduce the bug. Provide example code if possible.

The code below doesn't upload any image on the clearml web app.

task = Task.init(project_name='examples', task_name='Matplotlib example 7')
m = np.eye(256, 256, dtype=np.uint8)
plt.imshow(m)
plt.show()
task.close()

While following code upload the plot without any problem.

task = Task.init(project_name='examples', task_name='Matplotlib example 9')
m = np.eye(256, 256, dtype=np.uint8)
plt.plot(m[0],m[1])
plt.show()
task.close()

## Expected behaviour
What is the expected behaviour? What should've happened but didn't?

plt.imshow() uploads the result image on the clearml web app.

## Environment
WebApp: 1.9.1-312 • Server:  • API: 2.23

* Server type (self hosted )
* ClearML SDK Version: 1.9.0
* ClearML Server Version : 1.9.1-312 
* Python Version: 3.9.13
* OS : Server(MacOS), Client: (Chrome on Windows), Jupyterlab Server: (Ubuntu 20.04)

## Related Discussion
If this continues a slack thread, please provide a link to the original slack thread.

**Comment by jkhenning** [comment]
Hi @iryek219,

What do you see in the experiment page in the WebApp? Do you see the experiment? Do you see the images but the links are broken, or do the images not appear at all? Can you share a screen-shot?

**Comment by iryek219** [comment]
Hi @jkhenning,

Experiments are created and displayed in the WebApp without any problem. As the attached screenshots show, images don't appear at all.
 
An experiment with no image
![ex7](https://user-images.githubusercontent.com/5159861/211245102-51dcc89f-cee4-44bc-9e12-68284a1a8fce.png)
![ex7_client](https://user-images.githubusercontent.com/5159861/211245111-94f4cdec-8a3a-40ec-a264-0a188ee86f43.png)

A successful case
![ex9](https://user-images.githubusercontent.com/5159861/211245264-50564a39-0ba2-4284-832a-2b1c1d491bc4.png)
![ex9_client](https://user-images.githubusercontent.com/5159861/211245271-4fec150f-2c32-442a-8b92-ba8df1df0fb6.png)

**Comment by eugen-ajechiloae-clearml** [comment]
Hi @iryek219! Looks like we attempt to report the plot, but we silently fail. We will need look into this.

**Comment by guatavita** [comment]
I think I observed similar problem moving from clearml 1.8.4 to 1.9.0. If more details can help:

Using:

```python
self.logger.experiment.add_figure(
    f"val_image_{self.global_step}_{batch_idx}",
    log_figure,
    self.global_step,
)
```

With `log_figure` being the figure from `plt.gcf()` I get the following warning during training and no figure uploaded in my clearML task.

```
2023-01-14 10:00:33,018 - clearml - WARNING - Failed decoding debug image [1500, 1500, 3]
2023-01-14 10:00:33,019 - clearml - WARNING - Error: cannot reshape array of size 1 into shape (1500,1500,newaxis)
```

**Comment by ShiraBaronn** [comment]
Hi,
I have the same error (Failed decoding debug image) and found the change in the new version that causes this:
in the file: clearml/binding/frameworks/tensorflow_bind.py
```
    def _decode_image(self, img_str, width=None, height=None, color_channels=None):
        # noinspection PyBroadException
        try:
            if isinstance(img_str, bytes):
                imdata = img_str
            else:
                imdata = base64.b64decode(img_str)
            output = BytesIO(imdata)
            im = Image.open(output)
            # if this is a GIF store as is
            if getattr(im, 'is_animated', None):
                output.close()
                fd, temp_file = mkstemp(
                    suffix=guess_extension(im.get_format_mimetype()) if hasattr(im, 'get_format_mimetype')
                    else ".{}".format(str(im.format).lower())
                )
                with open(fd, "wb") as f:
                    f.write(imdata)
                return temp_file
            output.close()
            if height is not None and height > 0 and width is not None and width > 0:
                val = np.array(im).reshape((height, width, -1)).astype(np.uint8)
            else:
                val = np.array(im).astype(np.uint8)
```
there is a missing line before the `output.close()`, and therefore `np.array(im)` is using a closed file and this crashes.
in the older version (1.7.2) it was: 
```
image = np.asarray(im)
output.close()
```
please check that, thanks

**Comment by iryek219** [comment]
The problem was that I used the wrong value for CLEARML_FILE_HOST environment variable like below. 

%env CLEARML_WEB_HOST=http://192.168.1.145
%env CLEARML_API_HOST=http://192.168.1.145:8008
%env CLEARML_FILES_HOST=**_undefined_**

Setting the right value fixed the problem. So, I'll close the issue.

**Comment by dolevq** [comment]
any updates on this? I manage to log regular plots but when I'm using plt.imshow() I don't see anything in clearml.
When I excplictly used task.logger.report_matplotlib_figure then I see an empty plot in clearml

**Comment by ainoam** [comment]
@dolevq Do note this issue is closed, so there're probably no updates coming...
If nothing in this thread helps you, it would be best to open a new issue - Make sure to provide as much information as you can, as described in ["reporting issues"](https://github.com/clearml/clearml/blob/master/CONTRIBUTING.md#reporting-issues)
