### ISSUE TITLE
Update TriggerScheduler docs

### ISSUE THREAD

**Issue by InCogNiTo124** [allegroai/clearml#881]
## Proposal Summary
As per the discussion on your Slack workspace, I propose updating the [TriggerScheduler](https://clear.ml/docs/latest/docs/references/sdk/trigger#add_task_trigger) docs to include a list of all the valid statuses.

## Motivation
We were working on ClearML triggers and we noticed that there was no `"aborted"` status. Having that info in the docs would have greatly helped us.

**Comment by ainoam** [comment]
Thanks for suggesting @InCogNiTo124!

Do note that tasks status definitions are already mentioned in the Task references (e.g. [task.get_status()](https://clear.ml/docs/latest/docs/references/sdk/task#get_status)) though it would probably not hurt mentioning it in [TriggerScheduler](https://clear.ml/docs/latest/docs/references/sdk/trigger#add_task_trigger) as well.

**Comment by InCogNiTo124** [comment]
hey @ainoam while we're at it: do the `task.get_status()` docs look a bit broken to you as well? The list starts in plaintext and then converts to code, I don't think that should be happening...

**Comment by ainoam** [comment]
Indeed it does. Thanks for spotting.

**Comment by InCogNiTo124** [comment]
Great, thank you! Closing as it's resolved.
