### ISSUE TITLE
"Clone Experiment" dialog sizing issue in Windows

### ISSUE THREAD

**Issue by constructor-igor** [allegroai/clearml#89]
https://demoapp.trains.allegro.ai/projects/087f765c846c4c76a7e9f3d035667d82/experiments?columns=type&columns=name&columns=status&columns=project.name&columns=user.name&columns=started&columns=last_update&columns=last_iteration&order=last_update

![image](https://user-images.githubusercontent.com/1849690/73000374-706c6080-3e09-11ea-855c-eea9734a1ef1.png)

**Comment by bmartinn** [comment]
Yes, definitely a web bug, we are aware we need to work on adapting to more screen resolutions :(
(I'm assuming a bit of zoom-out (`ctrl -`) will solve the issue.

May I ask what's the screen resolution and what OS / Browser you are using?

**Comment by constructor-igor** [comment]
as **workaround** it's ok

![image](https://user-images.githubusercontent.com/1849690/73006233-f5a84300-3e12-11ea-82d3-c98f5f00985b.png)

**Comment by bmartinn** [comment]
@constructor-igor, thank you for the screen grab, I'm guessing its the 125% scaling...
I'm hoping that by the next *trains-server* version it will be solved :)

**Comment by allegroai-git** [comment]
Closing as this was handled in Trains Server v0.14.0
