### ISSUE TITLE
None value in Click cls._args.keys() 

### ISSUE THREAD

**Issue by chengzegang** [allegroai/clearml#902]
## Describe the bug
I dont know how Click implements its argument parser but clearly it is possible that ```None``` key in its _args dictionary. In ClearML, there is one line of codes that requires to sort all these argument and ```None``` key fails. The line is located atclick_bind.py line 43:
```
@classmethod
    def args(cls):
        # remove prefix and main command
        if cls._num_commands == 1:
            cmd = sorted(cls._args.keys())[0]   # <------ here
            skip = len(cmd)+1
        else:
            skip = 0

```
The most naive way to get ride of this is just filter out `None` keys in the `cls._args` before sorting.

## To reproduce
test.py
```
import click
from clearml import Task  # type: ignore


def run():
    cli = click.CommandCollection(sources=[test_cli])
    cli()


@click.group("test")
def test_cli():
    pass


@test_cli.command(name="test")
@click.option("--root", "-r", type=str, required=True, help="root directory")
def test(**kwargs) -> None:
    Task.init(
        project_name="Test",
        task_name="test",
        output_uri=kwargs["root"],
    )
    print(kwargs)


if __name__ == "__main__":
    run()

```
in bash

```
python test.py test -r example
```
## Expected behaviour
As long as click works that way, we should just ignore these None keys.

## Environment
* Python 3.10.8
* Click 8.1.3
* ClearML 1.9.1
* OS Ubuntu 20.04

**Comment by ainoam** [comment]
Thanks for highlighting the issue @chengzegang.

Care to issue a PR?

**Comment by chengzegang** [comment]
> 

no problem

**Comment by chengzegang** [comment]
> Thanks for highlighting the issue @chengzegang.
> 
> Care to issue a PR?

no problem

**Comment by pollfly** [comment]
Hey @chengzegang ! clearml [v1.9.2](https://github.com/allegroai/clearml/releases/tag/v1.9.2) is now out, and `None` values for click keys are ignored
