### ISSUE TITLE
Regarding Hyperparameter Optimization

### ISSUE THREAD

**Issue by pytholic** [allegroai/clearml#909]
When we run the optimization and visualize parallel coordinates, it says "Iteration 0" at the top.

![image](https://user-images.githubusercontent.com/60126503/218358310-cb68661d-1c5c-4b9d-9fef-c90d095602f3.png)

How can we run multiple iterations? I tried wrapping in the `for loop` but it concatenated all results in one experiment instead of creating two iteration charts i.e. Iteration 0 and 1.

Also, what is the use case of running multiple iterations?

**Comment by ainoam** [comment]
Hi @pytholic,

In reality there's no call for multiple iterations. The intent is for multiple optimization efforts to each run their separate task.
This is actually a confusing leakage of the underlying shared infrastructure for model training, where the training iteration is reported along with the plot - In this case, as there're no iterations, a NULL value is used.

We should probably remove the iteration title in this case...

**Comment by pytholic** [comment]
I see. 
@ainoam Can you elaborate a bit about *multiple optimization efforts*?  I am not sure if I fully understood the meaning.

**Comment by ainoam** [comment]
Apologies for not being clear @pytholic.
In "multiple optimization efforts" I meant running HPO multiple times.

**Comment by pytholic** [comment]
Oh I see. @ainoam Actually that was my initial question. How can I run HPO multiple times? And what is the difference of running it once or multiple times. 

Intuitively it feels like if I run HPO for 20 set of parameters, it feels same as running two HPO for 10 set of parameters each.

**Comment by ainoam** [comment]
To the extent that your experiments are consistent and do not include significant random noise - I would imagine there should be no significant difference in running the same HPO process more than once (or, perhaps, the differences between your runs would be exactly those arising from any inherent randomness in your process). To run an HPO process more than once, you can either run your code again (you can modify the task name to make sure you get a new task) or  simply clone your HPO task and and enqueue it to execute it on an available ClearML agent.

> Intuitively it feels like if I run HPO for 20 set of parameters, it feels same as running two HPO for 10 set of parameters each.

Do you mean a set of 20 parameter values divided to two groups, or 20 parameters each time optimizing a subset of those? For the former, you should indeed come to the same result (with your experiment outputs summarized across two tasks). For the latter, that would be significantly different, as the parameter space would be significantly larger.

**Comment by Capsar** [comment]
It seems that this issue / feature request is related to "https://github.com/allegroai/clearml/issues/499" where multiple experiments with the same hyperparameters need to be grouped to see the average (and standard deviation or min/max) of those  hyperparameter settings.

**Comment by ainoam** [comment]
I would tend to agree @Capsar.
Since this issue is more a high-level discussion, I think we'll close this to focus the feature request tracking in a single location.
