### ISSUE TITLE
Getting configuration from task returns empty

### ISSUE THREAD

**Issue by Make42** [allegroai/clearml#918]
I cannot get the configuration from a task. I run

```
from clearml import Task, TaskTypes, Model, OutputModel, InputModel
from clearml.task_parameters import TaskParameters, param, percent_param

parameters = {'var1': 1.0}
task = Task.init(project_name='FirstTrial', task_name='first_trial')
parameters = task.connect(parameters)
parameters['var2'] = 2.0
task.mark_completed()
```

and then later

```
from clearml import Task
task_IDs = Task.query_tasks(project_name='FirstTrial', task_name='first_trial')
mytask = Task.get_task(task_IDs[0])
myconf = mytask.get_configuration_objects()
```

but just `myconf ` is just an empty dict `{}`. I expected that I would get `{'var1': 1.0, 'var2': 2.0}` What is the issue here?

I use clearml 1.9.1, Python 3.9.6, Windows 10, on app.clear.ml.
I asked on https://app.slack.com/client/TT9ATQXJ5/CTK20V944/thread/CTK20V944-1676556098.205589

**Comment by ainoam** [comment]
Thanks for pointing to the original Slack thread @Make42 - As was discussed there:
This should be resolved by replacing `task.mark_completed()` with `task.close()`, and additionally, `parameters = task.connect(parameters)` can later be retrieved with `task.get_parameters()` (where values logged with `connect_configuration` are the ones retrieved with `get_configuration_objects`)

We'll clarify the docs to this effect. In the meantime, I guess we can close this issue?

**Comment by Make42** [comment]
@ainoam: The original issue is solved, but the "lack of understanding / documentation" issue remains. I close here and open a new issue.
