### ISSUE TITLE
docstring of Task.get_tasks

### ISSUE THREAD

**Issue by Make42** [allegroai/clearml#937]
The docstring of https://clear.ml/docs/latest/docs/references/sdk/task/#taskget_tasks contains `task_name` twice. Surely, this is wrong.

**Comment by ainoam** [comment]
Appreciate the feedback @Make42 - We'll be sure to correct.

**Comment by pollfly** [comment]
Hey @Make42! The docstring has been fixed

**Comment by pollfly** [comment]
@Make42, it was done in [this commit](https://github.com/allegroai/clearml/commit/7ca8743d86263f499657748e5747110c57108dc9).

**Comment by Make42** [comment]
@pollfly

![image](https://user-images.githubusercontent.com/4905185/233777335-5206b54c-a40e-4d0a-b1b2-0c4e3d3734df.png)

looks like the text was removed without replacement. This is obviously not the case, looking at https://github.com/allegroai/clearml/blob/7ca8743d86263f499657748e5747110c57108dc9/clearml/task.py#L959 to https://github.com/allegroai/clearml/blob/7ca8743d86263f499657748e5747110c57108dc9/clearml/task.py#L964

What am I missing?

**Comment by ainoam** [comment]
@Make42 As you initially noted - some strings appeared twice.
Redundant text was removed. Initial text remained.

Hopefully this is clearer?
