### ISSUE TITLE
Task.query_tasks should allow TaskTypes for task_filter-ing

### ISSUE THREAD

**Issue by Make42** [allegroai/clearml#938]
If one wants to query a task,

```
task_list = Task.query_tasks(project_name=..., task_filter={'type': [TaskTypes.custom] })
```

throws an error, because only strings are excepted as TaskType. Thus

```
task_list = Task.query_tasks(project_name=..., task_filter={'type': [str(TaskTypes.custom)] })
```

needs to be written. It should be possible to use the first.

**Comment by pollfly** [comment]
Hey @Make42! [v1.10.2](https://github.com/allegroai/clearml/releases/tag/v1.10.2) is now out supporting filtering tasks by TaskTypes in `Task.query_tasks()`

**Comment by Make42** [comment]
@pollfly: In which commit was this fixed? I am interested in how this was solved.

**Comment by pollfly** [comment]
Hey @Make42! It was done in this [commit](https://github.com/allegroai/clearml/commit/7ca8743d86263f499657748e5747110c57108dc9)  

![image](https://user-images.githubusercontent.com/75068813/235337735-dd2595be-cd99-415d-8d87-6a1936225bd1.png)
