### ISSUE TITLE
Keras `BackupAndRestore` and `clearml` dont work together as intended

### ISSUE THREAD

**Issue by lukas-folle-snkeos** [allegroai/clearml#953]
## Describe the bug
When using the callback `BackupAndRestore`, every epoch the weights are save to clearml. Instead, clearml should not upload the weights every epoch and they should only be store locally.

## To reproduce
Use the callback `BackupAndRestore` in your training loop.

## Expected behaviour
Weights should not be uploaded when using `BackupAndRestore`.

**Comment by eugen-ajechiloae-clearml** [comment]
Hi @lukas-folle-snkeos! We save all the weight files saved locally to ClearML as well.
If there are weight files you don't want to be saved to clearml, you can use wildcards in `Task.init`'s `auto_connect_framework` to filter your models. Check the docs under init: https://clear.ml/docs/latest/docs/references/sdk/task/#taskinit. You might also want to check out this GH thread for another way to do this: https://github.com/allegroai/clearml/issues/617

**Comment by lukas-folle-snkeos** [comment]
Thank you!
