### ISSUE TITLE
hide side menu

### ISSUE THREAD

**Issue by akfmdl** [allegroai/clearml#956]
## Proposal Summary
I installed self-hosted cleaml server on my own cluster using helm chart.
I want to hide some of menu with just fixing chart values.yaml file.
<img width="79" alt="image" src="https://user-images.githubusercontent.com/31917080/226566202-b64285c9-5284-4595-885b-82423e3ecf13.png">

## Related Discussion
https://clearml.slack.com/archives/CTK20V944/p1679364191280129

**Comment by ainoam** [comment]
Thanks for suggesting @akfmdl.

Are you looking to block functionality or simply hide the links? What's the use-case that drives this request?

**Comment by akfmdl** [comment]
`simply hide the links`

just hiding from web ui. thanks:)

**Comment by ainoam** [comment]
Thanks for clarifying @akfmdl.

What would be the incentive to hide parts of existing core UI functionality?

**Comment by akfmdl** [comment]
My purpose is giving clearml server to QA team as a monitoring train metric with hiding unnecessary menu

**Comment by akfmdl** [comment]
@ainoam Hello, when do you expect this feature will be developed? Is this included in the future roadmap?

**Comment by ainoam** [comment]
Apologies for the long response time @akfmdl.

The [ClearML Server](https://github.com/allegroai/clearml-server) is provided for open development and has no current plans for blocking any part of it's functionality, ClearML's [commercial](https://clear.ml/) offer includes more granular access controls.
