### ISSUE TITLE
How to log tensorboard reports running in a subprocess

### ISSUE THREAD

**Issue by igolan89** [allegroai/clearml#96]
The output from subprocesses doesn't end up being reported to the trains server.
Here is an example to reproduce:
```python
from trains import Task
import subprocess
import sys

task = Task.init(project_name='examples', task_name='subprocess example')
print("Hello from main proc")
subprocess.run([sys.executable, '-c', "from trains import Task; import os; import time; print('Hello from ' + str(os.getpid())); time.sleep(5);"])
```

I can see the child process print in the console, but not in the log on the server.

**Comment by bmartinn** [comment]
Hi @igolan89 ,

What you're describing is the expect behavior when running the experiment locally (although this is an interesting feature to add).

However, when running your task using _trains-agent_, printouts from subprocesses will be logged in the task's log, sent to the server and be visible in the UI, as you would expect.

**Comment by igolan89** [comment]
Thanks!
Is this the same for tensorboard reports? Will they reach the web UI if used from trains-agent?

**Comment by bmartinn** [comment]
Hi @igolan89,

To allow tensorboard reports made in a subprocess to be logged to the _trains-server_, you'll have to call `Task.init()` inside the subprocess.
