### ISSUE TITLE
`get_reported_scalars` is incorrectly documented for `x_axis` value `timestamp`. 

### ISSUE THREAD

**Issue by jday1** [allegroai/clearml#963]
## Describe the bug

`get_reported_scalars` is incorrectly documented for `x_axis` value `timestamp`. 

## To reproduce
Exact steps to reproduce the bug. Provide example code if possible.

Follow the source code.

`get_reported_scalars` -> `ScalarMetricsIterHistogramRequest`

```
    :param key: Histogram x axis to use: iter - iteration number iso_time - event
        time as ISO formatted string timestamp - event timestamp as milliseconds since
        epoch
```

## Expected behaviour
What is the expected behaviour? What should've happened but didn't?

Documentation should be correct.

## Environment
* Server type (self hosted \ app.clear.ml)
* ClearML SDK Version
* ClearML Server Version (Only for self hosted). Can be found on the bottom right corner of the settings screen.
* Python Version
* OS (Windows \ Linux \ Macos)
## Related Discussion
If this continues a slack thread, please provide a link to the original slack thread.

**Comment by jkhenning** [comment]
@jday1 I'm closing the issue. Please reopen if required.
