### ISSUE TITLE
Model Graph Visualisation

### ISSUE THREAD

**Issue by TTK95** [allegroai/clearml#978]
## Proposal Summary

I propose the addition of a model graph visualization feature to the existing software.

Machine learning models have become increasingly complex over the years, making it difficult for developers and researchers to gain a clear understanding of the structure and connections within the model. A model graph visualization feature would allow users to visualize the structure of their model in a more intuitive way, enabling them to more easily identify and diagnose issues.

## The Feature

The model graph visualization feature would generate a graphical representation of the model, including all layers, connections, and activations. The visualization could be customized by the user to highlight specific components of the model, such as layers with high activation or connections with large weights.

Users would be able to interact with the visualization to explore the structure of the model in more detail. For example, they could click on a particular layer to see a detailed view of its parameters or activation values. They could also zoom in or out to focus on specific parts of the model.

Image for inspiration
![grafik](https://user-images.githubusercontent.com/39856079/232002428-65ff4aaf-e1af-48d1-be79-7d0057f4120a.png)

## Related Discussion
[934](https://github.com/allegroai/clearml/issues/934 )

**Comment by MightyGoldenJA** [comment]
Would really be a nice to have but currently the same could be easily be done just by using the [Netron WebApp](https://netron.app/) or by doing an integration for something like [TorchStudio](https://www.torchstudio.ai/) in my opinion.

**Comment by TTK95** [comment]
@MightyGoldenJA Sure, one can always use a third app.. but it would be nice if it is all in one place, wouldn't it? 
I didn't know TorchStudio, looks nice! But I want to stick with ClearML.

**Comment by ainoam** [comment]
Thanks for suggesting @TTK95.

For tidiness, perhaps we should consolidate this into https://github.com/allegroai/clearml/issues/934?

**Comment by TTK95** [comment]
> Thanks for suggesting @TTK95.
> 
> For tidiness, perhaps we should consolidate this into #934?

yes, please. 👍
