### ISSUE TITLE
Task.query_tasks needs to be elaboration

### ISSUE THREAD

**Issue by Make42** [allegroai/clearml#981]
https://clear.ml/docs/latest/docs/references/sdk/task/#taskquery_tasks mentions "service.tasks.GetAllRequest", but I cannot find where or what that is. Why I can find `tasks.GetAllRequest` mentioned in the code, this does not explain much and I am not able to find the actual `tasks.GetAllRequest`. What is `tasks.GetAllRequest`? Also, I think the respective documentation / docstring should be elaborated.

**Comment by ainoam** [comment]
Hi @Make42,

Indeed the target reference is somewhat ambiguous.

Looking around the page, you'd notice that `GetAllRequest` refers to the backend API which is implemented for multiple API versions e.g. [backend_api.services.v2_23.tasks.GetAllRequest](https://github.com/allegroai/clearml/blob/master/clearml/backend_api/services/v2_23/tasks.py#L8030), which elaborates on the available options.

We'll clarify where this is missing.

**Comment by Make42** [comment]
@ainoam:

> We'll clarify where this is missing.

Thank you! I am sure, am not the only one to not have the idea to search for the term on the page :-)

**Comment by Make42** [comment]
I made https://github.com/allegroai/clearml/pull/982
