### ISSUE TITLE
Scatterplots for Experiment Comparison

### ISSUE THREAD

**Issue by pedro-sidra-isi** [allegroai/clearml#984]
## Proposal Summary
Add a scatterplot view to the Hyperparameters section when comparing experiments:
![image](https://user-images.githubusercontent.com/104914398/233057472-e0ce0bce-7ac6-40ee-a70e-2b32b8014228.png)

Chose an X-Axis from the "Hyperparameter" values and a Y-Axis from the "Scalars".

## Motivation
When exploring my results, I might want to visualize the correlation between a specific hyperparameter and a specific performance metric. 

Plotting an `X-Y` Scatterplot of  `Paremeter - Metric` can be much easier to interpret than a parallel coordinates plot.

## Related Discussion
https://clearml.slack.com/archives/CTK20V944/p1681838738290319

**Comment by ainoam** [comment]
Thanks for proposing @pedro-sidra-isi!

We'll take into account as we plan ClearML's  next versions.

**Comment by pollfly** [comment]
Hey @pedro-sidra-isi! [clearml-server 1.15.0](https://github.com/allegroai/clearml-server/releases/tag/v1.15.0) is now out, supporting scatter plot mode in experiment hyperparameter comparison.
