### ISSUE TITLE
Typo in storage protocol in Logger documentation

### ISSUE THREAD

**Issue by charlienewey** [allegroai/clearml#986]
## Describe the bug
There's a slightly misleading typo in the Logger documentation for the `set_default_upload_destination` method.

## To reproduce
See: https://clear.ml/docs/latest/docs/references/sdk/logger/#set_default_upload_destination
Google's GCS protocol is noted as `gc://` instead of the correct `gs://`

**Comment by charlienewey** [comment]
only smol issue btw

**Comment by ainoam** [comment]
Thanks for noticing @charlienewey.

Care to PR?

**Comment by pzarfos** [comment]
@ainoam Here is a PR to fix the doc comment for `gs://`
- https://github.com/allegroai/clearml/pull/1018

**Comment by ainoam** [comment]
Many thanks @pzarfos!!

**Comment by jkhenning** [comment]
Closing as #1018 was merged some time ago.
