### ISSUE TITLE
No right click in Web UI

### ISSUE THREAD

**Issue by Make42** [allegroai/clearml#990]
Currently, no right click is possible in the Web UI using Edge Browser or Firefox Browser. This can be overridden with shift + right click on Firefox, but should be allowed without the shift. The trick with shift does not work in Edge.

I want this, because I save links as Hyperparameters and I want to right-click and say "Open link in the Tab" and "Open link in new Window" etc.

**Comment by ainoam** [comment]
Thanks for reporting @Make42.

A fix should become available soon.

**Comment by pollfly** [comment]
Hey @Make42! Just letting you know that this issue has been resolved in the recently released [ClearML Server v1.11.0](https://github.com/allegroai/clearml-server/releases/tag/v1.11.0). Let us know if there are any issues :)
